Repository census-instrumentation/opencensus-java, pull requests merged in 2018-08, with the labels that each got.

#1353 Metrics: Move Exemplar to be part of Bucket.
  metrics/src/main/java/io/opencensus/metrics/Distribution.java
  metrics/src/test/java/io/opencensus/metrics/DistributionTest.java
  metrics/src/test/java/io/opencensus/metrics/PointTest.java
  metrics/src/test/java/io/opencensus/metrics/ValueTest.java
Labels: API, cla: yes, metrics

#1354 Fix incorrect argument to Checker Framework, and fix nullness warnings.
  api/src/main/java/io/opencensus/common/ServerStatsFieldEnums.java
  api/src/main/java/io/opencensus/trace/SpanBuilder.java
  build.gradle
  buildscripts/checkstyle.xml
  contrib/log_correlation/stackdriver/src/main/java/io/opencensus/contrib/logcorrelation/stackdriver/OpenCensusTraceLoggingEnhancer.java
  contrib/spring/src/main/java/io/opencensus/contrib/spring/aop/CensusSpringAspect.java
  contrib/spring/src/main/java/io/opencensus/contrib/spring/aop/Handler.java
  exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtils.java
  exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandler.java
  exporters/trace/zipkin/src/main/java/io/opencensus/exporter/trace/zipkin/ZipkinExporterHandler.java
  impl_core/src/main/java/io/opencensus/implcore/stats/MutableAggregation.java
  impl_core/src/main/java/io/opencensus/implcore/stats/RecordUtils.java
  impl_core/src/main/java/io/opencensus/implcore/trace/SpanBuilderImpl.java
Labels: cla: yes, static analysis

#1355 Checker Framework: 2.5.3 -> 2.5.4
  build.gradle
Labels: cla: yes, static analysis

#1356 Update README of Stackdriver stats exporter.
  exporters/stats/stackdriver/README.md
Labels: cla: yes, documentation, exporters

#1357 Add Checker Framework stub file for gRPC Context.Key.
  api/src/main/java/io/opencensus/trace/CurrentSpanUtils.java
  api/src/main/java/io/opencensus/trace/unsafe/ContextUtils.java
  checker-framework/stubs/grpc.astub
Labels: cla: yes, static analysis

#1300 Add the initial version of the TraceState class.
  api/src/main/java/io/opencensus/trace/Tracestate.java
  api/src/test/java/io/opencensus/trace/TracestateTest.java
Labels: cla: yes, tracing

#1358 Minor improvements for Tracestate.
  api/src/main/java/io/opencensus/trace/Tracestate.java
  api/src/test/java/io/opencensus/trace/TracestateTest.java
Labels: cla: yes

#1362 Add a warning about try-with-resource to auto-close spans.
  api/src/main/java/io/opencensus/trace/SpanBuilder.java
Labels: cla: yes

#1360 gradle wrapper --gradle-version 4.9
  examples/gradle/wrapper/gradle-wrapper.jar
  examples/gradle/wrapper/gradle-wrapper.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: cla: yes

#1363 Remove protected method from final class.
  impl_core/src/main/java/io/opencensus/implcore/trace/export/SpanExporterImpl.java
Labels: cla: yes

#1057 Allow users to use custom metric name prefix for Stackdriver
  CHANGELOG.md
  exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtils.java
  exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExporterWorker.java
  exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsConfiguration.java
  exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsExporter.java
  exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtilsTest.java
  exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverExporterWorkerTest.java
  exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsConfigurationTest.java
Labels: API, cla: yes, enhancement, exporters

#1338 Metrics: Produce and store Metrics in Stats impl.
  buildscripts/import-control.xml
  impl_core/build.gradle
  impl_core/src/main/java/io/opencensus/implcore/stats/MeasureToViewMap.java
  impl_core/src/main/java/io/opencensus/implcore/stats/MetricMap.java
  impl_core/src/main/java/io/opencensus/implcore/stats/MetricUtils.java
  impl_core/src/main/java/io/opencensus/implcore/stats/MutableAggregation.java
  impl_core/src/main/java/io/opencensus/implcore/stats/MutableViewData.java
  impl_core/src/test/java/io/opencensus/implcore/stats/MetricMapTest.java
  impl_core/src/test/java/io/opencensus/implcore/stats/MetricUtilsTest.java
Labels: cla: yes, metrics, stats

#1359 Add Tracestate into SpanContext.
  CHANGELOG.md
  api/src/main/java/io/opencensus/trace/SpanContext.java
  api/src/main/java/io/opencensus/trace/Tracestate.java
  api/src/test/java/io/opencensus/trace/SpanContextTest.java
  benchmarks/src/jmh/java/io/opencensus/benchmarks/trace/propagation/BinaryPropagationImplBenchmark.java
  contrib/appengine_standard_util/src/main/java/io/opencensus/contrib/appengine/standard/util/AppEngineCloudTraceContextUtils.java
  contrib/http_util/src/main/java/io/opencensus/contrib/http/util/CloudTraceFormat.java
  impl_core/src/main/java/io/opencensus/implcore/trace/SpanBuilderImpl.java
  impl_core/src/main/java/io/opencensus/implcore/trace/propagation/B3Format.java
  impl_core/src/main/java/io/opencensus/implcore/trace/propagation/BinaryFormatImpl.java
Labels: API, cla: yes, tracing

#1344 Add support for recording Gauges.
  api/src/main/java/io/opencensus/common/ToDoubleFunction.java
  api/src/main/java/io/opencensus/common/ToLongFunction.java
  metrics/src/main/java/io/opencensus/metrics/MetricProducer.java
  metrics/src/main/java/io/opencensus/metrics/MetricRegistry.java
  metrics/src/main/java/io/opencensus/metrics/Metrics.java
  metrics/src/main/java/io/opencensus/metrics/MetricsComponent.java
  metrics/src/main/java/io/opencensus/metrics/export/MetricProducerManager.java
  metrics/src/test/java/io/opencensus/metrics/MetricRegistryTest.java
  metrics/src/test/java/io/opencensus/metrics/MetricsComponentTest.java
  metrics/src/test/java/io/opencensus/metrics/export/MetricProducerManagerTest.java
Labels: API, cla: yes, metrics

#1346 Metrics: Move metrics to opencensus-api.
  all/build.gradle
  api/src/main/java/io/opencensus/metrics/Distribution.java
  api/src/main/java/io/opencensus/metrics/LabelKey.java
  api/src/main/java/io/opencensus/metrics/LabelValue.java
  api/src/main/java/io/opencensus/metrics/Metric.java
  api/src/main/java/io/opencensus/metrics/MetricDescriptor.java
  api/src/main/java/io/opencensus/metrics/MetricProducer.java
  api/src/main/java/io/opencensus/metrics/MetricRegistry.java
  api/src/main/java/io/opencensus/metrics/Metrics.java
  api/src/main/java/io/opencensus/metrics/MetricsComponent.java
  api/src/main/java/io/opencensus/metrics/Point.java
  api/src/main/java/io/opencensus/metrics/TimeSeries.java
  api/src/main/java/io/opencensus/metrics/TimeSeriesCumulative.java
  api/src/main/java/io/opencensus/metrics/TimeSeriesGauge.java
  api/src/main/java/io/opencensus/metrics/TimeSeriesList.java
  api/src/main/java/io/opencensus/metrics/Value.java
  api/src/main/java/io/opencensus/metrics/export/ExportComponent.java
  api/src/main/java/io/opencensus/metrics/export/MetricProducerManager.java
  api/src/main/java/io/opencensus/metrics/package-info.java
  api/src/test/java/io/opencensus/metrics/DistributionTest.java
  api/src/test/java/io/opencensus/metrics/LabelKeyTest.java
  api/src/test/java/io/opencensus/metrics/LabelValueTest.java
  api/src/test/java/io/opencensus/metrics/MetricDescriptorTest.java
  api/src/test/java/io/opencensus/metrics/MetricRegistryTest.java
  api/src/test/java/io/opencensus/metrics/MetricTest.java
  api/src/test/java/io/opencensus/metrics/MetricsComponentTest.java
  api/src/test/java/io/opencensus/metrics/MetricsTest.java
  api/src/test/java/io/opencensus/metrics/PointTest.java
  api/src/test/java/io/opencensus/metrics/TimeSeriesCumulativeTest.java
  api/src/test/java/io/opencensus/metrics/TimeSeriesGaugeTest.java
  api/src/test/java/io/opencensus/metrics/TimeSeriesListTest.java
  api/src/test/java/io/opencensus/metrics/ValueTest.java
  api/src/test/java/io/opencensus/metrics/export/ExportComponentTest.java
  api/src/test/java/io/opencensus/metrics/export/MetricProducerManagerTest.java
  build.gradle
  impl_core/build.gradle
  metrics/README.md
  metrics/build.gradle
  settings.gradle
Labels: API, build, cla: yes, metrics

#1364 Fix metrics tests by adding the RunWith annotation.
  api/src/test/java/io/opencensus/metrics/MetricRegistryTest.java
  api/src/test/java/io/opencensus/metrics/MetricsTest.java
Labels: cla: yes

#1366 Ignore VarInt for coverage.
  buildscripts/codecov.yml
Labels: cla: yes

#1365 Add implementation for gauges.
  impl/src/main/java/io/opencensus/impl/metrics/MetricsComponentImpl.java
  impl/src/test/java/io/opencensus/impl/metrics/MetricsTest.java
  impl_core/src/main/java/io/opencensus/implcore/metrics/Gauge.java
  impl_core/src/main/java/io/opencensus/implcore/metrics/MetricRegistryImpl.java
  impl_core/src/main/java/io/opencensus/implcore/metrics/MetricsComponentImplBase.java
  impl_core/src/test/java/io/opencensus/implcore/metrics/GaugeTest.java
  impl_core/src/test/java/io/opencensus/implcore/metrics/MetricRegistryImplTest.java
  impl_core/src/test/java/io/opencensus/implcore/metrics/MetricsComponentImplBaseTest.java
  impl_lite/src/main/java/io/opencensus/impllite/metrics/MetricsComponentImplLite.java
  impl_lite/src/test/java/io/opencensus/impllite/metrics/MetricsTest.java
Labels: cla: yes, kokoro:force-run

#1369 checkstyle: 8.0 -> 8.12
  api/src/main/java/io/opencensus/common/ServerStatsFieldEnums.java
  api/src/main/java/io/opencensus/stats/BucketBoundaries.java
  api/src/main/java/io/opencensus/trace/NetworkEvent.java
  api/src/main/java/io/opencensus/trace/Span.java
  api/src/main/java/io/opencensus/trace/TraceOptions.java
  api/src/main/java/io/opencensus/trace/export/SampledSpanStore.java
  api/src/main/java/io/opencensus/trace/propagation/BinaryFormat.java
  build.gradle
  buildscripts/checkstyle.xml
  buildscripts/kokoro/linux_presubmit.sh
  contrib/grpc_util/src/main/java/io/opencensus/contrib/grpc/util/StatusConverter.java
  contrib/spring/src/main/java/io/opencensus/contrib/spring/aop/CensusSpringAspect.java
  contrib/spring/src/main/java/io/opencensus/contrib/spring/aop/CensusSpringSqlAspect.java
  contrib/spring/src/main/java/io/opencensus/contrib/spring/aop/Traced.java
  scripts/travis_script
Labels: cla: yes, static analysis

#1370 Fix deprecation warnings in OpenCensusTraceLoggingEnhancerTest.java.
  contrib/log_correlation/stackdriver/src/test/java/io/opencensus/contrib/logcorrelation/stackdriver/OpenCensusTraceLoggingEnhancerTest.java
Labels: cla: yes, refactoring

#1368 Fix stats to metrics implementation.
  impl_core/src/main/java/io/opencensus/implcore/stats/MeasureToViewMap.java
  impl_core/src/main/java/io/opencensus/implcore/stats/MetricMap.java
  impl_core/src/main/java/io/opencensus/implcore/stats/MutableViewData.java
  impl_core/src/main/java/io/opencensus/implcore/stats/StatsManager.java
  impl_core/src/test/java/io/opencensus/implcore/stats/MetricMapTest.java
Labels: cla: yes, metrics

#1367 Update all targets to at least java7 and android14
  api/build.gradle
  contrib/agent/build.gradle
  contrib/exemplar_util/build.gradle
  contrib/grpc_metrics/build.gradle
  contrib/grpc_util/build.gradle
  contrib/http_util/build.gradle
  contrib/log_correlation/stackdriver/build.gradle
  contrib/monitored_resource_util/build.gradle
  contrib/spring/build.gradle
  exporters/stats/prometheus/build.gradle
  exporters/stats/prometheus/src/main/java/io/opencensus/exporter/stats/prometheus/PrometheusStatsCollector.java
  exporters/stats/signalfx/build.gradle
  exporters/stats/signalfx/src/main/java/io/opencensus/exporter/stats/signalfx/SignalFxStatsExporterWorkerThread.java
  exporters/stats/stackdriver/build.gradle
  exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExporterWorker.java
  exporters/trace/instana/build.gradle
  exporters/trace/jaeger/build.gradle
  exporters/trace/logging/build.gradle
  exporters/trace/stackdriver/build.gradle
  exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandler.java
  exporters/trace/zipkin/build.gradle
  impl/build.gradle
  impl_core/build.gradle
  impl_lite/build.gradle
  testing/build.gradle
Labels: cla: yes

#1373 Use the internal get version for getting the current state.
  impl_core/src/main/java/io/opencensus/implcore/stats/StatsManager.java
Labels: cla: yes

#1374 Build: Update Cloud Auth, Beta and GA versions.
  build.gradle
Labels: build, cla: yes

#1372 Remove match pattern from MutableAggregation.
  impl_core/src/main/java/io/opencensus/implcore/stats/IntervalBucket.java
  impl_core/src/main/java/io/opencensus/implcore/stats/MetricUtils.java
  impl_core/src/main/java/io/opencensus/implcore/stats/MutableAggregation.java
  impl_core/src/main/java/io/opencensus/implcore/stats/MutableViewData.java
  impl_core/src/main/java/io/opencensus/implcore/stats/RecordUtils.java
  impl_core/src/test/java/io/opencensus/implcore/stats/IntervalBucketTest.java
  impl_core/src/test/java/io/opencensus/implcore/stats/MetricUtilsTest.java
  impl_core/src/test/java/io/opencensus/implcore/stats/MutableAggregationTest.java
  impl_core/src/test/java/io/opencensus/implcore/stats/RecordUtilsTest.java
  impl_core/src/test/java/io/opencensus/implcore/stats/StatsTestUtil.java
  impl_core/src/test/java/io/opencensus/implcore/stats/ViewManagerImplTest.java
Labels: cla: yes

#1375 Make an internal function static.
  impl_core/src/main/java/io/opencensus/implcore/stats/MetricUtils.java
Labels: cla: yes, enhancement, stats

#1377 Implement CurrentStatsState using atomic variables.
  CHANGELOG.md
  findbugs-exclude.xml
  impl_core/src/main/java/io/opencensus/implcore/stats/CurrentStatsState.java
  impl_core/src/main/java/io/opencensus/implcore/stats/StatsComponentImplBase.java
Labels: cla: yes

#1381 Extract logic about current state in internal class and share between stats and tags.
  impl_core/src/main/java/io/opencensus/implcore/internal/CurrentState.java
  impl_core/src/main/java/io/opencensus/implcore/stats/CurrentStatsState.java
  impl_core/src/main/java/io/opencensus/implcore/stats/MeasureToViewMap.java
  impl_core/src/main/java/io/opencensus/implcore/stats/MutableViewData.java
  impl_core/src/main/java/io/opencensus/implcore/stats/StatsComponentImplBase.java
  impl_core/src/main/java/io/opencensus/implcore/stats/StatsManager.java
  impl_core/src/main/java/io/opencensus/implcore/tags/CurrentTaggingState.java
  impl_core/src/main/java/io/opencensus/implcore/tags/TaggerImpl.java
  impl_core/src/main/java/io/opencensus/implcore/tags/TagsComponentImplBase.java
  impl_core/src/main/java/io/opencensus/implcore/tags/propagation/TagContextBinarySerializerImpl.java
  impl_core/src/main/java/io/opencensus/implcore/tags/propagation/TagPropagationComponentImpl.java
  impl_core/src/test/java/io/opencensus/implcore/internal/CurrentStateTest.java
  impl_core/src/test/java/io/opencensus/implcore/stats/MeasureToViewMapTest.java
  impl_core/src/test/java/io/opencensus/implcore/tags/CurrentTaggingStateTest.java
  impl_core/src/test/java/io/opencensus/implcore/tags/ScopedTagContextsTest.java
  impl_core/src/test/java/io/opencensus/implcore/tags/TagContextImplTest.java
Labels: cla: yes, refactoring

#1380 Metrics: Combine TimeSeriesCumulative and TimeSeriesGauge.
  api/src/main/java/io/opencensus/metrics/Metric.java
  api/src/main/java/io/opencensus/metrics/TimeSeries.java
  api/src/main/java/io/opencensus/metrics/TimeSeriesCumulative.java
  api/src/main/java/io/opencensus/metrics/TimeSeriesGauge.java
  api/src/main/java/io/opencensus/metrics/TimeSeriesList.java
  api/src/test/java/io/opencensus/metrics/MetricTest.java
  api/src/test/java/io/opencensus/metrics/TimeSeriesGaugeTest.java
  api/src/test/java/io/opencensus/metrics/TimeSeriesListTest.java
  api/src/test/java/io/opencensus/metrics/TimeSeriesTest.java
  impl_core/src/main/java/io/opencensus/implcore/metrics/Gauge.java
  impl_core/src/main/java/io/opencensus/implcore/stats/MutableViewData.java
  impl_core/src/test/java/io/opencensus/implcore/metrics/GaugeTest.java
  impl_core/src/test/java/io/opencensus/implcore/metrics/MetricRegistryImplTest.java
Labels: API, cla: yes, metrics

#1386 Access current span using gRPC context key in OpenCensusTraceLoggingEnhancer.
  contrib/log_correlation/stackdriver/src/main/java/io/opencensus/contrib/logcorrelation/stackdriver/OpenCensusTraceLoggingEnhancer.java
Labels: cla: yes, tracing

#1371 Start adding log correlation for Log4j.
  all/build.gradle
  build.gradle
  buildscripts/import-control.xml
  contrib/log_correlation/log4j/README.md
  contrib/log_correlation/log4j/build.gradle
  contrib/log_correlation/log4j/src/main/java/io/opencensus/contrib/logcorrelation/log4j/OpenCensusTraceContextDataInjector.java
  contrib/log_correlation/log4j/src/test/java/io/opencensus/contrib/logcorrelation/log4j/AbstractOpenCensusLog4jLogCorrelationTest.java
  contrib/log_correlation/log4j/src/test/java/io/opencensus/contrib/logcorrelation/log4j/OpenCensusLog4jLogCorrelationAllSpansTest.java
  contrib/log_correlation/log4j/src/test/java/io/opencensus/contrib/logcorrelation/log4j/OpenCensusLog4jLogCorrelationNoSpansTest.java
  contrib/log_correlation/log4j/src/test/java/io/opencensus/contrib/logcorrelation/log4j/OpenCensusLog4jLogCorrelationSampledSpansTest.java
  contrib/log_correlation/log4j/src/test/java/io/opencensus/contrib/logcorrelation/log4j/OpenCensusTraceContextDataInjectorTest.java
  settings.gradle
Labels: cla: yes, tracing

#1385 Use Utils.checkNotNull instead of writing the null check.
  api/src/main/java/io/opencensus/trace/export/SpanData.java
Labels: cla: yes

#1392 Add get/from{Byte} methods on TraceOptions and deprecate get/from{Bytes}.
  CHANGELOG.md
  api/src/main/java/io/opencensus/trace/TraceOptions.java
  api/src/test/java/io/opencensus/trace/TraceOptionsTest.java
  benchmarks/src/jmh/java/io/opencensus/benchmarks/trace/propagation/BinaryPropagationImplBenchmark.java
  exporters/trace/instana/src/test/java/io/opencensus/exporter/trace/instana/InstanaExporterHandlerTest.java
  exporters/trace/zipkin/src/test/java/io/opencensus/exporter/trace/zipkin/ZipkinExporterHandlerTest.java
  impl_core/src/main/java/io/opencensus/implcore/trace/propagation/BinaryFormatImpl.java
  impl_core/src/test/java/io/opencensus/implcore/trace/propagation/B3FormatTest.java
  impl_core/src/test/java/io/opencensus/implcore/trace/propagation/BinaryFormatImplTest.java
Labels: cla: yes

#1390 Refactor propagation benchmarks and add b3format benchmarks.
  benchmarks/build.gradle
  benchmarks/src/jmh/java/io/opencensus/benchmarks/trace/propagation/B3FormatImplBenchmark.java
  benchmarks/src/jmh/java/io/opencensus/benchmarks/trace/propagation/BinaryFormatImplBenchmark.java
  benchmarks/src/jmh/java/io/opencensus/benchmarks/trace/propagation/TextFormatBenchmarkBase.java
  impl_core/src/test/java/io/opencensus/implcore/trace/propagation/B3FormatTest.java
Labels: cla: yes

#1394 Avoid doing string formatting when calling checkArgument.
  api/src/main/java/io/opencensus/internal/Utils.java
  api/src/main/java/io/opencensus/stats/Measure.java
  api/src/main/java/io/opencensus/tags/TagKey.java
  api/src/main/java/io/opencensus/tags/TagValue.java
  api/src/main/java/io/opencensus/trace/SpanId.java
  api/src/main/java/io/opencensus/trace/TraceId.java
  api/src/main/java/io/opencensus/trace/TraceOptions.java
  api/src/main/java/io/opencensus/trace/Tracestate.java
  api/src/test/java/io/opencensus/internal/UtilsTest.java
  build.gradle
  findbugs-exclude.xml
Labels: cla: yes

#1396 Avoid doing string formatting when calling checkArgument. (#1394)
  api/src/main/java/io/opencensus/internal/Utils.java
  api/src/main/java/io/opencensus/stats/Measure.java
  api/src/main/java/io/opencensus/tags/TagKey.java
  api/src/main/java/io/opencensus/tags/TagValue.java
  api/src/main/java/io/opencensus/trace/SpanId.java
  api/src/main/java/io/opencensus/trace/TraceId.java
  api/src/main/java/io/opencensus/trace/TraceOptions.java
  api/src/main/java/io/opencensus/trace/Tracestate.java
  api/src/test/java/io/opencensus/internal/UtilsTest.java
  build.gradle
  findbugs-exclude.xml
Labels: cla: yes, release

#1393 Remove guava dependency from the API artifact.
  api/build.gradle
  api/src/main/java/io/opencensus/trace/SpanId.java
  api/src/main/java/io/opencensus/trace/TraceId.java
  api/src/main/java/io/opencensus/trace/internal/LowerCaseBase16Encoding.java
  api/src/test/java/io/opencensus/trace/internal/LowerCaseBase16EncodingTest.java
  buildscripts/import-control.xml
  contrib/grpc_metrics/build.gradle
  exporters/stats/prometheus/build.gradle
  exporters/stats/signalfx/build.gradle
  exporters/stats/stackdriver/build.gradle
  exporters/trace/instana/build.gradle
  exporters/trace/jaeger/build.gradle
  exporters/trace/stackdriver/build.gradle
  exporters/trace/zipkin/build.gradle
  testing/build.gradle
Labels: cla: yes

#1397 Prepare for v0.15.1 release.
  api/src/main/java/io/opencensus/common/OpenCensusLibraryInformation.java
  build.gradle
  examples/build.gradle
  examples/pom.xml
Labels: cla: yes, release

#1399 Add an entry about v0.15.1 release in CHANGELOG.
  CHANGELOG.md
Labels: cla: yes, documentation, release

#1398 Update release versions for all readme and build files.
  README.md
  contrib/appengine_standard_util/README.md
  contrib/grpc_util/README.md
  contrib/http_util/README.md
  contrib/log_correlation/stackdriver/README.md
  contrib/monitored_resource_util/README.md
  contrib/zpages/README.md
  examples/build.gradle
  examples/opencensus_workspace.bzl
  examples/pom.xml
  exporters/stats/prometheus/README.md
  exporters/stats/signalfx/README.md
  exporters/stats/stackdriver/README.md
  exporters/trace/instana/README.md
  exporters/trace/jaeger/README.md
  exporters/trace/logging/README.md
  exporters/trace/stackdriver/README.md
  exporters/trace/zipkin/README.md
Labels: cla: yes, documentation, release

#1404 Update gRPC version to 1.14.
  build.gradle
  contrib/agent/src/integration-test/java/io/opencensus/contrib/agent/instrumentation/ThreadInstrumentationIT.java
  contrib/agent/src/main/java/io/opencensus/contrib/agent/instrumentation/ContextStrategyImpl.java
Labels: build, cla: yes

#1388 Examples : set sampler to always sample
  examples/src/main/java/io/opencensus/examples/grpc/helloworld/HelloWorldUtils.java
  examples/src/main/java/io/opencensus/examples/trace/MultiSpansContextTracing.java
  examples/src/main/java/io/opencensus/examples/trace/MultiSpansScopedTracing.java
  examples/src/main/java/io/opencensus/examples/trace/MultiSpansTracing.java
  examples/src/main/java/io/opencensus/examples/trace/Utils.java
Labels: cla: yes, examples, tracing
