Repository census-instrumentation/opencensus-java, pull requests merged in 2018-05, with the labels that each got.

#1168 Add build script and configure for Internal CI build.
  buildscripts/kokoro/linux.cfg
  buildscripts/kokoro/linux.sh
Labels: cla: yes, continuous integration

#1169 Clarify the order of pushing the release branch and deploying in RELEASING.md.
  RELEASING.md
Labels: cla: yes, documentation, release

#1170 Fix a typo on displaying Aggregation Type for a View on StatsZ page.
  CHANGELOG.md
  contrib/zpages/src/main/java/io/opencensus/contrib/zpages/StatszZPageHandler.java
  contrib/zpages/src/test/java/io/opencensus/contrib/zpages/StatszZPageHandlerTest.java
Labels: bug, cla: yes, zpages

#1167 Set bucket bounds as le labels for Prometheus exporter.
  CHANGELOG.md
  exporters/stats/prometheus/README.md
  exporters/stats/prometheus/src/main/java/io/opencensus/exporter/stats/prometheus/PrometheusExportUtils.java
  exporters/stats/prometheus/src/main/java/io/opencensus/exporter/stats/prometheus/PrometheusStatsCollector.java
  exporters/stats/prometheus/src/test/java/io/opencensus/exporter/stats/prometheus/PrometheusExportUtilsTest.java
  exporters/stats/prometheus/src/test/java/io/opencensus/exporter/stats/prometheus/PrometheusStatsCollectorTest.java
Labels: cla: yes, enhancement, exporters, stats

#1173 Release
  api/src/main/java/io/opencensus/common/OpenCensusLibraryInformation.java
  build.gradle
  examples/build.gradle
  examples/pom.xml
Labels: cla: yes, release

#1174 Update CHANGELOG about v0.13.1 release.
  CHANGELOG.md
Labels: cla: yes, documentation, release

#1175 Add missing Nullable annotation to Functions.returnNull().
  api/src/main/java/io/opencensus/common/Functions.java
  contrib/zpages/src/main/java/io/opencensus/contrib/zpages/TracezZPageHandler.java
  exporters/trace/instana/src/main/java/io/opencensus/exporter/trace/instana/InstanaExporterHandler.java
  exporters/trace/zipkin/src/main/java/io/opencensus/exporter/trace/zipkin/ZipkinExporterHandler.java
Labels: cla: yes, common, static analysis

#1176 Checker Framework: 2.5.0 -> 2.5.1
  api/src/main/java/io/opencensus/stats/NoopStats.java
  build.gradle
  impl_core/src/main/java/io/opencensus/implcore/stats/MutableViewData.java
Labels: cla: yes, static analysis

#1178 Update release versions for all readme and build files.
  README.md
  contrib/grpc_util/README.md
  contrib/http_util/README.md
  contrib/zpages/README.md
  examples/build.gradle
  examples/opencensus_workspace.bzl
  examples/pom.xml
  exporters/stats/prometheus/README.md
  exporters/stats/signalfx/README.md
  exporters/stats/stackdriver/README.md
  exporters/trace/instana/README.md
  exporters/trace/jaeger/README.md
  exporters/trace/logging/README.md
  exporters/trace/stackdriver/README.md
  exporters/trace/zipkin/README.md
Labels: cla: yes, documentation, release

#1180 Add kokoro build scripts for windows platform.
  buildscripts/kokoro/windows.bat
  buildscripts/kokoro/windows.cfg
Labels: cla: yes

#1181 Mention updating CHANGELOG in releasing instruction.
  RELEASING.md
Labels: cla: yes, documentation, release

#1182 Add kokoro build scripts for osx platform.
  buildscripts/kokoro/linux.sh
  buildscripts/kokoro/macos.cfg
Labels: cla: yes

#1183 Map http attributes to the stackdriver format, resolves #1153
  exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandler.java
  exporters/trace/stackdriver/src/test/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandlerProtoTest.java
Labels: cla: yes, exporters, tracing

#1185 Map http attributes to the stackdriver format, resolves #1153 (#1183)
  exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandler.java
  exporters/trace/stackdriver/src/test/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandlerProtoTest.java
Labels: cla: yes, release

#1187 Release
  api/src/main/java/io/opencensus/common/OpenCensusLibraryInformation.java
  build.gradle
  examples/build.gradle
  examples/pom.xml
Labels: cla: yes, release

#1188 Update CHANGELOG about v0.13.2 release.
  CHANGELOG.md
Labels: cla: yes, documentation, release

#1190 Update release versions for all readme and build files.
  README.md
  contrib/grpc_util/README.md
  contrib/http_util/README.md
  contrib/zpages/README.md
  examples/build.gradle
  examples/opencensus_workspace.bzl
  examples/pom.xml
  exporters/stats/prometheus/README.md
  exporters/stats/signalfx/README.md
  exporters/stats/stackdriver/README.md
  exporters/trace/instana/README.md
  exporters/trace/jaeger/README.md
  exporters/trace/logging/README.md
  exporters/trace/stackdriver/README.md
  exporters/trace/zipkin/README.md
Labels: cla: yes, documentation, release

#1189 Update CHANGELOG about v0.13.2 release. (#1188)
  CHANGELOG.md
Labels: cla: yes, documentation, release

#1191 Update Google Cloud and Auth version.
  build.gradle
Labels: cla: yes

#1192 Remove warning suppression in DisruptorEventQueue.
  impl/src/main/java/io/opencensus/impl/internal/DisruptorEventQueue.java
Labels: cla: yes

#1193 Update a @since tag for the next release.
  api/src/main/java/io/opencensus/trace/export/ExportComponent.java
Labels: cla: yes

#1196 Remove PublicForTesting from Status.CanonicalCode.toStatus() (fixes #976).
  api/src/main/java/io/opencensus/trace/Status.java
Labels: API, cla: yes, tracing

#1198 Throw IllegalArgumentException when Duration.create receives invalid arguments.
  CHANGELOG.md
  api/src/main/java/io/opencensus/common/Duration.java
  api/src/test/java/io/opencensus/common/DurationTest.java
Labels: API, cla: yes, common

#1199 Throw IllegalArgumentException when Timestamp.create receives invalid arguments.
  CHANGELOG.md
  api/src/main/java/io/opencensus/common/Timestamp.java
  api/src/test/java/io/opencensus/common/TimestampTest.java
  exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtils.java
  exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtilsTest.java
Labels: API, cla: yes, common

#1203 Prometheus exporter: remove namespace and prefix for help message.
  CHANGELOG.md
  exporters/stats/prometheus/src/main/java/io/opencensus/exporter/stats/prometheus/PrometheusExportUtils.java
  exporters/stats/prometheus/src/test/java/io/opencensus/exporter/stats/prometheus/PrometheusExportUtilsTest.java
  exporters/stats/prometheus/src/test/java/io/opencensus/exporter/stats/prometheus/PrometheusStatsCollectorTest.java
Labels: cla: yes, enhancement, exporters, stats

#1205 Stackdriver Trace Exporter: update README about auth setup and project id in bad format.
  exporters/trace/stackdriver/README.md
Labels: cla: yes, documentation, exporters

#1206 Update versions for monitored resource util README.
  RELEASING.md
  contrib/monitored_resource_util/README.md
Labels: cla: yes, documentation

#1200 To bring parity with travis build add missing tasks to kokoro build.
  buildscripts/kokoro/linux_build.cfg
  buildscripts/kokoro/linux_example_bazel.cfg
  buildscripts/kokoro/linux_example_format.cfg
  buildscripts/kokoro/linux_example_gradle.cfg
  buildscripts/kokoro/linux_example_license.cfg
  buildscripts/kokoro/linux_example_maven.cfg
  buildscripts/kokoro/linux_framework.cfg
  buildscripts/kokoro/linux_git_history.cfg
  buildscripts/kokoro/linux_presubmit.sh
  scripts/check-git-history.py
Labels: cla: yes, continuous integration

#1210 Run codecov reporting only if running as a part of kokoro build.
  buildscripts/kokoro/linux_presubmit.sh
Labels: cla: yes, continuous integration

#1211 Starts adding a metrics package.
  api/src/main/java/io/opencensus/stats/metrics/package-info.java
Labels: API, cla: yes, documentation, stats

#1217 Upgrade Prometheus to the latest version.
  build.gradle
Labels: cla: yes, exporters

#1219 Overwrite the sampling probability to default for stats exporters.
  exporters/stats/prometheus/src/main/java/io/opencensus/exporter/stats/prometheus/PrometheusStatsCollector.java
  exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExporterWorker.java
  exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandler.java
Labels: cla: yes, enhancement, exporters

#1214 Add util contrib package for AppEngine standard.
  .gitignore
  CHANGELOG.md
  all/build.gradle
  build.gradle
  buildscripts/import-control.xml
  contrib/appengine_standard_util/README.md
  contrib/appengine_standard_util/build.gradle
  contrib/appengine_standard_util/src/main/java/io/opencensus/contrib/appengine/standard/util/AppEngineCloudTraceContextUtils.java
  contrib/appengine_standard_util/src/main/proto/trace_id.proto
  contrib/appengine_standard_util/src/test/java/io/opencensus/contrib/appengine/standard/util/AppEngineCloudTraceContextUtilsTest.java
  findbugs-exclude.xml
  settings.gradle
Labels: action required, cla: yes, tracing

#1221 Add a note about Guava version conflicts in cloud client library.
  exporters/stats/stackdriver/README.md
Labels: cla: yes, documentation, exporters, stats

#1222 Update grpc and jagger.
  build.gradle
  exporters/trace/jaeger/build.gradle
  exporters/trace/jaeger/src/main/java/io/opencensus/exporter/trace/jaeger/JaegerExporterHandler.java
  exporters/trace/jaeger/src/test/java/io/opencensus/exporter/trace/jaeger/JaegerExporterHandlerTest.java
Labels: cla: yes

#1197 Add @Internal to io.opencensus.contrib.agent.Settings constructor (issue #977).
  contrib/agent/src/main/java/io/opencensus/contrib/agent/Settings.java
Labels: agent, cla: yes
