Repository census-instrumentation/opencensus-java, pull requests merged in 2018-11, with the labels that each got.

#1528 Update opencensus-contrib-log-correlation-log4j2 to match log correlation spec.
  CHANGELOG.md
  contrib/log_correlation/log4j2/README.md
  contrib/log_correlation/log4j2/src/main/java/io/opencensus/contrib/logcorrelation/log4j2/OpenCensusTraceContextDataInjector.java
  contrib/log_correlation/log4j2/src/test/java/io/opencensus/contrib/logcorrelation/log4j2/AbstractOpenCensusLog4jLogCorrelationTest.java
  contrib/log_correlation/log4j2/src/test/java/io/opencensus/contrib/logcorrelation/log4j2/OpenCensusLog4jLogCorrelationAllSpansTest.java
  contrib/log_correlation/log4j2/src/test/java/io/opencensus/contrib/logcorrelation/log4j2/OpenCensusTraceContextDataInjectorTest.java
Labels: cla: yes, tracing

#1530 Remove "span selection" feature from opencensus-contrib-log-correlation-stackdriver.
  contrib/log_correlation/stackdriver/README.md
  contrib/log_correlation/stackdriver/src/main/java/io/opencensus/contrib/logcorrelation/stackdriver/OpenCensusTraceLoggingEnhancer.java
  contrib/log_correlation/stackdriver/src/test/java/io/opencensus/contrib/logcorrelation/stackdriver/OpenCensusTraceLoggingEnhancerTest.java
Labels: cla: yes, tracing

#1499 ignore negative bucket bounds
  CHANGELOG.md
  api/src/main/java/io/opencensus/stats/BucketBoundaries.java
  api/src/main/java/io/opencensus/stats/NoopStats.java
  api/src/test/java/io/opencensus/stats/AggregationTest.java
  api/src/test/java/io/opencensus/stats/BucketBoundariesTest.java
  api/src/test/java/io/opencensus/stats/NoopStatsTest.java
  contrib/http_util/src/test/java/io/opencensus/contrib/http/util/HttpViewConstantsTest.java
  contrib/zpages/src/test/java/io/opencensus/contrib/zpages/StatszZPageHandlerTest.java
  impl_core/src/main/java/io/opencensus/implcore/stats/MeasureMapImpl.java
  impl_core/src/main/java/io/opencensus/implcore/stats/MutableAggregation.java
  impl_core/src/test/java/io/opencensus/implcore/stats/MutableAggregationTest.java
  impl_core/src/test/java/io/opencensus/implcore/stats/RecordUtilsTest.java
  impl_core/src/test/java/io/opencensus/implcore/stats/StatsRecorderImplTest.java
  impl_core/src/test/java/io/opencensus/implcore/stats/ViewManagerImplTest.java
Labels: cla: yes

#1529 Remove "span selection" feature from opencensus-contrib-log-correlation-log4j2.
  contrib/log_correlation/log4j2/README.md
  contrib/log_correlation/log4j2/build.gradle
  contrib/log_correlation/log4j2/src/main/java/io/opencensus/contrib/logcorrelation/log4j2/ContextDataUtils.java
  contrib/log_correlation/log4j2/src/main/java/io/opencensus/contrib/logcorrelation/log4j2/OpenCensusTraceContextDataInjector.java
  contrib/log_correlation/log4j2/src/test/java/io/opencensus/contrib/logcorrelation/log4j2/AbstractOpenCensusLog4jLogCorrelationTest.java
  contrib/log_correlation/log4j2/src/test/java/io/opencensus/contrib/logcorrelation/log4j2/OpenCensusLog4jLogCorrelationNoSpansTest.java
  contrib/log_correlation/log4j2/src/test/java/io/opencensus/contrib/logcorrelation/log4j2/OpenCensusLog4jLogCorrelationSampledSpansTest.java
  contrib/log_correlation/log4j2/src/test/java/io/opencensus/contrib/logcorrelation/log4j2/OpenCensusLog4jLogCorrelationTest.java
  contrib/log_correlation/log4j2/src/test/java/io/opencensus/contrib/logcorrelation/log4j2/OpenCensusTraceContextDataInjectorTest.java
Labels: cla: yes, tracing

#1532 Temporarily remove "traceSampled" label from Stackdriver log correlation.
  contrib/log_correlation/stackdriver/README.md
  contrib/log_correlation/stackdriver/src/main/java/io/opencensus/contrib/logcorrelation/stackdriver/OpenCensusTraceLoggingEnhancer.java
  contrib/log_correlation/stackdriver/src/test/java/io/opencensus/contrib/logcorrelation/stackdriver/OpenCensusTraceLoggingEnhancerTest.java
Labels: cla: yes, tracing

#1533 Remove warning about Stackdriver log correlation being experimental.
  CHANGELOG.md
  contrib/log_correlation/stackdriver/README.md
  contrib/log_correlation/stackdriver/src/main/java/io/opencensus/contrib/logcorrelation/stackdriver/OpenCensusTraceLoggingEnhancer.java
Labels: cla: yes, tracing

#1535 Replace OpenCensusTraceLoggingEnhancer(String) constructor with factory method.
  contrib/log_correlation/stackdriver/src/main/java/io/opencensus/contrib/logcorrelation/stackdriver/OpenCensusTraceLoggingEnhancer.java
  contrib/log_correlation/stackdriver/src/test/java/io/opencensus/contrib/logcorrelation/stackdriver/OpenCensusTraceLoggingEnhancerTest.java
Labels: cla: yes, tracing

#1538 Hide methods in OpenCensusTraceLoggingEnhancer that aren't necessary currently.
  contrib/log_correlation/stackdriver/src/main/java/io/opencensus/contrib/logcorrelation/stackdriver/OpenCensusTraceLoggingEnhancer.java
  contrib/log_correlation/stackdriver/src/test/java/io/opencensus/contrib/logcorrelation/stackdriver/OpenCensusTraceLoggingEnhancerTest.java
Labels: cla: yes, tracing

#1540 Example/Stats/Stackdriver: consistent with stackdriver doc example
  examples/BUILD.bazel
  examples/README.md
  examples/build.gradle
  examples/pom.xml
  examples/src/main/java/io/opencensus/examples/stats/StackdriverExample.java
  examples/src/main/java/io/opencensus/examples/stats/StackdriverQuickstart.java
Labels: cla: yes

#1541 Exclude OC-Agent exporter from this release for now.
  build.gradle
Labels: cla: yes, release

#1542 Remove min/max from Distribution.
  CHANGELOG.md
  api/src/main/java/io/opencensus/stats/AggregationData.java
  api/src/test/java/io/opencensus/stats/AggregationDataTest.java
  api/src/test/java/io/opencensus/stats/ViewDataTest.java
  impl_core/src/main/java/io/opencensus/implcore/stats/MutableAggregation.java
  impl_core/src/test/java/io/opencensus/implcore/stats/MutableAggregationTest.java
  impl_core/src/test/java/io/opencensus/implcore/stats/RecordUtilsTest.java
  impl_core/src/test/java/io/opencensus/implcore/stats/StatsTestUtil.java
Labels: API, cla: yes, stats

#1545 Release
  api/src/main/java/io/opencensus/common/OpenCensusLibraryInformation.java
  build.gradle
  examples/build.gradle
  examples/pom.xml
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentNodeUtils.java
  exporters/trace/ocagent/src/test/java/io/opencensus/exporter/trace/ocagent/OcAgentNodeUtilsTest.java
Labels: cla: yes, release

#1536 Improve handling of null project ID in Stackdriver log correlation.
  checker-framework/stubs/google-cloud-java.astub
  contrib/log_correlation/stackdriver/src/main/java/io/opencensus/contrib/logcorrelation/stackdriver/OpenCensusTraceLoggingEnhancer.java
  exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsExporter.java
  exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverExporter.java
  exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverTraceExporter.java
Labels: cla: yes, tracing

#1546 Update CHANGELOG.
  CHANGELOG.md
Labels: build, cla: yes, documentation

#1549 Update release versions for all readme and build files.
  README.md
  contrib/appengine_standard_util/README.md
  contrib/exemplar_util/README.md
  contrib/grpc_util/README.md
  contrib/http_util/README.md
  contrib/log_correlation/log4j2/README.md
  contrib/log_correlation/stackdriver/README.md
  contrib/monitored_resource_util/README.md
  contrib/spring/README.md
  contrib/spring_sleuth_v1x/README.md
  contrib/zpages/README.md
  examples/build.gradle
  examples/pom.xml
  exporters/stats/prometheus/README.md
  exporters/stats/signalfx/README.md
  exporters/stats/stackdriver/README.md
  exporters/trace/instana/README.md
  exporters/trace/jaeger/README.md
  exporters/trace/logging/README.md
  exporters/trace/stackdriver/README.md
  exporters/trace/zipkin/README.md
Labels: cla: yes, documentation, release

#1550 Checker Framework: 2.5.5 -> 2.5.6
  build.gradle
Labels: cla: yes, static analysis

#1552 Add few more tests in preparation to change the internal representation of the Span/Trace id.
  api/src/test/java/io/opencensus/trace/SpanIdTest.java
  api/src/test/java/io/opencensus/trace/TraceIdTest.java
Labels: cla: yes

#1551 Error Prone: 2.3.1 -> 2.3.2
  api/src/main/java/io/opencensus/trace/Span.java
  api/src/test/java/io/opencensus/common/ServerStatsEncodingTest.java
  api/src/test/java/io/opencensus/trace/samplers/SamplersTest.java
  build.gradle
  contrib/agent/src/jmh/java/io/opencensus/contrib/agent/instrumentation/ThreadInstrumentationBenchmark.java
  contrib/agent/src/main/java/io/opencensus/contrib/agent/instrumentation/ExecutorInstrumentation.java
  contrib/agent/src/main/java/io/opencensus/contrib/agent/instrumentation/ThreadInstrumentation.java
  contrib/agent/src/main/java/io/opencensus/contrib/agent/instrumentation/UrlInstrumentation.java
  contrib/dropwizard/src/main/java/io/opencensus/contrib/dropwizard/DropWizardMetrics.java
  contrib/dropwizard/src/test/java/io/opencensus/contrib/dropwizard/DropWizardMetricsTest.java
  contrib/http_util/src/main/java/io/opencensus/contrib/http/util/HttpMeasureConstants.java
  contrib/zpages/src/main/java/io/opencensus/contrib/zpages/StatszZPageHandler.java
  contrib/zpages/src/main/java/io/opencensus/contrib/zpages/TracezZPageHandler.java
  exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtils.java
  exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverExporterWorkerTest.java
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporterHandler.java
  exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandler.java
  impl/src/main/java/io/opencensus/impl/internal/DisruptorEventQueue.java
  impl_core/src/main/java/io/opencensus/implcore/internal/CurrentState.java
  impl_core/src/main/java/io/opencensus/implcore/trace/export/ExportComponentImpl.java
  impl_core/src/test/java/io/opencensus/implcore/stats/MetricUtilsTest.java
  impl_core/src/test/java/io/opencensus/implcore/stats/StatsTestUtil.java
Labels: cla: yes, static analysis

#1553 Helper utility for Http Tracing.
  api/src/main/java/io/opencensus/trace/Status.java
  contrib/http_util/src/main/java/io/opencensus/contrib/http/util/HttpTraceUtil.java
  contrib/http_util/src/test/java/io/opencensus/contrib/http/util/HttpTraceUtilTest.java
Labels: cla: yes

#1554 Avoid one extra allocation in TraceId and SpanId.
  api/src/main/java/io/opencensus/trace/BigendianEncoding.java
  api/src/main/java/io/opencensus/trace/SpanId.java
  api/src/main/java/io/opencensus/trace/TraceId.java
  api/src/test/java/io/opencensus/trace/BigendianEncodingTest.java
Labels: cla: yes

#1556 Add a common Http Handler for Http Client and Http Server.
  buildscripts/import-control.xml
  contrib/http_util/src/main/java/io/opencensus/contrib/http/AbstractHttpHandler.java
  contrib/http_util/src/main/java/io/opencensus/contrib/http/HttpExtractor.java
  contrib/http_util/src/test/java/io/opencensus/contrib/http/AbstractHttpHandlerTest.java
Labels: cla: yes

#1557 Update release version for Bazel build files.
  examples/opencensus_workspace.bzl
Labels: cla: yes

#1559 Build: Update oc-proto version.
  build.gradle
Labels: build, cla: yes

#1560 Exporter/Trace/OcAgent: Update versions.
  build.gradle
  exporters/trace/ocagent/README.md
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporter.java
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporterConfiguration.java
Labels: cla: yes, documentation

#1511 Add Gauges APIs examples
  buildscripts/import-control.xml
  examples/BUILD.bazel
  examples/build.gradle
  examples/pom.xml
  examples/src/main/java/io/opencensus/examples/gauges/DerivedDoubleGaugeQuickstart.java
  examples/src/main/java/io/opencensus/examples/gauges/DerivedLongGaugeQuickstart.java
  examples/src/main/java/io/opencensus/examples/gauges/DoubleGaugeQuickstart.java
  examples/src/main/java/io/opencensus/examples/gauges/LongGaugeQuickstart.java
Labels: cla: yes, examples, metrics

#1562 Style: Fix typos.
  api/src/test/java/io/opencensus/internal/UtilsTest.java
  contrib/http_util/src/main/java/io/opencensus/contrib/http/util/HttpTraceUtil.java
Labels: cla: yes, enhancement

#1564 Add @return and remove already done TODO
  api/src/main/java/io/opencensus/metrics/MetricRegistry.java
  api/src/test/java/io/opencensus/metrics/DerivedDoubleGaugeTest.java
  api/src/test/java/io/opencensus/metrics/DerivedLongGaugeTest.java
  api/src/test/java/io/opencensus/metrics/DoubleGaugeTest.java
  api/src/test/java/io/opencensus/metrics/LongGaugeTest.java
Labels: cla: yes

#1561 Add support to convert longs to base16-string.
  api/src/main/java/io/opencensus/trace/BigendianEncoding.java
  api/src/main/java/io/opencensus/trace/LowerCaseBase16Encoding.java
  api/src/main/java/io/opencensus/trace/SpanId.java
  api/src/main/java/io/opencensus/trace/TraceId.java
  api/src/test/java/io/opencensus/trace/BigendianEncodingTest.java
  api/src/test/java/io/opencensus/trace/LowerCaseBase16EncodingTest.java
Labels: cla: yes

#1558 Add support for generic http client handler.
  contrib/http_util/src/main/java/io/opencensus/contrib/http/AbstractHttpHandler.java
  contrib/http_util/src/main/java/io/opencensus/contrib/http/HttpClientHandler.java
  contrib/http_util/src/main/java/io/opencensus/contrib/http/util/HttpTraceAttributeConstants.java
  contrib/http_util/src/test/java/io/opencensus/contrib/http/AbstractHttpHandlerTest.java
  contrib/http_util/src/test/java/io/opencensus/contrib/http/HttpClientHandlerTest.java
  contrib/http_util/src/test/java/io/opencensus/contrib/http/util/testing/FakeSpan.java
Labels: cla: yes

#1568 Add support generic http server handler.
  contrib/http_util/src/main/java/io/opencensus/contrib/http/HttpServerHandler.java
  contrib/http_util/src/test/java/io/opencensus/contrib/http/HttpServerHandlerTest.java
Labels: cla: yes

#1571 Exporter/Jaeger: Fix an annotation.
  exporters/trace/jaeger/src/main/java/io/opencensus/exporter/trace/jaeger/JaegerExporterHandler.java
Labels: build, cla: yes

#1569 Build: Exclude oc-agent-exporter from nullness checker.
  build.gradle
Labels: build, cla: yes, exporters

#1570 Exporter/OcAgent: Add export RPC handler.
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceServiceExportRpcHandler.java
Labels: cla: yes, exporters, tracing

#1572 Exporter/OcAgent: Add config RPC handler.
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceServiceConfigRpcHandler.java
Labels: cla: yes, exporters, tracing

#1577 Add Trace config options and extractor for Http Servlets.
  all/build.gradle
  build.gradle
  buildscripts/import-control.xml
  contrib/http_servlet/README.md
  contrib/http_servlet/build.gradle
  contrib/http_servlet/src/main/java/io/opencensus/contrib/http/servlet/OcHttpServletExtractor.java
  contrib/http_servlet/src/test/java/io/opencensus/contrib/http/servlet/OcHttpServletExtractorTest.java
  settings.gradle
Labels: cla: yes

#1581 Exporter/OcAgent: Use dedicated Resource proto instead of string map.
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentNodeUtils.java
  exporters/trace/ocagent/src/test/java/io/opencensus/exporter/trace/ocagent/OcAgentNodeUtilsTest.java
Labels: cla: yes, enhancement, exporters, tracing

#1582 Add extractor for Jetty Client.
  all/build.gradle
  build.gradle
  buildscripts/import-control.xml
  contrib/http_jetty_client/README.md
  contrib/http_jetty_client/build.gradle
  contrib/http_jetty_client/src/main/java/io/opencensus/contrib/http/jetty/client/OcJettyHttpClientExtractor.java
  contrib/http_jetty_client/src/test/java/io/opencensus/contrib/http/jetty/client/OcJettyHttpClientExtractorTest.java
  settings.gradle
Labels: cla: yes

#1518 Exporter/Stats/Stackdriver: Add user agent as client header.
  exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsExporter.java
  exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsExporterTest.java
Labels: DO NOT MERGE, cla: yes, exporters, stats

#1565 Resource: Add resource detector
  api/src/main/java/io/opencensus/resource/Resource.java
  api/src/test/java/io/opencensus/resource/ResourceTest.java
Labels: API, cla: yes, resource

#1587 Use the nullable annotation when possible.
  api/src/main/java/io/opencensus/resource/Resource.java
Labels: cla: yes

#1589 Deprecate registration of the span names for zpages.
  api/src/main/java/io/opencensus/trace/EndSpanOptions.java
  api/src/main/java/io/opencensus/trace/export/SampledSpanStore.java
  contrib/zpages/src/main/java/io/opencensus/contrib/zpages/ZPageHttpHandler.java
  exporters/stats/prometheus/src/main/java/io/opencensus/exporter/stats/prometheus/PrometheusStatsCollector.java
  exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExporterWorker.java
  exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandler.java
  impl_core/src/main/java/io/opencensus/implcore/trace/export/InProcessSampledSpanStoreImpl.java
  impl_core/src/main/java/io/opencensus/implcore/trace/export/SampledSpanStoreImpl.java
Labels: cla: yes

#1592 Exporter/OcAgent/Test: Make fake agent thread-safe.
  exporters/trace/ocagent/src/test/java/io/opencensus/exporter/trace/ocagent/FakeOcAgentTraceServiceGrpcImpl.java
Labels: cla: yes, enhancement, tests

#1585 Exporter/Stats/Stackdriver: Use core resource API
  api/src/main/java/io/opencensus/resource/Resource.java
  buildscripts/import-control.xml
  contrib/monitored_resource_util/build.gradle
  contrib/monitored_resource_util/src/main/java/io/opencensus/contrib/monitoredresource/util/MonitoredResource.java
  contrib/monitored_resource_util/src/main/java/io/opencensus/contrib/monitoredresource/util/MonitoredResourceUtils.java
  contrib/monitored_resource_util/src/main/java/io/opencensus/contrib/monitoredresource/util/ResourceKeyConstants.java
  contrib/monitored_resource_util/src/test/java/io/opencensus/contrib/monitoredresource/util/MonitoredResourceUtilsTest.java
  exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtils.java
  exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtilsTest.java
  exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandler.java
Labels: cla: yes, exporters, resource

#1594 Add helper functions for base16 encoding.
  api/src/main/java/io/opencensus/trace/BigendianEncoding.java
  api/src/main/java/io/opencensus/trace/SpanId.java
  api/src/main/java/io/opencensus/trace/TraceId.java
  api/src/main/java/io/opencensus/trace/TraceOptions.java
  api/src/test/java/io/opencensus/trace/BigendianEncodingTest.java
  api/src/test/java/io/opencensus/trace/SpanIdTest.java
  api/src/test/java/io/opencensus/trace/TraceIdTest.java
  api/src/test/java/io/opencensus/trace/TraceOptionsTest.java
Labels: cla: yes

#1401 Add support for trace-context propagation.
  CHANGELOG.md
  api/src/main/java/io/opencensus/trace/propagation/PropagationComponent.java
  api/src/test/java/io/opencensus/trace/propagation/PropagationComponentTest.java
  impl_core/src/jmh/java/io/opencensus/implcore/trace/propagation/TraceContextImplBenchmark.java
  impl_core/src/main/java/io/opencensus/implcore/trace/propagation/PropagationComponentImpl.java
  impl_core/src/main/java/io/opencensus/implcore/trace/propagation/TraceContextFormat.java
  impl_core/src/test/java/io/opencensus/implcore/trace/propagation/PropagationComponentImplTest.java
  impl_core/src/test/java/io/opencensus/implcore/trace/propagation/TraceContextFormatTest.java
Labels: API, cla: yes, tracing

#1596 Exporter/OcAgent: Use core resource API.
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentNodeUtils.java
  exporters/trace/ocagent/src/test/java/io/opencensus/exporter/trace/ocagent/OcAgentNodeUtilsTest.java
Labels: cla: yes, exporters, tracing

#1361 Fix jaeger integration tests.
  exporters/trace/jaeger/src/test/java/io/opencensus/exporter/trace/jaeger/JaegerExporterHandlerIntegrationTest.java
Labels: cla: yes

#1597 Add changelog entries for http insturmentations.
  CHANGELOG.md
Labels: cla: yes

#1598 Use java8 for osx builds.
  .travis.yml
Labels: build, cla: yes, continuous integration

#1563 gRPC metrics: Add measures and views for real-time metrics in streaming RPCs.
  CHANGELOG.md
  contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcMeasureConstants.java
  contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcViewConstants.java
  contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcViews.java
  contrib/grpc_metrics/src/test/java/io/opencensus/contrib/grpc/metrics/RpcMeasureConstantsTest.java
  contrib/grpc_metrics/src/test/java/io/opencensus/contrib/grpc/metrics/RpcViewConstantsTest.java
  contrib/grpc_metrics/src/test/java/io/opencensus/contrib/grpc/metrics/RpcViewsTest.java
Labels: cla: yes, gRPC

#1586 Add Jetty http client wrapper for tracing.
  contrib/http_jetty_client/src/main/java/io/opencensus/contrib/http/jetty/client/HttpRequestListener.java
  contrib/http_jetty_client/src/main/java/io/opencensus/contrib/http/jetty/client/OcJettyHttpClient.java
  contrib/http_jetty_client/src/test/java/io/opencensus/contrib/http/jetty/client/HttpRequestListenerTest.java
  contrib/http_jetty_client/src/test/java/io/opencensus/contrib/http/jetty/client/OcJettyHttpClientTest.java
  contrib/http_util/src/main/java/io/opencensus/contrib/http/HttpClientHandler.java
Labels: cla: yes

#1573 Exporter/OcAgent: Add unit tests for RPC handlers.
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceServiceConfigRpcHandler.java
  exporters/trace/ocagent/src/test/java/io/opencensus/exporter/trace/ocagent/FakeOcAgentTraceServiceGrpcImpl.java
  exporters/trace/ocagent/src/test/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceServiceRpcHandlersTest.java
Labels: cla: yes, exporters, tests, tracing

#1579 Build: Exclude OC-Agent exporter from this release for now.
  build.gradle
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporter.java
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporterConfiguration.java
Labels: build, cla: yes

#1602 Exclude http-jetty-client and http-servlet artifact from release 0.18
  build.gradle
  contrib/http_jetty_client/README.md
  contrib/http_jetty_client/build.gradle
Labels: cla: yes

#1608 Exclude http instrumentation api from 0.18 release.
  all/build.gradle
  contrib/http_util/src/main/java/io/opencensus/contrib/http/AbstractHttpHandler.java
  contrib/http_util/src/main/java/io/opencensus/contrib/http/HttpClientHandler.java
  contrib/http_util/src/main/java/io/opencensus/contrib/http/HttpServerHandler.java
  settings.gradle
Labels: cla: yes

#1611 Set the right unit for dropwizard timer metrics.
  contrib/dropwizard/src/main/java/io/opencensus/contrib/dropwizard/DropWizardMetrics.java
  contrib/dropwizard/src/test/java/io/opencensus/contrib/dropwizard/DropWizardMetricsTest.java
Labels: cla: yes

#1609 Fix bug: Dropwizard Meter should have non-null start Timestamp
  contrib/dropwizard/src/main/java/io/opencensus/contrib/dropwizard/DropWizardMetrics.java
  contrib/dropwizard/src/test/java/io/opencensus/contrib/dropwizard/DropWizardMetricsTest.java
Labels: cla: yes

#1591 Exporter/Stats/Stackdriver: handle Summary Type
  exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtils.java
  exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExporterWorker.java
  exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtilsTest.java
Labels: cla: yes, exporters, stats

#1612 Start 0.19.0 development cycle
  api/src/main/java/io/opencensus/common/OpenCensusLibraryInformation.java
  build.gradle
  examples/build.gradle
  examples/pom.xml
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentNodeUtils.java
  exporters/trace/ocagent/src/test/java/io/opencensus/exporter/trace/ocagent/OcAgentNodeUtilsTest.java
Labels: cla: yes

#1614 Release
  api/src/main/java/io/opencensus/common/OpenCensusLibraryInformation.java
  build.gradle
  examples/build.gradle
  examples/pom.xml
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentNodeUtils.java
  exporters/trace/ocagent/src/test/java/io/opencensus/exporter/trace/ocagent/OcAgentNodeUtilsTest.java
Labels: cla: yes

#1613 Don't test constants, especially the version because we automatically update it.
  exporters/trace/ocagent/src/test/java/io/opencensus/exporter/trace/ocagent/OcAgentNodeUtilsTest.java
Labels: cla: yes

#1616 Update CHANGELOG.
  CHANGELOG.md
Labels: cla: yes

#1615 Update release versions for all readme
  README.md
  contrib/appengine_standard_util/README.md
  contrib/exemplar_util/README.md
  contrib/grpc_util/README.md
  contrib/http_util/README.md
  contrib/log_correlation/log4j2/README.md
  contrib/log_correlation/stackdriver/README.md
  contrib/monitored_resource_util/README.md
  contrib/spring/README.md
  contrib/spring_sleuth_v1x/README.md
  contrib/zpages/README.md
  examples/build.gradle
  examples/pom.xml
  exporters/stats/prometheus/README.md
  exporters/stats/signalfx/README.md
  exporters/stats/stackdriver/README.md
  exporters/trace/instana/README.md
  exporters/trace/jaeger/README.md
  exporters/trace/logging/README.md
  exporters/trace/stackdriver/README.md
  exporters/trace/zipkin/README.md
Labels: cla: yes

#1604 update http default view as per the spec. fixes #1603
  contrib/http_util/src/main/java/io/opencensus/contrib/http/util/HttpMeasureConstants.java
  contrib/http_util/src/main/java/io/opencensus/contrib/http/util/HttpViewConstants.java
  contrib/http_util/src/test/java/io/opencensus/contrib/http/util/HttpViewConstantsTest.java
Labels: cla: yes

#1619 Update release versions for all build files.
  examples/opencensus_workspace.bzl
Labels: cla: yes

#1621 Move the travis build scripts and remove java6 installation.
  .travis.yml
  buildscripts/check-git-history.py
  buildscripts/kokoro/linux_presubmit.sh
  buildscripts/travis_script
Labels: cla: yes

#1617 Update dependencies and source/target compatibility.
  .travis.yml
  appveyor.yml
  build.gradle
  buildscripts/travis_script
Labels: cla: yes

#1623 Remove unnecessary usage of CheckerFrameworkUtils.
  impl_core/src/main/java/io/opencensus/implcore/trace/RecordEventsSpanImpl.java
  impl_core/src/main/java/io/opencensus/implcore/trace/internal/ConcurrentIntrusiveList.java
Labels: cla: yes

#1624 Checker Framework: 2.5.6 -> 2.5.7
  build.gradle
Labels: cla: yes, static analysis

#1625 Make our user-agent consistent with other user-agents.
  exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsExporter.java
Labels: cla: yes
