Repository census-instrumentation/opencensus-java, pull requests merged in 2018-04, with the labels that each got.

#1109 Update README based on customers' feedback
  README.md
Labels: cla: yes, documentation, enhancement, examples

#1110 Fix a few typos in exporter README
  exporters/stats/stackdriver/README.md
  exporters/trace/instana/README.md
Labels: cla: yes, documentation, exporters

#1112 Checker Framework: 2.3.2 -> 2.4.0
  build.gradle
Labels: cla: yes, static analysis

#1111 Remove more usages of Guava from opencensus-api (issue #1081).
  api/src/main/java/io/opencensus/common/Duration.java
  api/src/main/java/io/opencensus/common/TimeUtils.java
  api/src/main/java/io/opencensus/common/Timestamp.java
  api/src/main/java/io/opencensus/internal/DefaultVisibilityForTesting.java
  api/src/main/java/io/opencensus/internal/PublicForTesting.java
  api/src/main/java/io/opencensus/internal/StringUtils.java
  api/src/main/java/io/opencensus/internal/Utils.java
  api/src/main/java/io/opencensus/stats/Aggregation.java
  api/src/main/java/io/opencensus/stats/AggregationData.java
  api/src/main/java/io/opencensus/stats/BucketBoundaries.java
  api/src/main/java/io/opencensus/stats/Measure.java
  api/src/main/java/io/opencensus/stats/NoopStats.java
  api/src/main/java/io/opencensus/stats/Stats.java
  api/src/main/java/io/opencensus/stats/View.java
  api/src/main/java/io/opencensus/stats/ViewData.java
  api/src/main/java/io/opencensus/tags/NoopTags.java
  api/src/main/java/io/opencensus/tags/TagKey.java
  api/src/main/java/io/opencensus/tags/TagValue.java
  api/src/main/java/io/opencensus/tags/Tags.java
  api/src/main/java/io/opencensus/trace/Annotation.java
  api/src/main/java/io/opencensus/trace/AttributeValue.java
  api/src/main/java/io/opencensus/trace/CurrentSpanUtils.java
  api/src/main/java/io/opencensus/trace/MessageEvent.java
  api/src/main/java/io/opencensus/trace/NetworkEvent.java
  api/src/main/java/io/opencensus/trace/Span.java
  api/src/main/java/io/opencensus/trace/SpanBuilder.java
  api/src/main/java/io/opencensus/trace/SpanContext.java
  api/src/main/java/io/opencensus/trace/SpanId.java
  api/src/main/java/io/opencensus/trace/Status.java
  api/src/main/java/io/opencensus/trace/TraceId.java
  api/src/main/java/io/opencensus/trace/TraceOptions.java
  api/src/main/java/io/opencensus/trace/Tracer.java
  api/src/main/java/io/opencensus/trace/Tracing.java
  api/src/main/java/io/opencensus/trace/config/TraceParams.java
  api/src/main/java/io/opencensus/trace/export/RunningSpanStore.java
  api/src/main/java/io/opencensus/trace/export/SampledSpanStore.java
  api/src/main/java/io/opencensus/trace/export/SpanData.java
  api/src/main/java/io/opencensus/trace/internal/BaseMessageEventUtils.java
  api/src/main/java/io/opencensus/trace/propagation/BinaryFormat.java
  api/src/main/java/io/opencensus/trace/propagation/TextFormat.java
  api/src/main/java/io/opencensus/trace/samplers/ProbabilitySampler.java
  api/src/test/java/io/opencensus/internal/StringUtilsTest.java
  api/src/test/java/io/opencensus/internal/UtilsTest.java
  api/src/test/java/io/opencensus/trace/internal/BaseMessageEventUtilsTest.java
  checker-framework/stubs/guava.astub
  contrib/http_util/src/main/java/io/opencensus/contrib/http/util/CloudTraceFormat.java
  findbugs-exclude.xml
  impl_core/src/main/java/io/opencensus/implcore/trace/propagation/B3Format.java
Labels: build, cla: yes, refactoring

#1060 Add utility class to expose default HTTP measures, tags and view, and register default views.
  contrib/http_util/src/main/java/io/opencensus/contrib/http/util/HttpMeasureConstants.java
  contrib/http_util/src/main/java/io/opencensus/contrib/http/util/HttpViewConstants.java
  contrib/http_util/src/main/java/io/opencensus/contrib/http/util/HttpViews.java
  contrib/http_util/src/test/java/io/opencensus/contrib/http/util/HttpMeasureConstantsTest.java
  contrib/http_util/src/test/java/io/opencensus/contrib/http/util/HttpViewConstantsTest.java
  contrib/http_util/src/test/java/io/opencensus/contrib/http/util/HttpViewsTest.java
Labels: cla: yes, stats

#1115 Add new RPC measure and view constants, deprecate old ones.
  contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcMeasureConstants.java
  contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcViewConstants.java
  contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcViews.java
  contrib/grpc_metrics/src/test/java/io/opencensus/contrib/grpc/metrics/RpcMeasureConstantsTest.java
  contrib/grpc_metrics/src/test/java/io/opencensus/contrib/grpc/metrics/RpcViewConstantsTest.java
  contrib/grpc_metrics/src/test/java/io/opencensus/contrib/grpc/metrics/RpcViewsTest.java
Labels: cla: yes, gRPC, stats

#1118 Fix issues in RPC constants
  contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcMeasureConstants.java
  contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcViewConstants.java
  contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcViews.java
  contrib/grpc_metrics/src/test/java/io/opencensus/contrib/grpc/metrics/RpcMeasureConstantsTest.java
Labels: cla: yes, gRPC, stats

#1119 Clarifies implementation details on BinaryFormat
  api/src/main/java/io/opencensus/trace/propagation/BinaryFormat.java
Labels: cla: yes

#1121 Bumps to latest gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: cla: yes

#1122 This fixes the Jaeger integration test and generally cleans it up
  exporters/trace/jaeger/build.gradle
  exporters/trace/jaeger/src/test/java/io/opencensus/exporter/trace/jaeger/JaegerExporterHandlerIntegrationTest.java
  exporters/trace/jaeger/src/test/java/io/opencensus/exporter/trace/jaeger/JaegerExporterHandlerTest.java
Labels: cla: yes

#1120 Makes the trace and span ID fields mandatory in binary format
  impl_core/src/main/java/io/opencensus/implcore/trace/propagation/BinaryFormatImpl.java
  impl_core/src/test/java/io/opencensus/implcore/trace/propagation/BinaryFormatImplTest.java
Labels: cla: yes

#1127 Substitute non-ascii characters in B3Format header key. (#1072)
  impl_core/src/main/java/io/opencensus/implcore/trace/propagation/B3Format.java
Labels: cla: yes, release

#1128 Release
  api/src/main/java/io/opencensus/common/OpenCensusLibraryInformation.java
  build.gradle
  examples/build.gradle
  examples/pom.xml
Labels: cla: yes, release

#1129 Update release versions for all readme and build files.
  README.md
  contrib/grpc_util/README.md
  contrib/http_util/README.md
  contrib/zpages/README.md
  examples/build.gradle
  examples/pom.xml
  exporters/stats/prometheus/README.md
  exporters/stats/signalfx/README.md
  exporters/stats/stackdriver/README.md
  exporters/trace/instana/README.md
  exporters/trace/jaeger/README.md
  exporters/trace/logging/README.md
  exporters/trace/stackdriver/README.md
  exporters/trace/zipkin/README.md
Labels: cla: yes, documentation, release

#1114 Move toMillis(Duration) to Utils so that it can be reused.
  api/src/main/java/io/opencensus/common/Duration.java
  api/src/test/java/io/opencensus/common/DurationTest.java
  exporters/stats/signalfx/src/main/java/io/opencensus/exporter/stats/signalfx/SignalFxStatsExporterWorkerThread.java
  exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExporterWorker.java
  impl_core/src/main/java/io/opencensus/implcore/stats/IntervalBucket.java
  impl_core/src/main/java/io/opencensus/implcore/stats/MutableViewData.java
  impl_core/src/main/java/io/opencensus/implcore/trace/export/SpanExporterImpl.java
  impl_core/src/test/java/io/opencensus/implcore/stats/MutableViewDataTest.java
Labels: cla: yes, enhancement

#1132 Improve Duration.toMillis()
  api/src/main/java/io/opencensus/common/Duration.java
  api/src/test/java/io/opencensus/common/DurationTest.java
  exporters/stats/signalfx/src/main/java/io/opencensus/exporter/stats/signalfx/SignalFxStatsExporterWorkerThread.java
  exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExporterWorker.java
  impl_core/src/main/java/io/opencensus/implcore/stats/IntervalBucket.java
  impl_core/src/main/java/io/opencensus/implcore/stats/MutableViewData.java
  impl_core/src/main/java/io/opencensus/implcore/trace/export/SpanExporterImpl.java
Labels: cla: yes, common, documentation, enhancement

#1134 Remove java doc about overflow cases in Duration.toMillis().
  api/src/main/java/io/opencensus/common/Duration.java
Labels: cla: yes, common, documentation

#1137 Control package dependencies with Checkstyle.
  CONTRIBUTING.md
  api/src/main/java/io/opencensus/common/Duration.java
  api/src/main/java/io/opencensus/common/TimeUtils.java
  api/src/main/java/io/opencensus/common/Timestamp.java
  api/src/main/java/io/opencensus/internal/Utils.java
  api/src/test/java/io/opencensus/common/TimeUtilsTest.java
  api/src/test/java/io/opencensus/internal/UtilsTest.java
  buildscripts/checkstyle.xml
  buildscripts/import-control.xml
  impl_core/src/main/java/io/opencensus/implcore/trace/propagation/BinaryFormatImpl.java
Labels: build, cla: yes, static analysis

#1139 Add a Markdown changelog, starting at version 0.9.0 (closes #945).
  CHANGELOG.md
  CONTRIBUTING.md
Labels: cla: yes, documentation, release

#1140 Update the MonitoredResource section in SD readme
  exporters/stats/stackdriver/README.md
Labels: cla: yes, documentation, exporters

#1150 #785 - Check for null status/annotations/etc in Span
  api/src/main/java/io/opencensus/trace/BlankSpan.java
  api/src/main/java/io/opencensus/trace/Span.java
  api/src/test/java/io/opencensus/trace/NoopSpan.java
  impl_core/src/main/java/io/opencensus/implcore/trace/SpanImpl.java
Labels: cla: yes, tracing

#1135 Move monitored resource detection utils to a separate artifact.
  all/build.gradle
  build.gradle
  buildscripts/import-control.xml
  contrib/monitored_resource_util/README.md
  contrib/monitored_resource_util/build.gradle
  contrib/monitored_resource_util/src/main/java/io/opencensus/contrib/monitoredresource/util/AwsIdentityDocUtils.java
  contrib/monitored_resource_util/src/main/java/io/opencensus/contrib/monitoredresource/util/GcpMetadataConfig.java
  contrib/monitored_resource_util/src/main/java/io/opencensus/contrib/monitoredresource/util/MonitoredResource.java
  contrib/monitored_resource_util/src/main/java/io/opencensus/contrib/monitoredresource/util/MonitoredResourceUtils.java
  contrib/monitored_resource_util/src/main/java/io/opencensus/contrib/monitoredresource/util/ResourceType.java
  contrib/monitored_resource_util/src/test/java/io/opencensus/contrib/monitoredresource/util/AwsIdentityDocUtilsTest.java
  contrib/monitored_resource_util/src/test/java/io/opencensus/contrib/monitoredresource/util/MonitoredResourceUtilsTest.java
  exporters/stats/stackdriver/build.gradle
  exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtils.java
  exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtilsTest.java
  settings.gradle
Labels: cla: yes, exporters, stats

#1151 Update changelog.
  CHANGELOG.md
Labels: cla: yes, documentation

#1155 Check for null in more public methods in Span and its subclasses.
  api/src/main/java/io/opencensus/trace/BlankSpan.java
  api/src/test/java/io/opencensus/trace/NoopSpan.java
  impl_core/src/main/java/io/opencensus/implcore/trace/SpanImpl.java
Labels: cla: yes, tracing

#1156 Rename StatsRunner to TagContextExample because it's more about TagContext.
  examples/BUILD.bazel
  examples/README.md
  examples/build.gradle
  examples/pom.xml
  examples/src/main/java/io/opencensus/examples/tags/TagContextExample.java
Labels: cla: yes, examples

#1055 Add Aggregation.LastValue and AggregationData.LastValueData to support Gauge
  api/src/main/java/io/opencensus/stats/Aggregation.java
  api/src/main/java/io/opencensus/stats/AggregationData.java
  api/src/main/java/io/opencensus/stats/ViewData.java
  api/src/test/java/io/opencensus/stats/AggregationDataTest.java
  api/src/test/java/io/opencensus/stats/AggregationTest.java
  api/src/test/java/io/opencensus/stats/ViewDataTest.java
  contrib/zpages/src/main/java/io/opencensus/contrib/zpages/StatszZPageHandler.java
  contrib/zpages/src/test/java/io/opencensus/contrib/zpages/StatszZPageHandlerTest.java
  exporters/stats/prometheus/src/main/java/io/opencensus/exporter/stats/prometheus/PrometheusExportUtils.java
  exporters/stats/prometheus/src/test/java/io/opencensus/exporter/stats/prometheus/PrometheusExportUtilsTest.java
  exporters/stats/signalfx/src/main/java/io/opencensus/exporter/stats/signalfx/SignalFxSessionAdaptor.java
  exporters/stats/signalfx/src/test/java/io/opencensus/exporter/stats/signalfx/SignalFxSessionAdaptorTest.java
  exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtils.java
  exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtilsTest.java
  impl_core/src/main/java/io/opencensus/implcore/stats/MutableAggregation.java
  impl_core/src/main/java/io/opencensus/implcore/stats/MutableViewData.java
  impl_core/src/test/java/io/opencensus/implcore/stats/MutableAggregationTest.java
  impl_core/src/test/java/io/opencensus/implcore/stats/MutableViewDataTest.java
  impl_core/src/test/java/io/opencensus/implcore/stats/StatsTestUtil.java
  impl_core/src/test/java/io/opencensus/implcore/stats/ViewManagerImplTest.java
Labels: API, cla: yes, stats

#1159 Update RELEASING.md that changes can be found from CHANGELOG.md.
  RELEASING.md
Labels: cla: yes, documentation, release

#1161 Update CHANGELOG.md for v0.13.0 release.
  CHANGELOG.md
Labels: cla: yes, release

#1157 Start 0.14.0 development cycle
  api/src/main/java/io/opencensus/common/OpenCensusLibraryInformation.java
  build.gradle
  examples/build.gradle
  examples/pom.xml
Labels: cla: yes, release

#1160 Update release versions for readme and build files.
  README.md
  contrib/grpc_util/README.md
  contrib/http_util/README.md
  contrib/zpages/README.md
  examples/build.gradle
  examples/pom.xml
  exporters/stats/prometheus/README.md
  exporters/stats/signalfx/README.md
  exporters/stats/stackdriver/README.md
  exporters/trace/instana/README.md
  exporters/trace/jaeger/README.md
  exporters/trace/logging/README.md
  exporters/trace/stackdriver/README.md
  exporters/trace/zipkin/README.md
Labels: cla: yes, documentation, not ready for merge, release

#1158 Release
  api/src/main/java/io/opencensus/common/OpenCensusLibraryInformation.java
  build.gradle
  examples/build.gradle
  examples/pom.xml
Labels: cla: yes, release

#1165 Update CHANGELOG.md for v0.13.0 release. (#1161)
  CHANGELOG.md
Labels: cla: yes, documentation, release

#1166 Update release versions for Bazel BUILD.
  examples/WORKSPACE
  examples/opencensus_workspace.bzl
Labels: cla: yes, release
