Repository census-instrumentation/opencensus-java, pull requests merged in 2018-03, with the labels that each got.

#1037 Fix a typo in Zipkin exporter README
  exporters/trace/zipkin/README.md
Labels: cla: yes, documentation

#1038 Small update in Zipkin exporter README
  exporters/trace/zipkin/README.md
Labels: cla: yes, documentation

#1040 Fix probabilitySampler_getDescription for all locales.
  api/src/test/java/io/opencensus/trace/samplers/SamplersTest.java
Labels: cla: yes

#1039 Add a QuickStart example.
  examples/BUILD.bazel
  examples/build.gradle
  examples/pom.xml
  examples/src/main/java/io/opencensus/examples/helloworld/QuickStart.java
Labels: cla: yes, examples, stats, tags, tracing

#1034 Fixes copy/paste errors
  exporters/trace/zipkin/src/main/java/io/opencensus/exporter/trace/zipkin/ZipkinExporterHandler.java
Labels: cla: yes

#1042 Update example README to include QuickStart
  examples/README.md
Labels: cla: yes, documentation, examples

#1043 Update QuickStart to improve readability.
  examples/src/main/java/io/opencensus/examples/helloworld/QuickStart.java
Labels: cla: yes, documentation, enhancement, examples

#1045 Prefer non-deprecated classes.
  examples/src/main/java/io/opencensus/examples/trace/MultiSpansContextTracing.java
  examples/src/main/java/io/opencensus/examples/trace/MultiSpansScopedTracing.java
  examples/src/main/java/io/opencensus/examples/trace/MultiSpansTracing.java
Labels: cla: yes

#1046 Don't declare any dependencies in the generated POM because the agent JAR is self-contained.
  contrib/agent/build.gradle
Labels: agent, build, cla: yes

#1048 Update Byte Buddy to 1.7.11 (was 1.7.10).
  build.gradle
Labels: cla: yes

#1049 Update ZPagesTester section in examples README
  examples/README.md
Labels: cla: yes, documentation, examples

#1051 Dependency update
  build.gradle
Labels: cla: yes

#1053 Add quick start example to README
  README.md
Labels: cla: yes, documentation, examples

#1018 Deprecate Window and WindowData.
  api/src/main/java/io/opencensus/stats/NoopStats.java
  api/src/main/java/io/opencensus/stats/View.java
  api/src/main/java/io/opencensus/stats/ViewData.java
  api/src/test/java/io/opencensus/stats/NoopViewManagerTest.java
  contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcViewConstants.java
  contrib/zpages/src/main/java/io/opencensus/contrib/zpages/RpczZPageHandler.java
  contrib/zpages/src/main/java/io/opencensus/contrib/zpages/StatszZPageHandler.java
  contrib/zpages/src/main/java/io/opencensus/contrib/zpages/ZPageHandlers.java
  exporters/stats/prometheus/src/main/java/io/opencensus/exporter/stats/prometheus/PrometheusExportUtils.java
  exporters/stats/signalfx/src/main/java/io/opencensus/exporter/stats/signalfx/SignalFxSessionAdaptor.java
  exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtils.java
  impl_core/src/main/java/io/opencensus/implcore/stats/MeasureToViewMap.java
  impl_core/src/main/java/io/opencensus/implcore/stats/MutableViewData.java
Labels: API, cla: yes, stats

#1056 Add a PrometheusStatsConfiguration class.
  exporters/stats/prometheus/build.gradle
  exporters/stats/prometheus/src/main/java/io/opencensus/exporter/stats/prometheus/PrometheusStatsCollector.java
  exporters/stats/prometheus/src/main/java/io/opencensus/exporter/stats/prometheus/PrometheusStatsConfiguration.java
Labels: API, cla: yes, enhancement, exporters

#1041 Fix build on platforms that are not supported by netty-tcnative.
  build.gradle
Labels: build, cla: yes

#1059 Make "./gradlew goJF" work in examples/.
  examples/build.gradle
  examples/src/main/java/io/opencensus/examples/helloworld/QuickStart.java
Labels: cla: yes

#1058 Change MBy to By units.
  README.md
  examples/src/main/java/io/opencensus/examples/helloworld/QuickStart.java
Labels: cla: yes

#1062 Move Travis jobs for example projects to the end of the build matrix.
  .travis.yml
Labels: cla: yes, continuous integration

#1061 Improve StatszZPageHandler.TreeNode
  contrib/zpages/src/main/java/io/opencensus/contrib/zpages/StatszZPageHandler.java
Labels: cla: yes, enhancement, zpages

#1023 Add traces exporter to Jaeger
  .gitignore
  all/build.gradle
  build.gradle
  exporters/trace/jaeger/README.md
  exporters/trace/jaeger/build.gradle
  exporters/trace/jaeger/src/main/java/io/opencensus/exporter/trace/jaeger/JaegerExporterHandler.java
  exporters/trace/jaeger/src/main/java/io/opencensus/exporter/trace/jaeger/JaegerTraceExporter.java
  exporters/trace/jaeger/src/test/java/io/opencensus/exporter/trace/jaeger/JaegerExporterHandlerIntegrationTest.java
  exporters/trace/jaeger/src/test/java/io/opencensus/exporter/trace/jaeger/JaegerExporterHandlerTest.java
  exporters/trace/jaeger/src/test/java/io/opencensus/exporter/trace/jaeger/JaegerTraceExporterTest.java
  settings.gradle
Labels: cla: yes, exporters, tracing

#1063 Fix a failing test with Jaeger exporter
  exporters/trace/jaeger/src/test/java/io/opencensus/exporter/trace/jaeger/JaegerExporterHandlerIntegrationTest.java
Labels: bug, cla: yes, exporters

#1064 Update README, RELEASING and all/build.gradle
  README.md
  RELEASING.md
  all/build.gradle
Labels: cla: yes, documentation

#1065 Add screenshots examples for zpages in the readme.md.
  contrib/zpages/README.md
  contrib/zpages/screenshots/rpcz-example.png
  contrib/zpages/screenshots/statsz-example-1.png
  contrib/zpages/screenshots/statsz-example-2.png
  contrib/zpages/screenshots/traceconfigz-example.png
  contrib/zpages/screenshots/tracez-example.png
Labels: cla: yes, documentation, zpages

#1044 Add a gRPC Hello World example.
  examples/BUILD.bazel
  examples/README.md
  examples/build.gradle
  examples/pom.xml
  examples/src/main/java/io/opencensus/examples/grpc/helloworld/HelloWorldClient.java
  examples/src/main/java/io/opencensus/examples/grpc/helloworld/HelloWorldServer.java
  examples/src/main/java/io/opencensus/examples/grpc/helloworld/HelloWorldUtils.java
  examples/src/main/proto/helloworld.proto
Labels: cla: yes, documentation, examples, gRPC

#1069 Remove usages of guava collections in api/
  api/src/main/java/io/opencensus/stats/AggregationData.java
  api/src/main/java/io/opencensus/stats/NoopStats.java
  api/src/main/java/io/opencensus/stats/ViewData.java
  api/src/main/java/io/opencensus/tags/TagContext.java
  api/src/main/java/io/opencensus/trace/export/SampledSpanStore.java
  api/src/main/java/io/opencensus/trace/export/SpanData.java
Labels: cla: yes

#1070 Fix comment about bucket boundaries in the helloworld example.
  examples/src/main/java/io/opencensus/examples/helloworld/QuickStart.java
Labels: cla: yes

#1072 Substitute non-ascii characters in B3Format header key.
  impl_core/src/main/java/io/opencensus/implcore/trace/propagation/B3Format.java
Labels: cla: yes

#1073 Simplify example Gradle build file by moving license and format checks to the Travis script.
  .travis.yml
  examples/build.gradle
  scripts/travis_script
Labels: cla: yes, continuous integration, examples

#1075 Update disruptor to latest version.
  build.gradle
Labels: cla: yes

#1076 Move BaseMessageEventUtil to trace package.
  api/src/main/java/io/opencensus/trace/Span.java
  api/src/main/java/io/opencensus/trace/export/SpanData.java
  api/src/main/java/io/opencensus/trace/internal/BaseMessageEventUtil.java
  api/src/test/java/io/opencensus/trace/internal/BaseMessageEventUtilTest.java
  findbugs-exclude.xml
Labels: API, build, cla: yes, tracing

#1078 Jaeger exporter test is now more robust to small IDs.
  exporters/trace/jaeger/src/test/java/io/opencensus/exporter/trace/jaeger/JaegerExporterHandlerIntegrationTest.java
Labels: cla: yes

#1077 Run docker -v to find whether Jaeger integration test can be performed.
  exporters/trace/jaeger/src/test/java/io/opencensus/exporter/trace/jaeger/JaegerExporterHandlerIntegrationTest.java
Labels: cla: yes

#1083 Run docker version to find whether Jaeger integration test can be performed.
  exporters/trace/jaeger/src/test/java/io/opencensus/exporter/trace/jaeger/JaegerExporterHandlerIntegrationTest.java
Labels: cla: yes

#1082 Remove an unused local variable
  impl_core/src/test/java/io/opencensus/implcore/trace/export/NoopRunningSpanStoreImplTest.java
Labels: cla: yes

#1084 Run jaegertracing/all-in-one:1.2.0 instead of latest.
  exporters/trace/jaeger/src/test/java/io/opencensus/exporter/trace/jaeger/JaegerExporterHandlerIntegrationTest.java
Labels: cla: yes

#1087 Set unit '1' when the aggregation type is Count.
  exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtils.java
  exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtilsTest.java
Labels: cla: yes

#1086 Enable FindBugs in tests.
  api/src/test/java/io/opencensus/trace/export/NoopSampledSpanStoreTest.java
  build.gradle
  contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcMeasureConstants.java
  contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcViewConstants.java
  contrib/grpc_metrics/src/test/java/io/opencensus/contrib/grpc/metrics/RpcMeasureConstantsTest.java
  contrib/grpc_metrics/src/test/java/io/opencensus/contrib/grpc/metrics/RpcViewConstantsTest.java
  contrib/http_util/src/test/java/io/opencensus/contrib/http/util/CloudTraceFormatTest.java
  exporters/stats/prometheus/src/test/java/io/opencensus/exporter/stats/prometheus/PrometheusStatsCollectorTest.java
  exporters/stats/signalfx/src/test/java/io/opencensus/exporter/stats/signalfx/SignalFxSessionAdaptorTest.java
  exporters/stats/signalfx/src/test/java/io/opencensus/exporter/stats/signalfx/SignalFxStatsExporterWorkerThreadTest.java
  exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverExporterWorkerTest.java
  exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsConfigurationTest.java
  exporters/trace/jaeger/src/test/java/io/opencensus/exporter/trace/jaeger/JaegerExporterHandlerIntegrationTest.java
  exporters/trace/stackdriver/src/test/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandlerExportTest.java
  findbugs-exclude.xml
  impl_core/src/test/java/io/opencensus/implcore/stats/StatsTestUtil.java
  impl_core/src/test/java/io/opencensus/implcore/stats/ViewManagerImplTest.java
  impl_core/src/test/java/io/opencensus/implcore/tags/propagation/TagContextSerializationTest.java
  impl_core/src/test/java/io/opencensus/implcore/trace/SpanImplTest.java
Labels: build, cla: yes

#1089 Fix README.md missing paren
  README.md
Labels: cla: yes

#1092 Simplify README.md
  exporters/stats/stackdriver/README.md
Labels: cla: yes

#1091 Point README at correct link for monitoring API
  exporters/stats/stackdriver/README.md
Labels: cla: yes

#1093 Fix warning-throwing README.md instructions
  README.md
Labels: cla: yes

#1085 More robust integration test for Jaeger exporter.
  exporters/trace/jaeger/src/test/java/io/opencensus/exporter/trace/jaeger/JaegerExporterHandlerIntegrationTest.java
Labels: cla: yes

#1095 Update Guava and Jmh versions
  api/src/main/java/io/opencensus/trace/CurrentSpanUtils.java
  benchmarks/build.gradle
  build.gradle
Labels: bug, build, cla: yes

#1071 Auto detect GCE and GKE Stackdriver MonitoredResources.
  exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtils.java
  exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsExporter.java
  exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtilsTest.java
  exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsExporterTest.java
Labels: cla: yes, enhancement, exporters

#1098 Make Error Prone and FindBugs annotations 'compileOnly' dependencies.
  build.gradle
Labels: build, cla: yes

#1102 Suppress Checker Framework warnings in AutoValue generated classes (fixes #917).
  api/src/main/java/io/opencensus/common/Duration.java
  api/src/main/java/io/opencensus/common/Timestamp.java
  api/src/main/java/io/opencensus/stats/Aggregation.java
  api/src/main/java/io/opencensus/stats/AggregationData.java
  api/src/main/java/io/opencensus/stats/BucketBoundaries.java
  api/src/main/java/io/opencensus/stats/Measure.java
  api/src/main/java/io/opencensus/stats/Measurement.java
  api/src/main/java/io/opencensus/stats/View.java
  api/src/main/java/io/opencensus/stats/ViewData.java
  api/src/main/java/io/opencensus/tags/Tag.java
  api/src/main/java/io/opencensus/tags/TagKey.java
  api/src/main/java/io/opencensus/tags/TagValue.java
  api/src/main/java/io/opencensus/trace/Annotation.java
  api/src/main/java/io/opencensus/trace/AttributeValue.java
  api/src/main/java/io/opencensus/trace/EndSpanOptions.java
  api/src/main/java/io/opencensus/trace/Link.java
  api/src/main/java/io/opencensus/trace/MessageEvent.java
  api/src/main/java/io/opencensus/trace/NetworkEvent.java
  api/src/main/java/io/opencensus/trace/config/TraceParams.java
  api/src/main/java/io/opencensus/trace/export/RunningSpanStore.java
  api/src/main/java/io/opencensus/trace/export/SampledSpanStore.java
  api/src/main/java/io/opencensus/trace/export/SpanData.java
  api/src/main/java/io/opencensus/trace/samplers/ProbabilitySampler.java
  build.gradle
  exporters/stats/prometheus/src/main/java/io/opencensus/exporter/stats/prometheus/PrometheusStatsConfiguration.java
  exporters/stats/signalfx/src/main/java/io/opencensus/exporter/stats/signalfx/SignalFxStatsConfiguration.java
  exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsConfiguration.java
  exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverTraceConfiguration.java
Labels: build, cla: yes

#1101 Deprecate Mean and MeanData
  api/src/main/java/io/opencensus/stats/Aggregation.java
  api/src/main/java/io/opencensus/stats/AggregationData.java
  api/src/main/java/io/opencensus/stats/ViewData.java
  contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcViewConstants.java
  contrib/zpages/src/main/java/io/opencensus/contrib/zpages/RpczZPageHandler.java
  contrib/zpages/src/main/java/io/opencensus/contrib/zpages/StatszZPageHandler.java
  exporters/stats/prometheus/src/main/java/io/opencensus/exporter/stats/prometheus/PrometheusExportUtils.java
  exporters/stats/signalfx/src/main/java/io/opencensus/exporter/stats/signalfx/SignalFxSessionAdaptor.java
  exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtils.java
  impl_core/src/main/java/io/opencensus/implcore/stats/MutableViewData.java
Labels: API, cla: yes, stats

#1106 Turn off Error Prone warning MutableMethodReturnType.
  gradle/errorprone/experimental_warnings
Labels: build, cla: yes

#1107 Update StackdriverStatsExporter README about auto-detecting resources.
  exporters/stats/stackdriver/README.md
Labels: cla: yes, documentation, exporters

#1108 Sort TagKeys in View.create(...) (fixes #1080).
  api/src/main/java/io/opencensus/stats/View.java
  api/src/test/java/io/opencensus/stats/ViewTest.java
Labels: API, cla: yes, stats
