Repository census-instrumentation/opencensus-java, pull requests merged in 2018-02, with the labels that each got.

#972 First proof of concept for Instana integration
  README.md
  RELEASING.md
  build.gradle
  exporters/trace/instana/README.md
  exporters/trace/instana/build.gradle
  exporters/trace/instana/src/main/java/io/opencensus/exporter/trace/instana/InstanaExporterHandler.java
  exporters/trace/instana/src/main/java/io/opencensus/exporter/trace/instana/InstanaTraceExporter.java
  exporters/trace/instana/src/test/java/io/opencensus/exporter/trace/instana/InstanaExporterHandlerTest.java
  exporters/trace/instana/src/test/java/io/opencensus/exporter/trace/instana/InstanaTraceExporterTest.java
  settings.gradle
Labels: cla: yes, exporters, tracing

#990 Add a configuration class to help to create StackdriverTraceExporter. (closes #949)
  exporters/trace/stackdriver/build.gradle
  exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverExporter.java
  exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverTraceConfiguration.java
  exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverTraceExporter.java
  exporters/trace/stackdriver/src/test/java/io/opencensus/exporter/trace/stackdriver/StackdriverTraceConfigurationTest.java
Labels: cla: yes

#991 Add '@since' Javadoc tag to Instana APIs (issue #864).
  exporters/trace/instana/src/main/java/io/opencensus/exporter/trace/instana/InstanaTraceExporter.java
Labels: cla: yes, documentation, exporters, tracing

#978 Add '@since' Javadoc tag to all agent APIs (issue #864).
  contrib/agent/src/main/java/io/opencensus/contrib/agent/AgentMain.java
  contrib/agent/src/main/java/io/opencensus/contrib/agent/Settings.java
  contrib/agent/src/main/java/io/opencensus/contrib/agent/bootstrap/ContextStrategy.java
  contrib/agent/src/main/java/io/opencensus/contrib/agent/bootstrap/ContextTrampoline.java
  contrib/agent/src/main/java/io/opencensus/contrib/agent/bootstrap/TraceStrategy.java
  contrib/agent/src/main/java/io/opencensus/contrib/agent/bootstrap/TraceTrampoline.java
  contrib/agent/src/main/java/io/opencensus/contrib/agent/instrumentation/ContextTrampolineInitializer.java
  contrib/agent/src/main/java/io/opencensus/contrib/agent/instrumentation/ExecutorInstrumentation.java
  contrib/agent/src/main/java/io/opencensus/contrib/agent/instrumentation/Instrumenter.java
  contrib/agent/src/main/java/io/opencensus/contrib/agent/instrumentation/ThreadInstrumentation.java
  contrib/agent/src/main/java/io/opencensus/contrib/agent/instrumentation/TraceTrampolineInitializer.java
  contrib/agent/src/main/java/io/opencensus/contrib/agent/instrumentation/UrlInstrumentation.java
Labels: agent, cla: yes, documentation

#993 Add cumulative views for started and finished RPCs.
  contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcViewConstants.java
  contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcViews.java
  contrib/grpc_metrics/src/test/java/io/opencensus/contrib/grpc/metrics/RpcViewConstantsTest.java
Labels: cla: yes, enhancement, gRPC, stats

#992 Add RpcZ Zpage for stats.
  contrib/zpages/build.gradle
  contrib/zpages/src/main/java/io/opencensus/contrib/zpages/RpczZPageHandler.java
  contrib/zpages/src/main/java/io/opencensus/contrib/zpages/ZPageHandlers.java
  contrib/zpages/src/test/java/io/opencensus/contrib/zpages/RpczZPageHandlerTest.java
  contrib/zpages/src/test/java/io/opencensus/contrib/zpages/ZPageHandlersTest.java
Labels: cla: yes, gRPC, stats, zpages

#965 Implement Prometheus Stats exporter
  RELEASING.md
  all/build.gradle
  build.gradle
  exporters/stats/prometheus/README.md
  exporters/stats/prometheus/build.gradle
  exporters/stats/prometheus/src/main/java/io/opencensus/exporter/stats/prometheus/PrometheusExportUtils.java
  exporters/stats/prometheus/src/main/java/io/opencensus/exporter/stats/prometheus/PrometheusStatsCollector.java
  exporters/stats/prometheus/src/test/java/io/opencensus/exporter/stats/prometheus/PrometheusExportUtilsTest.java
  exporters/stats/prometheus/src/test/java/io/opencensus/exporter/stats/prometheus/PrometheusStatsCollectorTest.java
  settings.gradle
Labels: API, cla: yes, exporters, stats

#997 Instrument the Prometheus Stats Exporter with trace
  exporters/stats/prometheus/src/main/java/io/opencensus/exporter/stats/prometheus/PrometheusStatsCollector.java
Labels: cla: yes, enhancement, exporters, stats

#998 Add Nullable annotation to tag values.
  api/src/main/java/io/opencensus/stats/ViewData.java
  contrib/zpages/src/main/java/io/opencensus/contrib/zpages/RpczZPageHandler.java
  exporters/stats/prometheus/src/main/java/io/opencensus/exporter/stats/prometheus/PrometheusExportUtils.java
  exporters/stats/signalfx/src/main/java/io/opencensus/exporter/stats/signalfx/SignalFxSessionAdaptor.java
  exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtils.java
Labels: API, cla: yes, enhancement, stats

#1001 Change the organization to OpenCensus
  build.gradle
Labels: cla: yes

#1000 Update zipkin-reporter to the latest version 2.3.2.
  build.gradle
  exporters/trace/zipkin/src/main/java/io/opencensus/exporter/trace/zipkin/ZipkinExporterHandler.java
Labels: cla: yes

#894 Add MessageEvent and deprecate NetworkEvent. (closes #858)
  api/src/main/java/io/opencensus/internal/BaseMessageEventUtil.java
  api/src/main/java/io/opencensus/trace/BaseMessageEvent.java
  api/src/main/java/io/opencensus/trace/BlankSpan.java
  api/src/main/java/io/opencensus/trace/MessageEvent.java
  api/src/main/java/io/opencensus/trace/NetworkEvent.java
  api/src/main/java/io/opencensus/trace/Span.java
  api/src/main/java/io/opencensus/trace/config/TraceParams.java
  api/src/main/java/io/opencensus/trace/export/SpanData.java
  api/src/test/java/io/opencensus/internal/BaseMessageEventUtilTest.java
  api/src/test/java/io/opencensus/trace/BlankSpanTest.java
  api/src/test/java/io/opencensus/trace/MessageEventTest.java
  api/src/test/java/io/opencensus/trace/NoopSpan.java
  api/src/test/java/io/opencensus/trace/SpanTest.java
  api/src/test/java/io/opencensus/trace/config/TraceConfigTest.java
  api/src/test/java/io/opencensus/trace/config/TraceParamsTest.java
  api/src/test/java/io/opencensus/trace/export/SpanDataTest.java
  benchmarks/src/jmh/java/io/opencensus/benchmarks/trace/RecordTraceEventsNonSampledSpanBenchmark.java
  benchmarks/src/jmh/java/io/opencensus/benchmarks/trace/RecordTraceEventsSampledSpanBenchmark.java
  contrib/zpages/src/main/java/io/opencensus/contrib/zpages/TraceConfigzZPageHandler.java
  contrib/zpages/src/main/java/io/opencensus/contrib/zpages/TracezZPageHandler.java
  exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandler.java
  exporters/trace/zipkin/src/main/java/io/opencensus/exporter/trace/zipkin/ZipkinExporterHandler.java
  findbugs-exclude.xml
  impl_core/src/main/java/io/opencensus/implcore/trace/SpanImpl.java
Labels: API, cla: yes

#1002 Add StatsZ Zpage for stats.
  contrib/zpages/src/main/java/io/opencensus/contrib/zpages/StatszZPageHandler.java
  contrib/zpages/src/main/java/io/opencensus/contrib/zpages/ZPageHandlers.java
  contrib/zpages/src/test/java/io/opencensus/contrib/zpages/StatszZPageHandlerTest.java
  contrib/zpages/src/test/java/io/opencensus/contrib/zpages/ZPageHandlersTest.java
Labels: cla: yes, stats, zpages

#1005 Remove a redundant annotation.
  contrib/zpages/src/main/java/io/opencensus/contrib/zpages/StatszZPageHandler.java
Labels: cla: yes, enhancement

#1006 Synchronize the access to the tree, views and measures for Statsz.
  contrib/zpages/src/main/java/io/opencensus/contrib/zpages/StatszZPageHandler.java
Labels: bug, cla: yes, stats, zpages

#1004 Start 0.13.0 development cycle
  api/src/main/java/io/opencensus/common/OpenCensusLibraryInformation.java
  build.gradle
  examples/build.gradle
  examples/pom.xml
Labels: cla: yes, release

#996 Update READMEs to include Prometheus exporter.
  README.md
  exporters/stats/prometheus/README.md
Labels: cla: yes, documentation, exporters, stats

#1007 Release
  api/src/main/java/io/opencensus/common/OpenCensusLibraryInformation.java
  build.gradle
  examples/build.gradle
  examples/pom.xml
Labels: cla: yes, release

#1010 Update release versions for all readme and build files.
  README.md
  contrib/grpc_util/README.md
  contrib/http_util/README.md
  contrib/zpages/README.md
  examples/build.gradle
  examples/pom.xml
  exporters/stats/signalfx/README.md
  exporters/stats/stackdriver/README.md
  exporters/trace/logging/README.md
  exporters/trace/stackdriver/README.md
  exporters/trace/zipkin/README.md
Labels: cla: yes, documentation, release

#1011 Update opencensus version for bazel build file in examples
  examples/opencensus_workspace.bzl
Labels: cla: yes, documentation, release

#1016 Test with oraclejdk9 on Travis.
  .travis.yml
  api/src/main/java/io/opencensus/stats/Stats.java
  api/src/main/java/io/opencensus/tags/Tags.java
  api/src/main/java/io/opencensus/trace/Tracing.java
  build.gradle
  impl_core/src/main/java/io/opencensus/implcore/trace/SpanImpl.java
  scripts/travis_script
Labels: build, cla: yes, continuous integration

#1021 Fix bugs, fix warnings and update disruptor.
  build.gradle
  impl/src/main/java/io/opencensus/impl/internal/DisruptorEventQueue.java
Labels: cla: yes

#1024 Fix bugs, fix warnings and update disruptor. (#1021)
  build.gradle
  impl/src/main/java/io/opencensus/impl/internal/DisruptorEventQueue.java
Labels: bug, cla: yes, release

#1025 Release
  api/src/main/java/io/opencensus/common/OpenCensusLibraryInformation.java
  build.gradle
  examples/build.gradle
  examples/pom.xml
Labels: cla: yes, release

#1026 Upgrade disruptor to include the fix for SleepingWaitStrategy causing 100% CPU usage
  build.gradle
Labels: cla: yes

#1027 Upgrade disruptor to include the fix for SleepingWaitStrategy causing…
  build.gradle
Labels: bug, cla: yes, release

#1019 Remove stackdriver dependencyConvergence failure list because they are not clean.
  build.gradle
Labels: cla: yes

#1029 Release
  api/src/main/java/io/opencensus/common/OpenCensusLibraryInformation.java
  build.gradle
  examples/build.gradle
  examples/pom.xml
Labels: cla: yes, release

#1031 Reorganize warning suppression and enable -Werror with Java 7.
  build.gradle
Labels: build, cla: yes

#1022 Cleanup benchmarks and test both impl and impl-lite.
  benchmarks/README.md
  benchmarks/build.gradle
  benchmarks/src/jmh/java/io/opencensus/benchmarks/trace/BenchmarksUtil.java
  benchmarks/src/jmh/java/io/opencensus/benchmarks/trace/RecordTraceEventsBenchmark.java
  benchmarks/src/jmh/java/io/opencensus/benchmarks/trace/RecordTraceEventsNonSampledSpanBenchmark.java
  benchmarks/src/jmh/java/io/opencensus/benchmarks/trace/StartEndSpanBenchmark.java
  settings.gradle
Labels: cla: yes

#1032 Suppress all FindBugs warnings about NullPointerExceptions.
  findbugs-exclude.xml
Labels: build, cla: yes

#1033 Update release versions for all readme and build files.
  README.md
  contrib/grpc_util/README.md
  contrib/http_util/README.md
  contrib/zpages/README.md
  examples/build.gradle
  examples/opencensus_workspace.bzl
  examples/pom.xml
  exporters/stats/prometheus/README.md
  exporters/stats/signalfx/README.md
  exporters/stats/stackdriver/README.md
  exporters/trace/instana/README.md
  exporters/trace/logging/README.md
  exporters/trace/stackdriver/README.md
  exporters/trace/zipkin/README.md
Labels: cla: yes, documentation, release

#1035 Add instruction on formatting files
  CONTRIBUTING.md
Labels: cla: yes, documentation

#1036 Fix typo.
  exporters/stats/stackdriver/README.md
Labels: cla: yes
