Repository census-instrumentation/opencensus-java, pull requests merged in 2018-06, with the labels that each got.

#1223 Add Span.Kind to the trace API.
  CHANGELOG.md
  api/src/main/java/io/opencensus/trace/Span.java
  api/src/main/java/io/opencensus/trace/SpanBuilder.java
  api/src/main/java/io/opencensus/trace/export/SpanData.java
  api/src/test/java/io/opencensus/trace/SpanBuilderTest.java
  api/src/test/java/io/opencensus/trace/export/SpanDataTest.java
  impl_core/src/main/java/io/opencensus/implcore/trace/SpanBuilderImpl.java
  impl_core/src/main/java/io/opencensus/implcore/trace/SpanImpl.java
  impl_core/src/test/java/io/opencensus/implcore/trace/SpanBuilderImplTest.java
  impl_core/src/test/java/io/opencensus/implcore/trace/SpanImplTest.java
  impl_core/src/test/java/io/opencensus/implcore/trace/export/InProcessRunningSpanStoreImplTest.java
  impl_core/src/test/java/io/opencensus/implcore/trace/export/InProcessSampledSpanStoreImplTest.java
  impl_core/src/test/java/io/opencensus/implcore/trace/export/NoopRunningSpanStoreImplTest.java
  impl_core/src/test/java/io/opencensus/implcore/trace/export/NoopSampledSpanStoreImplTest.java
  impl_core/src/test/java/io/opencensus/implcore/trace/export/SpanExporterImplTest.java
Labels: cla: yes

#1229 Temporarily disable example-bazel build for Travis CI.
  .travis.yml
Labels: cla: yes, continuous integration

#1226 Add since for Span.Kind constants and make SpanBuilder.setSpanKind not abstract.
  api/src/main/java/io/opencensus/trace/Span.java
  api/src/main/java/io/opencensus/trace/SpanBuilder.java
Labels: cla: yes

#1225 Cleanup trace exporters.
  exporters/trace/instana/src/main/java/io/opencensus/exporter/trace/instana/InstanaExporterHandler.java
  exporters/trace/instana/src/test/java/io/opencensus/exporter/trace/instana/InstanaExporterHandlerTest.java
  exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandler.java
  exporters/trace/stackdriver/src/test/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandlerProtoTest.java
  exporters/trace/zipkin/src/main/java/io/opencensus/exporter/trace/zipkin/ZipkinExporterHandler.java
  exporters/trace/zipkin/src/test/java/io/opencensus/exporter/trace/zipkin/ZipkinExporterHandlerTest.java
Labels: cla: yes

#1232 Fix checkstyle download link.
  buildscripts/kokoro/linux_presubmit.sh
  scripts/travis_script
Labels: build, cla: yes

#1231 Update gradle to 4.7.
  examples/gradle/wrapper/gradle-wrapper.jar
  examples/gradle/wrapper/gradle-wrapper.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: build, cla: yes

#1230 Add started_rpcs measures and views to RPC constants.
  CHANGELOG.md
  contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcMeasureConstants.java
  contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcViewConstants.java
  contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcViews.java
  contrib/grpc_metrics/src/test/java/io/opencensus/contrib/grpc/metrics/RpcMeasureConstantsTest.java
  contrib/grpc_metrics/src/test/java/io/opencensus/contrib/grpc/metrics/RpcViewConstantsTest.java
Labels: API, cla: yes, gRPC

#1233 Start 0.15.0 development cycle
  api/src/main/java/io/opencensus/common/OpenCensusLibraryInformation.java
  build.gradle
  examples/build.gradle
  examples/pom.xml
Labels: cla: yes, release

#1234 Release
  api/src/main/java/io/opencensus/common/OpenCensusLibraryInformation.java
  build.gradle
  examples/build.gradle
  examples/pom.xml
Labels: cla: yes, release

#1235 Update CHANGELOG
  CHANGELOG.md
Labels: cla: yes, documentation, release

#1236 Update CHANGELOG (#1235)
  CHANGELOG.md
Labels: cla: yes, documentation, release

#1237 Update release versions for all readme and build files.
  README.md
  contrib/grpc_util/README.md
  contrib/http_util/README.md
  contrib/monitored_resource_util/README.md
  contrib/zpages/README.md
  examples/WORKSPACE
  examples/build.gradle
  examples/opencensus_workspace.bzl
  examples/pom.xml
  exporters/stats/prometheus/README.md
  exporters/stats/signalfx/README.md
  exporters/stats/stackdriver/README.md
  exporters/trace/instana/README.md
  exporters/trace/jaeger/README.md
  exporters/trace/logging/README.md
  exporters/trace/stackdriver/README.md
  exporters/trace/zipkin/README.md
Labels: cla: yes, documentation, release

#1216 Metrics: Move Metrics to a separate artifact.
  build.gradle
  buildscripts/import-control.xml
  metrics/README.md
  metrics/build.gradle
  metrics/src/main/java/io/opencensus/metrics/package-info.java
  settings.gradle
Labels: API, cla: yes, discussion, metrics

#1241 Update Google Cloud version.
  build.gradle
Labels: cla: yes

#1242 Remove Checkstyle rule VariableDeclarationUsageDistance
  buildscripts/checkstyle.xml
Labels: build, cla: yes, discussion

#1245 Add package-info for all main packages in opencensus-api.
  api/src/main/java/io/opencensus/common/package-info.java
  api/src/main/java/io/opencensus/stats/package-info.java
  api/src/main/java/io/opencensus/trace/package-info.java
Labels: cla: yes

#1247 Examples: add runtime dependency on netty-tcnative-boringssl-static.
  examples/build.gradle
  examples/pom.xml
Labels: bug, build, cla: yes, examples, gRPC

#1248 Checker Framework: 2.5.1 -> 2.5.2
  build.gradle
Labels: cla: yes, static analysis

#1249 Stackdriver Stats Exporter: remove unnecessary SuppressWarnings.
  exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtils.java
Labels: cla: yes, exporters, stats

#1250 Expose the factory methods of MonitoredResource.
  CHANGELOG.md
  contrib/monitored_resource_util/src/main/java/io/opencensus/contrib/monitoredresource/util/MonitoredResource.java
  contrib/monitored_resource_util/src/test/java/io/opencensus/contrib/monitoredresource/util/MonitoredResourceTest.java
Labels: API, cla: yes, contrib

#1243 Stackdriver Trace Exporter: add resource labels to Spans.
  buildscripts/import-control.xml
  exporters/trace/stackdriver/build.gradle
  exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandler.java
  exporters/trace/stackdriver/src/test/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandlerProtoTest.java
Labels: cla: yes, exporters, tracing

#1212 Start adding log correlation for Stackdriver Logging.
  all/build.gradle
  build.gradle
  buildscripts/import-control.xml
  contrib/log_correlation/stackdriver/README.md
  contrib/log_correlation/stackdriver/build.gradle
  contrib/log_correlation/stackdriver/src/main/java/io/opencensus/contrib/logcorrelation/stackdriver/OpenCensusTraceLoggingEnhancer.java
  contrib/log_correlation/stackdriver/src/test/java/io/opencensus/contrib/logcorrelation/stackdriver/OpenCensusTraceLoggingEnhancerTest.java
  settings.gradle
Labels: cla: yes, tracing

#1253 Stackdriver Stats Exporter: don't set StartTime for Gauge values.
  exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtils.java
  exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtilsTest.java
Labels: cla: yes, exporters

#1254 Stackdriver Trace Exporter: improve unit tests on resource labels.
  exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandler.java
  exporters/trace/stackdriver/src/test/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandlerExportTest.java
  exporters/trace/stackdriver/src/test/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandlerProtoTest.java
Labels: cla: yes, exporters, tests

#1257 Error Prone: 2.2.0 -> 2.3.1
  .travis.yml
  api/src/main/java/io/opencensus/trace/CurrentSpanUtils.java
  api/src/test/java/io/opencensus/tags/TagContextTest.java
  api/src/test/java/io/opencensus/trace/SpanBuilderTest.java
  build.gradle
  contrib/log_correlation/stackdriver/src/test/java/io/opencensus/contrib/logcorrelation/stackdriver/OpenCensusTraceLoggingEnhancerTest.java
  exporters/trace/jaeger/src/test/java/io/opencensus/exporter/trace/jaeger/JaegerExporterHandlerIntegrationTest.java
  gradle/errorprone/experimental_errors
  gradle/errorprone/experimental_suggestions
  gradle/errorprone/experimental_warnings
  gradle/errorprone/warnings
  impl_core/src/test/java/io/opencensus/implcore/trace/SpanBuilderImplTest.java
  impl_core/src/test/java/io/opencensus/implcore/trace/export/InProcessRunningSpanStoreImplTest.java
  impl_core/src/test/java/io/opencensus/implcore/trace/export/SpanExporterImplTest.java
Labels: build, cla: yes, static analysis

#1259 Add ALL_SPANS/NO_SPANS/SAMPLED_SPANS property to OpenCensusTraceLoggingEnhancer.
  contrib/log_correlation/stackdriver/build.gradle
  contrib/log_correlation/stackdriver/src/main/java/io/opencensus/contrib/logcorrelation/stackdriver/OpenCensusTraceLoggingEnhancer.java
  contrib/log_correlation/stackdriver/src/test/java/io/opencensus/contrib/logcorrelation/stackdriver/OpenCensusTraceLoggingEnhancerTest.java
Labels: cla: yes, tracing

#1260 Allow overriding the Project ID used by OpenCensusTraceLoggingEnhancer.
  contrib/log_correlation/stackdriver/src/main/java/io/opencensus/contrib/logcorrelation/stackdriver/OpenCensusTraceLoggingEnhancer.java
  contrib/log_correlation/stackdriver/src/test/java/io/opencensus/contrib/logcorrelation/stackdriver/OpenCensusTraceLoggingEnhancerTest.java
Labels: cla: yes, tracing

#1262 Add opencensus-contrib-log-correlation-stackdriver to the list of released artifacts.
  build.gradle
  contrib/log_correlation/stackdriver/src/main/java/io/opencensus/contrib/logcorrelation/stackdriver/OpenCensusTraceLoggingEnhancer.java
Labels: cla: yes, tracing

#1266 Document and clean up opencensus-contrib-log-correlation-stackdriver.
  contrib/log_correlation/stackdriver/README.md
  contrib/log_correlation/stackdriver/src/main/java/io/opencensus/contrib/logcorrelation/stackdriver/OpenCensusTraceLoggingEnhancer.java
  contrib/log_correlation/stackdriver/src/test/java/io/opencensus/contrib/logcorrelation/stackdriver/OpenCensusTraceLoggingEnhancerTest.java
Labels: cla: yes, tracing

#1261 Metrics: Add LabelKey and LabelValue.
  metrics/src/main/java/io/opencensus/metrics/LabelKey.java
  metrics/src/main/java/io/opencensus/metrics/LabelValue.java
  metrics/src/test/java/io/opencensus/metrics/LabelKeyTest.java
  metrics/src/test/java/io/opencensus/metrics/LabelValueTest.java
  settings.gradle
Labels: API, cla: yes, metrics

#1269 Add contrib/log_correlation/stackdriver/README.md to RELEASING.md.
  RELEASING.md
Labels: cla: yes, tracing

#1270 Add opencensus-contrib-log-correlation-stackdriver to changelog.
  CHANGELOG.md
Labels: cla: yes, tracing

#1267 Stats: Only include the simple class name in the error message for ViewData.check methods.
  api/src/main/java/io/opencensus/stats/ViewData.java
  api/src/test/java/io/opencensus/stats/ViewDataTest.java
Labels: bug, cla: yes, stats

#1273 Update Google Cloud version.
  build.gradle
Labels: build, cla: yes

#1274 Start 0.16.0 development cycle
  api/src/main/java/io/opencensus/common/OpenCensusLibraryInformation.java
  build.gradle
  examples/build.gradle
  examples/pom.xml
Labels: cla: yes, release

#1275 Release 0.15.0.
  api/src/main/java/io/opencensus/common/OpenCensusLibraryInformation.java
  build.gradle
  examples/build.gradle
  examples/pom.xml
Labels: cla: yes, release

#1276 Update changelog for 0.15.0 release.
  CHANGELOG.md
Labels: cla: yes, documentation, release

#1277 Update release versions for all readme and build files.
  README.md
  contrib/appengine_standard_util/README.md
  contrib/grpc_util/README.md
  contrib/http_util/README.md
  contrib/log_correlation/stackdriver/README.md
  contrib/monitored_resource_util/README.md
  contrib/zpages/README.md
  examples/build.gradle
  examples/opencensus_workspace.bzl
  examples/pom.xml
  exporters/stats/prometheus/README.md
  exporters/stats/signalfx/README.md
  exporters/stats/stackdriver/README.md
  exporters/trace/instana/README.md
  exporters/trace/jaeger/README.md
  exporters/trace/logging/README.md
  exporters/trace/stackdriver/README.md
  exporters/trace/zipkin/README.md
Labels: cla: yes, documentation, release

#1278 Fix broken link in README.md
  README.md
Labels: cla: yes, documentation

#1272 Summary Span: Add encoder/decoder for Server Stats.
  api/src/main/java/io/opencensus/common/ServerStats.java
  api/src/main/java/io/opencensus/common/ServerStatsDeserializationException.java
  api/src/main/java/io/opencensus/common/ServerStatsEncoding.java
  api/src/main/java/io/opencensus/common/ServerStatsFieldEnums.java
  api/src/test/java/io/opencensus/common/ServerStatsEncodingTest.java
  api/src/test/java/io/opencensus/common/ServerStatsFieldEnumsTest.java
  api/src/test/java/io/opencensus/common/ServerStatsTest.java
Labels: API, cla: yes, common

#1279 Examples: Record some stats and spans for ZPageTester.
  examples/src/main/java/io/opencensus/examples/zpages/ZPagesTester.java
Labels: cla: yes, enhancement, examples, zpages

#1280 Example: record against an example method tag.
  examples/src/main/java/io/opencensus/examples/zpages/ZPagesTester.java
Labels: cla: yes, enhancement, examples, zpages

#1281 Update Cloud Beta and GA versions.
  build.gradle
Labels: build, cla: yes

#1282 gRPC metrics: Add APIs to register gRPC client and server views separately.
  CHANGELOG.md
  contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcViews.java
  contrib/grpc_metrics/src/test/java/io/opencensus/contrib/grpc/metrics/RpcViewsTest.java
Labels: API, cla: yes, gRPC

#1283 Clarify Javadoc for Tagger.withTagContext.
  api/src/main/java/io/opencensus/tags/Tagger.java
Labels: cla: yes, documentation, tags

#1263 Metrics: Add Value and Point.
  metrics/src/main/java/io/opencensus/metrics/Distribution.java
  metrics/src/main/java/io/opencensus/metrics/Point.java
  metrics/src/main/java/io/opencensus/metrics/Utils.java
  metrics/src/main/java/io/opencensus/metrics/Value.java
  metrics/src/test/java/io/opencensus/metrics/DistributionTest.java
  metrics/src/test/java/io/opencensus/metrics/PointTest.java
  metrics/src/test/java/io/opencensus/metrics/ValueTest.java
Labels: API, cla: yes, metrics

#1285 Stats: Add API MeasureMap.putAttachment() for recording exemplars.
  CHANGELOG.md
  api/src/main/java/io/opencensus/stats/MeasureMap.java
  api/src/test/java/io/opencensus/stats/NoopStatsTest.java
  impl_core/src/main/java/io/opencensus/implcore/stats/MeasureMapImpl.java
  impl_core/src/main/java/io/opencensus/implcore/stats/MeasureMapInternal.java
  impl_core/src/main/java/io/opencensus/implcore/stats/MeasureToViewMap.java
  impl_core/src/main/java/io/opencensus/implcore/stats/MutableViewData.java
Labels: API, cla: yes, stats

#1287 Stats: Add Exemplar class to DistributionData.
  api/src/main/java/io/opencensus/stats/AggregationData.java
  api/src/test/java/io/opencensus/stats/AggregationDataTest.java
Labels: API, cla: yes, stats

#1290 Readme: Update library stage to Beta.
  README.md
Labels: cla: yes, documentation

#1264 Metrics: Add TimeSeries.
  metrics/src/main/java/io/opencensus/metrics/TimeSeries.java
  metrics/src/main/java/io/opencensus/metrics/Utils.java
  metrics/src/test/java/io/opencensus/metrics/TimeSeriesTest.java
Labels: API, cla: yes, metrics
