Repository census-instrumentation/opencensus-java, pull requests merged in 2018-09, with the labels that each got.

#1402 Add readme for opencensus-contrib-log-correlation-log4j.
  RELEASING.md
  contrib/log_correlation/log4j/README.md
Labels: cla: yes, contrib, tracing

#1405 Log4j log correlation: Add unit tests for handling configuration properties.
  contrib/log_correlation/log4j/src/test/java/io/opencensus/contrib/logcorrelation/log4j/OpenCensusLog4jLogCorrelationAllSpansTest.java
  contrib/log_correlation/log4j/src/test/java/io/opencensus/contrib/logcorrelation/log4j/OpenCensusTraceContextDataInjectorTest.java
Labels: cla: yes, contrib, tracing

#1406 Stackdriver log correlation: Improve description of library stability.
  contrib/log_correlation/stackdriver/README.md
Labels: cla: yes, contrib, tracing

#1409 Contrib/agent: detach() should take the context returned from attach().
  contrib/agent/src/integration-test/java/io/opencensus/contrib/agent/instrumentation/ThreadInstrumentationIT.java
Labels: agent, cla: yes, contrib

#1378 Spring sleuth
  RELEASING.md
  all/build.gradle
  build.gradle
  buildscripts/import-control.xml
  checker-framework/stubs/org-springframework-cloud-sleuth.astub
  checker-framework/stubs/org-springframework-cloud-sleuth.log.astub
  contrib/spring_sleuth/README.md
  contrib/spring_sleuth/build.gradle
  contrib/spring_sleuth/src/main/java/io/opencensus/contrib/spring/sleuth/OpenCensusSleuthAutoConfiguration.java
  contrib/spring_sleuth/src/main/java/io/opencensus/contrib/spring/sleuth/OpenCensusSleuthProperties.java
  contrib/spring_sleuth/src/main/java/io/opencensus/contrib/spring/sleuth/OpenCensusSleuthSpan.java
  contrib/spring_sleuth/src/main/java/io/opencensus/contrib/spring/sleuth/OpenCensusSleuthSpanContextHolder.java
  contrib/spring_sleuth/src/main/java/io/opencensus/contrib/spring/sleuth/OpenCensusSleuthTracer.java
  contrib/spring_sleuth/src/main/resources/META-INF/additional-spring-configuration-metadata.json
  contrib/spring_sleuth/src/main/resources/META-INF/spring.factories
  contrib/spring_sleuth/src/test/java/io/opencensus/contrib/spring/sleuth/OpenCensusSleuthSpanContextHolderTest.java
  contrib/spring_sleuth/src/test/java/io/opencensus/contrib/spring/sleuth/OpenCensusSleuthSpanTest.java
  contrib/spring_sleuth/src/test/java/io/opencensus/contrib/spring/sleuth/OpenCensusSleuthTracerTest.java
  settings.gradle
Labels: action required, cla: yes, contrib, tracing

#1412 Checker Framework: 2.5.4 -> 2.5.5
  build.gradle
Labels: cla: yes, static analysis

#1411 Rename opencensus-contrib-log-correlation-log4j artifact/package to use log4j2.
  all/build.gradle
  build.gradle
  buildscripts/import-control.xml
  contrib/log_correlation/log4j2/README.md
  contrib/log_correlation/log4j2/build.gradle
  contrib/log_correlation/log4j2/src/main/java/io/opencensus/contrib/logcorrelation/log4j2/OpenCensusTraceContextDataInjector.java
  contrib/log_correlation/log4j2/src/test/java/io/opencensus/contrib/logcorrelation/log4j2/AbstractOpenCensusLog4jLogCorrelationTest.java
  contrib/log_correlation/log4j2/src/test/java/io/opencensus/contrib/logcorrelation/log4j2/OpenCensusLog4jLogCorrelationAllSpansTest.java
  contrib/log_correlation/log4j2/src/test/java/io/opencensus/contrib/logcorrelation/log4j2/OpenCensusLog4jLogCorrelationNoSpansTest.java
  contrib/log_correlation/log4j2/src/test/java/io/opencensus/contrib/logcorrelation/log4j2/OpenCensusLog4jLogCorrelationSampledSpansTest.java
  contrib/log_correlation/log4j2/src/test/java/io/opencensus/contrib/logcorrelation/log4j2/OpenCensusTraceContextDataInjectorTest.java
  settings.gradle
Labels: cla: yes, contrib, tracing

#1416 Update opencensus-contrib-log-correlation-log4j2 artifact/package names in readme.
  contrib/log_correlation/log4j2/README.md
Labels: cla: yes, contrib, tracing

#1414 Log4j log correlation: Capitalize "opencensus" as one word in context key names.
  contrib/log_correlation/log4j2/README.md
  contrib/log_correlation/log4j2/src/main/java/io/opencensus/contrib/logcorrelation/log4j2/OpenCensusTraceContextDataInjector.java
  contrib/log_correlation/log4j2/src/test/java/io/opencensus/contrib/logcorrelation/log4j2/AbstractOpenCensusLog4jLogCorrelationTest.java
  contrib/log_correlation/log4j2/src/test/java/io/opencensus/contrib/logcorrelation/log4j2/OpenCensusTraceContextDataInjectorTest.java
Labels: cla: yes, contrib, tracing

#1417 Change spring-sleuth package to include version.
  all/build.gradle
  build.gradle
  contrib/spring_sleuth_v1x/README.md
  contrib/spring_sleuth_v1x/build.gradle
  contrib/spring_sleuth_v1x/src/main/java/io/opencensus/contrib/spring/sleuth/v1x/OpenCensusSleuthAutoConfiguration.java
  contrib/spring_sleuth_v1x/src/main/java/io/opencensus/contrib/spring/sleuth/v1x/OpenCensusSleuthProperties.java
  contrib/spring_sleuth_v1x/src/main/java/io/opencensus/contrib/spring/sleuth/v1x/OpenCensusSleuthSpan.java
  contrib/spring_sleuth_v1x/src/main/java/io/opencensus/contrib/spring/sleuth/v1x/OpenCensusSleuthSpanContextHolder.java
  contrib/spring_sleuth_v1x/src/main/java/io/opencensus/contrib/spring/sleuth/v1x/OpenCensusSleuthTracer.java
  contrib/spring_sleuth_v1x/src/main/resources/META-INF/additional-spring-configuration-metadata.json
  contrib/spring_sleuth_v1x/src/main/resources/META-INF/spring.factories
  contrib/spring_sleuth_v1x/src/test/java/io/opencensus/contrib/spring/sleuth/v1x/OpenCensusSleuthSpanContextHolderTest.java
  contrib/spring_sleuth_v1x/src/test/java/io/opencensus/contrib/spring/sleuth/v1x/OpenCensusSleuthSpanTest.java
  contrib/spring_sleuth_v1x/src/test/java/io/opencensus/contrib/spring/sleuth/v1x/OpenCensusSleuthTracerTest.java
  settings.gradle
Labels: cla: yes

#1420 Fix a memory reference issue caused by the fact that we always append a new value.
  contrib/spring_sleuth_v1x/src/main/java/io/opencensus/contrib/spring/sleuth/v1x/OpenCensusSleuthSpanContextHolder.java
Labels: cla: yes

#1421 Avoid using internal org.apache.logging.log4j.core.impl package.
  buildscripts/import-control.xml
  contrib/log_correlation/log4j2/src/main/java/io/opencensus/contrib/logcorrelation/log4j2/OpenCensusTraceContextDataInjector.java
Labels: cla: yes, contrib, tracing

#1425 Make jmh available for all subprojects.
  CONTRIBUTING.md
  all/build.gradle
  api/build.gradle
  benchmarks/README.md
  benchmarks/build.gradle
  build.gradle
  contrib/agent/build.gradle
  impl_core/src/jmh/java/io/opencensus/implcore/trace/propagation/B3FormatImplBenchmark.java
  impl_core/src/jmh/java/io/opencensus/implcore/trace/propagation/BinaryFormatImplBenchmark.java
  impl_core/src/jmh/java/io/opencensus/implcore/trace/propagation/TextFormatBenchmarkBase.java
Labels: cla: yes

#1427 Make LowerCaseBase16Encoding package protected.
  api/src/main/java/io/opencensus/trace/LowerCaseBase16Encoding.java
  api/src/main/java/io/opencensus/trace/SpanId.java
  api/src/main/java/io/opencensus/trace/TraceId.java
  api/src/test/java/io/opencensus/trace/LowerCaseBase16EncodingTest.java
Labels: cla: yes

#1413 Improve implementation of OpenCensusTraceContextDataInjector.
  buildscripts/import-control.xml
  checker-framework/stubs/log4j.astub
  contrib/log_correlation/log4j2/src/main/java/io/opencensus/contrib/logcorrelation/log4j2/ContextDataUtils.java
  contrib/log_correlation/log4j2/src/main/java/io/opencensus/contrib/logcorrelation/log4j2/OpenCensusTraceContextDataInjector.java
  contrib/log_correlation/log4j2/src/test/java/io/opencensus/contrib/logcorrelation/log4j2/OpenCensusLog4jLogCorrelationAllSpansTest.java
  contrib/log_correlation/log4j2/src/test/java/io/opencensus/contrib/logcorrelation/log4j2/OpenCensusTraceContextDataInjectorTest.java
Labels: cla: yes, contrib, tracing

#1415 Add opencensus-contrib-log-correlation-log4j2 to the list of released artifacts.
  CHANGELOG.md
  build.gradle
Labels: cla: yes, contrib, tracing

#1429 Start 0.17.0 development cycle
  api/src/main/java/io/opencensus/common/OpenCensusLibraryInformation.java
  build.gradle
  examples/build.gradle
  examples/pom.xml
Labels: cla: yes, release

#1430 Update release instructions for new Github branch protection rules.
  RELEASING.md
Labels: cla: yes, documentation, release

#1431 Release 0.16.0
  api/src/main/java/io/opencensus/common/OpenCensusLibraryInformation.java
  build.gradle
  examples/build.gradle
  examples/pom.xml
Labels: cla: yes, release

#1434 Update directory names in RELEASING.md.
  RELEASING.md
Labels: cla: yes, release

#1435 Update release versions for all readme and build files.
  README.md
  contrib/appengine_standard_util/README.md
  contrib/grpc_util/README.md
  contrib/http_util/README.md
  contrib/log_correlation/log4j2/README.md
  contrib/log_correlation/stackdriver/README.md
  contrib/monitored_resource_util/README.md
  contrib/zpages/README.md
  examples/build.gradle
  examples/pom.xml
  exporters/stats/prometheus/README.md
  exporters/stats/signalfx/README.md
  exporters/stats/stackdriver/README.md
  exporters/trace/instana/README.md
  exporters/trace/jaeger/README.md
  exporters/trace/logging/README.md
  exporters/trace/stackdriver/README.md
  exporters/trace/zipkin/README.md
Labels: cla: yes, documentation, release

#1438 Update changelog for 0.16.0 release.
  CHANGELOG.md
Labels: cla: yes, documentation, release

#1442 Tracing: Add AttributeValueDouble.
  CHANGELOG.md
  api/src/main/java/io/opencensus/trace/AttributeValue.java
  api/src/test/java/io/opencensus/trace/AttributeValueTest.java
  contrib/zpages/src/main/java/io/opencensus/contrib/zpages/TracezZPageHandler.java
  exporters/trace/instana/src/main/java/io/opencensus/exporter/trace/instana/InstanaExporterHandler.java
  exporters/trace/jaeger/src/main/java/io/opencensus/exporter/trace/jaeger/JaegerExporterHandler.java
  exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandler.java
  exporters/trace/zipkin/src/main/java/io/opencensus/exporter/trace/zipkin/ZipkinExporterHandler.java
Labels: API, cla: yes, tracing

#1440 allow arbitrary metric prefixes
  CHANGELOG.md
  exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExporterWorker.java
  exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverExporterWorkerTest.java
Labels: cla: yes

#1437 Fix ClassCastException in opencensus-contrib-log-correlation-log4j2.
  contrib/log_correlation/log4j2/src/main/java/io/opencensus/contrib/logcorrelation/log4j2/ContextDataUtils.java
Labels: cla: yes, contrib, tracing

#1439 Update links to Log4j log correlation demo.
  contrib/log_correlation/log4j2/README.md
Labels: cla: yes, contrib, documentation, tracing

#1446 Fix ClassCastException in opencensus-contrib-log-correlation-log4j2. (v0.16.x)
  contrib/log_correlation/log4j2/src/main/java/io/opencensus/contrib/logcorrelation/log4j2/ContextDataUtils.java
Labels: cla: yes, contrib, tracing

#1448 Update changelog for 0.16.0 release. (v0.16.x)
  CHANGELOG.md
Labels: cla: yes, release

#1449 allow arbitrary metric prefixes (v0.16.x)
  CHANGELOG.md
  exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExporterWorker.java
  exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverExporterWorkerTest.java
Labels: cla: yes

#1450 Release 0.16.1
  api/src/main/java/io/opencensus/common/OpenCensusLibraryInformation.java
  build.gradle
  examples/build.gradle
  examples/pom.xml
Labels: cla: yes, release

#1444 Pass a preconfigured HttpSender to the trace exporter
  CHANGELOG.md
  exporters/trace/jaeger/src/main/java/io/opencensus/exporter/trace/jaeger/JaegerTraceExporter.java
Labels: cla: yes

#1451 Update changelog for 0.16.1 release.
  CHANGELOG.md
Labels: cla: yes, release

#1452 Update release versions for all readme and build files.
  README.md
  contrib/appengine_standard_util/README.md
  contrib/exemplar_util/README.md
  contrib/grpc_util/README.md
  contrib/http_util/README.md
  contrib/log_correlation/log4j2/README.md
  contrib/log_correlation/stackdriver/README.md
  contrib/monitored_resource_util/README.md
  contrib/spring/README.md
  contrib/spring_sleuth_v1x/README.md
  contrib/zpages/README.md
  examples/build.gradle
  examples/pom.xml
  exporters/stats/prometheus/README.md
  exporters/stats/signalfx/README.md
  exporters/stats/stackdriver/README.md
  exporters/trace/instana/README.md
  exporters/trace/jaeger/README.md
  exporters/trace/logging/README.md
  exporters/trace/stackdriver/README.md
  exporters/trace/zipkin/README.md
Labels: cla: yes, release

#1453 Update changelog for 0.16.1 release. (v0.16.x)
  CHANGELOG.md
Labels: cla: yes, release

#1457 Update release version for Bazel build files.
  RELEASING.md
  examples/BUILD.bazel
  examples/opencensus_workspace.bzl
Labels: cla: yes, examples, release

#1454 Update a typo in CHANGELOG.
  CHANGELOG.md
Labels: cla: yes, documentation

#1461 Travis: Temporarily disable JDK 9 build.
  .travis.yml
Labels: build, cla: yes, continuous integration

#1422 Improve tests for OpenCensusTraceContextDataInjector.
  contrib/log_correlation/log4j2/src/main/java/io/opencensus/contrib/logcorrelation/log4j2/OpenCensusTraceContextDataInjector.java
  contrib/log_correlation/log4j2/src/test/java/io/opencensus/contrib/logcorrelation/log4j2/AbstractOpenCensusLog4jLogCorrelationTest.java
  contrib/log_correlation/log4j2/src/test/java/io/opencensus/contrib/logcorrelation/log4j2/OpenCensusTraceContextDataInjectorTest.java
  contrib/log_correlation/log4j2/src/test/java/io/opencensus/contrib/logcorrelation/log4j2/TestSpan.java
Labels: cla: yes, contrib, tracing

#1459 Contrib: Add opencensus-contrib-opencensus-proto-util.
  CHANGELOG.md
  RELEASING.md
  all/build.gradle
  build.gradle
  buildscripts/import-control.xml
  contrib/opencensus_proto_util/README.md
  contrib/opencensus_proto_util/build.gradle
  contrib/opencensus_proto_util/src/main/java/io/opencensus/contrib/opencensus/proto/util/TraceProtoUtils.java
  contrib/opencensus_proto_util/src/test/java/io/opencensus/contrib/opencensus/proto/util/TraceProtoUtilsTest.java
  settings.gradle
Labels: API, cla: yes, contrib, tracing

#1462 Improve tests for OpenCensusTraceContextDataInjector. (v0.16.x)
  contrib/log_correlation/log4j2/src/main/java/io/opencensus/contrib/logcorrelation/log4j2/OpenCensusTraceContextDataInjector.java
  contrib/log_correlation/log4j2/src/test/java/io/opencensus/contrib/logcorrelation/log4j2/AbstractOpenCensusLog4jLogCorrelationTest.java
  contrib/log_correlation/log4j2/src/test/java/io/opencensus/contrib/logcorrelation/log4j2/OpenCensusTraceContextDataInjectorTest.java
  contrib/log_correlation/log4j2/src/test/java/io/opencensus/contrib/logcorrelation/log4j2/TestSpan.java
Labels: cla: yes, contrib, tracing

#1466 Avoid 3 allocs, one builders and two objects when startSpan.
  impl_core/src/main/java/io/opencensus/implcore/trace/SpanBuilderImpl.java
Labels: cla: yes, enhancement, tracing

#1468 Split SpanImpl into record/notrecord span impl to avoid checks of recording all time.
  impl_core/src/main/java/io/opencensus/implcore/trace/NoRecordEventsSpanImpl.java
  impl_core/src/main/java/io/opencensus/implcore/trace/RecordEventsSpanImpl.java
  impl_core/src/main/java/io/opencensus/implcore/trace/SpanBuilderImpl.java
  impl_core/src/main/java/io/opencensus/implcore/trace/StartEndHandlerImpl.java
  impl_core/src/main/java/io/opencensus/implcore/trace/TraceComponentImplBase.java
  impl_core/src/main/java/io/opencensus/implcore/trace/TracerImpl.java
  impl_core/src/main/java/io/opencensus/implcore/trace/export/InProcessRunningSpanStoreImpl.java
  impl_core/src/main/java/io/opencensus/implcore/trace/export/InProcessSampledSpanStoreImpl.java
  impl_core/src/main/java/io/opencensus/implcore/trace/export/RunningSpanStoreImpl.java
  impl_core/src/main/java/io/opencensus/implcore/trace/export/SampledSpanStoreImpl.java
  impl_core/src/main/java/io/opencensus/implcore/trace/export/SpanExporterImpl.java
  impl_core/src/test/java/io/opencensus/implcore/trace/NoRecordEventsSpanImplTest.java
  impl_core/src/test/java/io/opencensus/implcore/trace/RecordEventsSpanImplTest.java
  impl_core/src/test/java/io/opencensus/implcore/trace/SpanBuilderImplTest.java
  impl_core/src/test/java/io/opencensus/implcore/trace/TracerImplTest.java
  impl_core/src/test/java/io/opencensus/implcore/trace/export/InProcessRunningSpanStoreImplTest.java
  impl_core/src/test/java/io/opencensus/implcore/trace/export/InProcessSampledSpanStoreImplTest.java
  impl_core/src/test/java/io/opencensus/implcore/trace/export/NoopRunningSpanStoreImplTest.java
  impl_core/src/test/java/io/opencensus/implcore/trace/export/NoopSampledSpanStoreImplTest.java
  impl_core/src/test/java/io/opencensus/implcore/trace/export/SpanExporterImplTest.java
Labels: cla: yes

#1467 Monitored Resource: replace gke_container with k8s_container in SD exporter
  CHANGELOG.md
  exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtils.java
  exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandler.java
  exporters/trace/stackdriver/src/test/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandlerProtoTest.java
Labels: cla: yes

#1469 Avoid using LinkedList and remove couple SuppressWarnings.
  impl_core/src/main/java/io/opencensus/implcore/stats/MutableViewData.java
Labels: cla: yes

#1455 Exporter: Start adding OC-Agent Trace Exporter.
  CHANGELOG.md
  RELEASING.md
  all/build.gradle
  build.gradle
  buildscripts/import-control.xml
  exporters/trace/ocagent/README.md
  exporters/trace/ocagent/build.gradle
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporter.java
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporterConfiguration.java
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporterHandler.java
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/package-info.java
  exporters/trace/ocagent/src/test/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporterConfigurationTest.java
  exporters/trace/ocagent/src/test/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporterTest.java
  settings.gradle
Labels: API, cla: yes, exporters, tracing

#1470 Exporter/OCAgent: Move TraceProtoUtils to exporter.
  CHANGELOG.md
  RELEASING.md
  all/build.gradle
  build.gradle
  buildscripts/import-control.xml
  contrib/opencensus_proto_util/README.md
  contrib/opencensus_proto_util/build.gradle
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/TraceProtoUtils.java
  exporters/trace/ocagent/src/test/java/io/opencensus/exporter/trace/ocagent/TraceProtoUtilsTest.java
  settings.gradle
Labels: cla: yes, contrib, refactoring

#1471 Exporter/OCAgent: Add OcAgentNodeUtils.
  RELEASING.md
  buildscripts/import-control.xml
  exporters/trace/ocagent/build.gradle
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentNodeUtils.java
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporterHandler.java
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/TraceProtoUtils.java
  exporters/trace/ocagent/src/test/java/io/opencensus/exporter/trace/ocagent/OcAgentNodeUtilsTest.java
Labels: cla: yes, exporters, tracing

#1474 Update dependencies.
  build.gradle
Labels: build, cla: yes
