Repository census-instrumentation/opencensus-java, pull requests merged in 2019-03, with the labels that each got.

#1776 Exporter/Trace/OcAgent: Add integration test.
  exporters/trace/ocagent/build.gradle
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporterHandler.java
  exporters/trace/ocagent/src/test/java/io/opencensus/exporter/trace/ocagent/FakeOcAgentTraceServiceGrpcImpl.java
  exporters/trace/ocagent/src/test/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporterIntegrationTest.java
Labels: cla: yes, exporters, tests, tracing

#1781 Modify default value to false for publicEndpoint in Http-Servlet.
  CHANGELOG.md
  contrib/http_servlet/src/main/java/io/opencensus/contrib/http/servlet/OcHttpServletFilter.java
Labels: cla: yes

#1783 Changelog: Fix a typo.
  CHANGELOG.md
Labels: cla: yes

#1785 Changed Public endpoint publicEndpoint from an attribute to init parameter
  contrib/http_servlet/src/main/java/io/opencensus/contrib/http/servlet/OcHttpServletFilter.java
  contrib/http_servlet/src/test/java/io/opencensus/contrib/http/servlet/OcHttpServletFilterTest.java
Labels: cla: yes

#1788 Example: Add OcAgent Exporters quick start.
  examples/README.md
  examples/build.gradle
  examples/pom.xml
  examples/src/main/java/io/opencensus/examples/ocagent/OcAgentExportersQuickStart.java
Labels: cla: yes, examples, exporters

#1786 Exporter/Metrics/OcAgent: Add integration test.
  exporters/metrics/ocagent/build.gradle
  exporters/metrics/ocagent/src/main/java/io/opencensus/exporter/metrics/ocagent/OcAgentMetricsExporter.java
  exporters/metrics/ocagent/src/test/java/io/opencensus/exporter/metrics/ocagent/OcAgentMetricsExporterIntegrationTest.java
Labels: cla: yes, exporters, metrics, tests

#1790 fix path and URL HttpServlet according to spec.
  contrib/http_servlet/src/main/java/io/opencensus/contrib/http/servlet/OcHttpServletExtractor.java
  contrib/http_servlet/src/test/java/io/opencensus/contrib/http/servlet/OcHttpServletExtractorTest.java
Labels: cla: yes

#1779 Stats/Exemplar: Add a generic AttachmentValue class.
  CHANGELOG.md
  api/src/main/java/io/opencensus/stats/AggregationData.java
  api/src/main/java/io/opencensus/stats/AttachmentValue.java
  api/src/main/java/io/opencensus/stats/MeasureMap.java
  api/src/test/java/io/opencensus/stats/AggregationDataTest.java
  api/src/test/java/io/opencensus/stats/AttachmentValueTest.java
  api/src/test/java/io/opencensus/stats/NoopStatsTest.java
  contrib/exemplar_util/build.gradle
  contrib/exemplar_util/src/main/java/io/opencensus/contrib/exemplar/util/AttachmentValueSpanContext.java
  contrib/exemplar_util/src/main/java/io/opencensus/contrib/exemplar/util/ExemplarUtils.java
  contrib/exemplar_util/src/test/java/io/opencensus/contrib/exemplar/util/AttachmentValueSpanContextTest.java
  contrib/exemplar_util/src/test/java/io/opencensus/contrib/exemplar/util/ExemplarUtilsTest.java
  impl_core/src/main/java/io/opencensus/implcore/stats/IntervalBucket.java
  impl_core/src/main/java/io/opencensus/implcore/stats/MeasureMapImpl.java
  impl_core/src/main/java/io/opencensus/implcore/stats/MeasureMapInternal.java
  impl_core/src/main/java/io/opencensus/implcore/stats/MeasureToViewMap.java
  impl_core/src/main/java/io/opencensus/implcore/stats/MetricUtils.java
  impl_core/src/main/java/io/opencensus/implcore/stats/MutableAggregation.java
  impl_core/src/main/java/io/opencensus/implcore/stats/MutableViewData.java
  impl_core/src/test/java/io/opencensus/implcore/stats/IntervalBucketTest.java
  impl_core/src/test/java/io/opencensus/implcore/stats/MeasureMapInternalTest.java
  impl_core/src/test/java/io/opencensus/implcore/stats/MutableAggregationTest.java
  impl_core/src/test/java/io/opencensus/implcore/stats/StatsRecorderImplTest.java
  impl_core/src/test/java/io/opencensus/implcore/stats/StatsTestUtil.java
Labels: API, cla: yes, stats

#1792 Checker Framework: 2.6.0 -> 2.7.0
  build.gradle
  impl_core/src/main/java/io/opencensus/implcore/metrics/DerivedDoubleGaugeImpl.java
  impl_core/src/main/java/io/opencensus/implcore/metrics/DerivedLongGaugeImpl.java
Labels: cla: yes, static analysis

#1793 Remove package qualification from Immutable annotations.
  api/src/main/java/io/opencensus/stats/AggregationData.java
Labels: cla: yes, static analysis

#1774 elasticsearch trace exporter
  CHANGELOG.md
  RELEASING.md
  all/build.gradle
  build.gradle
  exporters/trace/elasticsearch/README.md
  exporters/trace/elasticsearch/build.gradle
  exporters/trace/elasticsearch/src/main/java/io/opencensus/exporter/trace/elasticsearch/ElasticsearchTraceConfiguration.java
  exporters/trace/elasticsearch/src/main/java/io/opencensus/exporter/trace/elasticsearch/ElasticsearchTraceExporter.java
  exporters/trace/elasticsearch/src/main/java/io/opencensus/exporter/trace/elasticsearch/ElasticsearchTraceHandler.java
  exporters/trace/elasticsearch/src/main/java/io/opencensus/exporter/trace/elasticsearch/JsonConversionUtils.java
  exporters/trace/elasticsearch/src/test/java/io/opencensus/exporter/trace/elasticsearch/ElasticsearchTraceExporterTest.java
  exporters/trace/elasticsearch/src/test/java/io/opencensus/exporter/trace/elasticsearch/JsonConversionUtilsTest.java
  settings.gradle
Labels: cla: yes, exporters, tracing

#1795 Build: Upgrade oc-proto version.
  build.gradle
  exporters/metrics/ocagent/src/test/java/io/opencensus/exporter/metrics/ocagent/OcAgentMetricsExporterIntegrationTest.java
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/TraceProtoUtils.java
  exporters/trace/ocagent/src/test/java/io/opencensus/exporter/trace/ocagent/FakeOcAgentTraceServiceGrpcImpl.java
  exporters/trace/ocagent/src/test/java/io/opencensus/exporter/trace/ocagent/FakeOcAgentTraceServiceGrpcImplTest.java
  exporters/trace/ocagent/src/test/java/io/opencensus/exporter/trace/ocagent/TraceProtoUtilsTest.java
Labels: build, cla: yes

#1794 Metrics: Add metrics.data package to hold common classes.
  api/src/main/java/io/opencensus/metrics/data/package-info.java
  buildscripts/import-control.xml
Labels: cla: yes, kokoro:force-run, metrics, refactoring

#1761 Exporter/OcAgent: Add to release artifacts.
  build.gradle
Labels: cla: yes, exporters, metrics

#1791 Exemplar: Refactor to be under metrics.data.
  CHANGELOG.md
  api/src/main/java/io/opencensus/metrics/data/AttachmentValue.java
  api/src/main/java/io/opencensus/metrics/data/Exemplar.java
  api/src/main/java/io/opencensus/metrics/export/Distribution.java
  api/src/main/java/io/opencensus/stats/AggregationData.java
  api/src/main/java/io/opencensus/stats/MeasureMap.java
  api/src/test/java/io/opencensus/metrics/data/AttachmentValueTest.java
  api/src/test/java/io/opencensus/metrics/data/ExemplarTest.java
  api/src/test/java/io/opencensus/metrics/export/DistributionTest.java
  api/src/test/java/io/opencensus/stats/AggregationDataTest.java
  api/src/test/java/io/opencensus/stats/NoopStatsTest.java
  buildscripts/import-control.xml
  contrib/exemplar_util/src/main/java/io/opencensus/contrib/exemplar/util/AttachmentValueSpanContext.java
  contrib/exemplar_util/src/main/java/io/opencensus/contrib/exemplar/util/ExemplarUtils.java
  contrib/exemplar_util/src/test/java/io/opencensus/contrib/exemplar/util/ExemplarUtilsTest.java
  exporters/metrics/ocagent/src/main/java/io/opencensus/exporter/metrics/ocagent/MetricsProtoUtils.java
  exporters/metrics/ocagent/src/test/java/io/opencensus/exporter/metrics/ocagent/MetricsProtoUtilsTests.java
  impl_core/src/main/java/io/opencensus/implcore/stats/IntervalBucket.java
  impl_core/src/main/java/io/opencensus/implcore/stats/MeasureMapImpl.java
  impl_core/src/main/java/io/opencensus/implcore/stats/MeasureMapInternal.java
  impl_core/src/main/java/io/opencensus/implcore/stats/MeasureToViewMap.java
  impl_core/src/main/java/io/opencensus/implcore/stats/MetricUtils.java
  impl_core/src/main/java/io/opencensus/implcore/stats/MutableAggregation.java
  impl_core/src/main/java/io/opencensus/implcore/stats/MutableViewData.java
  impl_core/src/test/java/io/opencensus/implcore/stats/IntervalBucketTest.java
  impl_core/src/test/java/io/opencensus/implcore/stats/MeasureMapInternalTest.java
  impl_core/src/test/java/io/opencensus/implcore/stats/MutableAggregationTest.java
  impl_core/src/test/java/io/opencensus/implcore/stats/StatsRecorderImplTest.java
  impl_core/src/test/java/io/opencensus/implcore/stats/StatsTestUtil.java
Labels: cla: yes, discussion, refactoring

#1771 Exporter/Stats/Stackdriver: Support Exemplar.
  buildscripts/import-control.xml
  exporters/stats/stackdriver/build.gradle
  exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/CreateTimeSeriesExporter.java
  exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtils.java
  exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/CreateTimeSeriesExporterTest.java
  exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtilsTest.java
Labels: cla: yes, exporters, metrics

#1768 Tags: Add TagMetadata.
  CHANGELOG.md
  api/src/main/java/io/opencensus/tags/NoopTags.java
  api/src/main/java/io/opencensus/tags/Tag.java
  api/src/main/java/io/opencensus/tags/TagContextBuilder.java
  api/src/main/java/io/opencensus/tags/TagMetadata.java
  api/src/main/java/io/opencensus/tags/propagation/TagContextBinarySerializer.java
  api/src/test/java/io/opencensus/tags/NoopTagsTest.java
  api/src/test/java/io/opencensus/tags/TagMetadataTest.java
  api/src/test/java/io/opencensus/tags/TagTest.java
  contrib/http_util/src/main/java/io/opencensus/contrib/http/HttpClientHandler.java
  contrib/http_util/src/main/java/io/opencensus/contrib/http/HttpRequestContext.java
  contrib/http_util/src/main/java/io/opencensus/contrib/http/HttpServerHandler.java
  impl_core/src/main/java/io/opencensus/implcore/stats/RecordUtils.java
  impl_core/src/main/java/io/opencensus/implcore/tags/NoopTagMapBuilder.java
  impl_core/src/main/java/io/opencensus/implcore/tags/TagContextUtils.java
  impl_core/src/main/java/io/opencensus/implcore/tags/TagMapBuilderImpl.java
  impl_core/src/main/java/io/opencensus/implcore/tags/TagMapImpl.java
  impl_core/src/main/java/io/opencensus/implcore/tags/TagValueWithMetadata.java
  impl_core/src/main/java/io/opencensus/implcore/tags/propagation/SerializationUtils.java
  impl_core/src/test/java/io/opencensus/implcore/stats/RecordUtilsTest.java
  impl_core/src/test/java/io/opencensus/implcore/tags/ScopedTagMapTest.java
  impl_core/src/test/java/io/opencensus/implcore/tags/TagMapImplTest.java
  impl_core/src/test/java/io/opencensus/implcore/tags/propagation/TagContextBinarySerializerImplTest.java
Labels: API, GA-Effort, cla: yes, tags

#1803 Build: Upgrade dependency versions.
  build.gradle
Labels: build, cla: yes

#1806 Fix a bunch of errorprone warnings.
  api/src/test/java/io/opencensus/common/ServerStatsEncodingTest.java
  api/src/test/java/io/opencensus/common/ServerStatsTest.java
  api/src/test/java/io/opencensus/metrics/MetricRegistryTest.java
  contrib/http_jaxrs/src/test/java/io/opencensus/contrib/http/jaxrs/JaxrsClientFilterTest.java
  contrib/http_jaxrs/src/test/java/io/opencensus/contrib/http/jaxrs/JaxrsContainerFilterTest.java
  contrib/http_jetty_client/src/test/java/io/opencensus/contrib/http/jetty/client/HttpRequestListenerTest.java
  contrib/http_servlet/src/main/java/io/opencensus/contrib/http/servlet/OcHttpServletUtil.java
  contrib/http_servlet/src/test/java/io/opencensus/contrib/http/servlet/OcHttpServletListenerTest.java
  contrib/http_util/src/main/java/io/opencensus/contrib/http/AbstractHttpHandler.java
  contrib/http_util/src/main/java/io/opencensus/contrib/http/HttpClientHandler.java
  contrib/http_util/src/main/java/io/opencensus/contrib/http/HttpServerHandler.java
  contrib/http_util/src/test/java/io/opencensus/contrib/http/AbstractHttpHandlerTest.java
  contrib/zpages/src/main/java/io/opencensus/contrib/zpages/ZPageHttpHandler.java
  contrib/zpages/src/test/java/io/opencensus/contrib/zpages/RpczZPageHandlerTest.java
  contrib/zpages/src/test/java/io/opencensus/contrib/zpages/StatszZPageHandlerTest.java
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporterHandler.java
  impl_core/src/main/java/io/opencensus/implcore/metrics/MetricRegistryImpl.java
  impl_core/src/test/java/io/opencensus/implcore/metrics/MetricRegistryImplTest.java
Labels: cla: yes

#1804 Metrics/Util: Add QueueMetricProducer.
  CHANGELOG.md
  exporters/metrics/util/src/main/java/io/opencensus/exporter/metrics/util/QueueMetricProducer.java
  exporters/metrics/util/src/test/java/io/opencensus/exporter/metrics/util/QueueMetricProducerTest.java
Labels: API, cla: yes, metrics

#1811 Tags: Make the new API non-abstract to avoid breaking other subclasses.
  api/src/main/java/io/opencensus/tags/TagContextBuilder.java
Labels: API, cla: yes, tags

#1816 Examples: Update gRPC version.
  examples/build.gradle
Labels: build, cla: yes, examples

#1814 Add MetricOptions to simplify all addXGuage.
  api/src/main/java/io/opencensus/internal/Utils.java
  api/src/main/java/io/opencensus/metrics/MetricOptions.java
  api/src/main/java/io/opencensus/metrics/MetricRegistry.java
  api/src/test/java/io/opencensus/metrics/MetricOptionsTest.java
  api/src/test/java/io/opencensus/metrics/MetricRegistryTest.java
  impl_core/src/main/java/io/opencensus/implcore/metrics/MetricRegistryImpl.java
  impl_core/src/test/java/io/opencensus/implcore/metrics/MetricRegistryImplTest.java
Labels: cla: yes

#1805 Refactor resource util to match specs.
  contrib/monitored_resource_util/src/main/java/io/opencensus/contrib/monitoredresource/util/MonitoredResource.java
  contrib/monitored_resource_util/src/main/java/io/opencensus/contrib/monitoredresource/util/MonitoredResourceUtils.java
  contrib/monitored_resource_util/src/main/java/io/opencensus/contrib/monitoredresource/util/ResourceKeyConstants.java
  contrib/monitored_resource_util/src/test/java/io/opencensus/contrib/monitoredresource/util/MonitoredResourceUtilsTest.java
  contrib/resource_util/build.gradle
  contrib/resource_util/src/main/java/io/opencensus/contrib/resource/util/AwsEc2InstanceResource.java
  contrib/resource_util/src/main/java/io/opencensus/contrib/resource/util/AwsIdentityDocUtils.java
  contrib/resource_util/src/main/java/io/opencensus/contrib/resource/util/CloudResource.java
  contrib/resource_util/src/main/java/io/opencensus/contrib/resource/util/ContainerResource.java
  contrib/resource_util/src/main/java/io/opencensus/contrib/resource/util/GcpGceInstanceResource.java
  contrib/resource_util/src/main/java/io/opencensus/contrib/resource/util/GcpMetadataConfig.java
  contrib/resource_util/src/main/java/io/opencensus/contrib/resource/util/HostResource.java
  contrib/resource_util/src/main/java/io/opencensus/contrib/resource/util/K8sContainerResource.java
  contrib/resource_util/src/main/java/io/opencensus/contrib/resource/util/K8sResource.java
  contrib/resource_util/src/main/java/io/opencensus/contrib/resource/util/ResourceUtils.java
  contrib/resource_util/src/test/java/io/opencensus/contrib/resource/util/CloudResourceTest.java
  contrib/resource_util/src/test/java/io/opencensus/contrib/resource/util/ContainerResourceTest.java
  contrib/resource_util/src/test/java/io/opencensus/contrib/resource/util/HostResourceTest.java
  contrib/resource_util/src/test/java/io/opencensus/contrib/resource/util/K8sResourceTest.java
  contrib/resource_util/src/test/java/io/opencensus/contrib/resource/util/ResourceUtilsTest.java
  exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtils.java
  exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtilsTest.java
  exporters/trace/stackdriver/src/test/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandlerProtoTest.java
Labels: cla: yes, resource

#1817 Start 0.21.0 development cycle
  api/src/main/java/io/opencensus/common/OpenCensusLibraryInformation.java
  build.gradle
  examples/build.gradle
  examples/pom.xml
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentNodeUtils.java
Labels: cla: yes

#1819 Release
  api/src/main/java/io/opencensus/common/OpenCensusLibraryInformation.java
  build.gradle
  examples/build.gradle
  examples/pom.xml
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentNodeUtils.java
Labels: cla: yes, release

#1820 Revert "Release"
  api/src/main/java/io/opencensus/common/OpenCensusLibraryInformation.java
  build.gradle
  examples/build.gradle
  examples/pom.xml
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentNodeUtils.java
Labels: cla: yes

#1822 Release
  api/src/main/java/io/opencensus/common/OpenCensusLibraryInformation.java
  build.gradle
  examples/build.gradle
  examples/pom.xml
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentNodeUtils.java
Labels: cla: yes

#1823 Remove deprecated package monitored-resource-util.
  RELEASING.md
  all/build.gradle
  build.gradle
  buildscripts/import-control.xml
  contrib/monitored_resource_util/README.md
  contrib/monitored_resource_util/build.gradle
  contrib/monitored_resource_util/src/main/java/io/opencensus/contrib/monitoredresource/util/MonitoredResource.java
  contrib/monitored_resource_util/src/main/java/io/opencensus/contrib/monitoredresource/util/MonitoredResourceUtils.java
  contrib/monitored_resource_util/src/main/java/io/opencensus/contrib/monitoredresource/util/ResourceKeyConstants.java
  contrib/monitored_resource_util/src/main/java/io/opencensus/contrib/monitoredresource/util/ResourceType.java
  contrib/monitored_resource_util/src/test/java/io/opencensus/contrib/monitoredresource/util/MonitoredResourceTest.java
  contrib/monitored_resource_util/src/test/java/io/opencensus/contrib/monitoredresource/util/MonitoredResourceUtilsTest.java
  exporters/metrics/ocagent/build.gradle
  exporters/trace/ocagent/build.gradle
  settings.gradle
Labels: cla: yes, contrib, resource

#1824 Clean up a few nullable annotations.
  api/src/main/java/io/opencensus/metrics/data/Exemplar.java
  api/src/main/java/io/opencensus/resource/Resource.java
Labels: build, cla: yes, static analysis

#1827 Update release versions for all readme and build files.
  README.md
  contrib/appengine_standard_util/README.md
  contrib/dropwizard/README.md
  contrib/dropwizard5/README.md
  contrib/exemplar_util/README.md
  contrib/grpc_util/README.md
  contrib/http_jaxrs/README.md
  contrib/http_jetty_client/README.md
  contrib/http_servlet/README.md
  contrib/http_util/README.md
  contrib/log_correlation/log4j2/README.md
  contrib/log_correlation/stackdriver/README.md
  contrib/spring/README.md
  contrib/spring_sleuth_v1x/README.md
  contrib/zpages/README.md
  examples/build.gradle
  examples/pom.xml
  exporters/stats/prometheus/README.md
  exporters/stats/signalfx/README.md
  exporters/stats/stackdriver/README.md
  exporters/trace/datadog/README.md
  exporters/trace/instana/README.md
  exporters/trace/jaeger/README.md
  exporters/trace/logging/README.md
  exporters/trace/stackdriver/README.md
  exporters/trace/zipkin/README.md
Labels: cla: yes

#1826 Examples: Uncomment OcAgentExportersQuickStart.
  examples/build.gradle
  examples/pom.xml
Labels: build, cla: yes, examples

#1828 Update changelog with v0.20.0 release.
  CHANGELOG.md
Labels: cla: yes
