Repository census-instrumentation/opencensus-java, pull requests merged in 2019-01, with the labels that each got.

#1646 Checker Framework: 2.5.7 -> 2.5.8
  build.gradle
Labels: cla: yes, static analysis

#1645 Add Http servlet listener and filter.
  build.gradle
  buildscripts/import-control.xml
  contrib/http_servlet/build.gradle
  contrib/http_servlet/src/main/java/io/opencensus/contrib/http/servlet/OcHttpServletFilter.java
  contrib/http_servlet/src/main/java/io/opencensus/contrib/http/servlet/OcHttpServletListener.java
  contrib/http_servlet/src/main/java/io/opencensus/contrib/http/servlet/OcHttpServletUtil.java
  contrib/http_servlet/src/test/java/io/opencensus/contrib/http/servlet/OcHttpServletFilterTest.java
  contrib/http_servlet/src/test/java/io/opencensus/contrib/http/servlet/OcHttpServletListenerTest.java
Labels: cla: yes

#1648 fix version for http servlet in Readme file.
  contrib/http_servlet/README.md
  contrib/http_servlet/build.gradle
Labels: cla: yes

#1649 build: update dependency versions.
  build.gradle
Labels: build, cla: yes

#1647 Add metrics util and helper classes to read metrics.
  CHANGELOG.md
  all/build.gradle
  build.gradle
  buildscripts/import-control.xml
  exporters/metrics/util/README.md
  exporters/metrics/util/build.gradle
  exporters/metrics/util/src/main/java/io/opencensus/exporter/metrics/util/DaemonThreadFactory.java
  exporters/metrics/util/src/main/java/io/opencensus/exporter/metrics/util/IntervalMetricReader.java
  exporters/metrics/util/src/main/java/io/opencensus/exporter/metrics/util/MetricExporter.java
  exporters/metrics/util/src/main/java/io/opencensus/exporter/metrics/util/MetricReader.java
  exporters/metrics/util/src/test/java/io/opencensus/exporter/metrics/util/FakeMetricExporter.java
  exporters/metrics/util/src/test/java/io/opencensus/exporter/metrics/util/IntervalMetricReaderTest.java
  exporters/metrics/util/src/test/java/io/opencensus/exporter/metrics/util/MetricReaderTest.java
  settings.gradle
Labels: cla: yes

#1652 Add trace exporter for Datadog.
  CHANGELOG.md
  build.gradle
  buildscripts/import-control.xml
  exporters/trace/datadog/README.md
  exporters/trace/datadog/build.gradle
  exporters/trace/datadog/src/main/java/io/opencensus/exporter/trace/datadog/DatadogExporterHandler.java
  exporters/trace/datadog/src/main/java/io/opencensus/exporter/trace/datadog/DatadogSpan.java
  exporters/trace/datadog/src/main/java/io/opencensus/exporter/trace/datadog/DatadogTraceConfiguration.java
  exporters/trace/datadog/src/main/java/io/opencensus/exporter/trace/datadog/DatadogTraceExporter.java
  exporters/trace/datadog/src/test/java/io/opencensus/exporter/trace/datadog/DatadogExporterHandlerTest.java
  settings.gradle
Labels: cla: yes, exporters, tracing

#1632 Exporter/Metrics/OcAgent: Add worker thread and exporter.
  exporters/metrics/ocagent/src/main/java/io/opencensus/exporter/metrics/ocagent/OcAgentMetricsExporter.java
  exporters/metrics/ocagent/src/main/java/io/opencensus/exporter/metrics/ocagent/OcAgentMetricsExporterWorker.java
Labels: cla: yes, exporters, metrics

#1656 Change Prometheus exporter to use the new util package.
  exporters/stats/prometheus/build.gradle
  exporters/stats/prometheus/src/main/java/io/opencensus/exporter/stats/prometheus/PrometheusStatsCollector.java
Labels: cla: yes

#1655 http_server_status tag should hold http status code
  contrib/http_util/src/main/java/io/opencensus/contrib/http/HttpClientHandler.java
  contrib/http_util/src/main/java/io/opencensus/contrib/http/HttpServerHandler.java
Labels: cla: yes

#1661 Change SignalFx stats exporter to use metrics util.
  exporters/stats/signalfx/build.gradle
  exporters/stats/signalfx/src/main/java/io/opencensus/exporter/stats/signalfx/SignalFxMetricExporter.java
  exporters/stats/signalfx/src/main/java/io/opencensus/exporter/stats/signalfx/SignalFxStatsExporter.java
  exporters/stats/signalfx/src/test/java/io/opencensus/exporter/stats/signalfx/SignalFxMetricExporterTest.java
Labels: cla: yes, exporters, refactoring

#1659 Change Stackdriver stats exporter to use metrics util.
  exporters/stats/stackdriver/build.gradle
  exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/CreateMetricDescriptorExporter.java
  exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/CreateTimeSeriesExporter.java
  exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtils.java
  exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExporterWorker.java
  exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsExporter.java
  exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/CreateMetricDescriptorExporterTest.java
  exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/CreateTimeSeriesExporterTest.java
  exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/FakeMetricServiceClient.java
  exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtilsTest.java
  exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverExporterWorkerTest.java
  exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsExporterTest.java
Labels: cla: yes, exporters, refactoring

#1653 Adding support for JAX-RS client and server
  contrib/http_jaxrs/README.md
  contrib/http_jaxrs/build.gradle
  contrib/http_jaxrs/src/main/java/io/opencensus/contrib/http/jaxrs/ExtendedContainerRequest.java
  contrib/http_jaxrs/src/main/java/io/opencensus/contrib/http/jaxrs/JaxrsClientExtractor.java
  contrib/http_jaxrs/src/main/java/io/opencensus/contrib/http/jaxrs/JaxrsClientFilter.java
  contrib/http_jaxrs/src/main/java/io/opencensus/contrib/http/jaxrs/JaxrsContainerExtractor.java
  contrib/http_jaxrs/src/main/java/io/opencensus/contrib/http/jaxrs/JaxrsContainerFilter.java
  contrib/http_jaxrs/src/main/java/io/opencensus/contrib/http/jaxrs/Metrics.java
  contrib/http_jaxrs/src/test/java/io/opencensus/contrib/http/jaxrs/JaxrsClientExtractorTest.java
  contrib/http_jaxrs/src/test/java/io/opencensus/contrib/http/jaxrs/JaxrsClientFilterTest.java
  contrib/http_jaxrs/src/test/java/io/opencensus/contrib/http/jaxrs/JaxrsContainerExtractorTest.java
  contrib/http_jaxrs/src/test/java/io/opencensus/contrib/http/jaxrs/JaxrsContainerFilterTest.java
  settings.gradle
Labels: cla: yes, contrib

#1669 update readme file with example for generic http client and server.
  contrib/http_util/README.md
Labels: cla: yes

#1672 update readme file with example for http servlet instrumentation.
  contrib/http_servlet/README.md
Labels: cla: yes

#1670 Update versions for guava, grpc, google cloud
  build.gradle
  contrib/agent/build.gradle
Labels: cla: yes

#1671 Update readme with an example for Jetty Http Client instrumentation.
  contrib/http_jetty_client/README.md
Labels: cla: yes

#1675 http jetty example.
  buildscripts/import-control.xml
  examples/BUILD.bazel
  examples/build.gradle
  examples/pom.xml
  examples/src/main/java/io/opencensus/examples/http/jetty/client/HelloWorldClient.java
  examples/src/main/java/io/opencensus/examples/http/jetty/server/HelloWorldServer.java
Labels: cla: yes

#1685 Remove jetty server dependency in http_servlet.
  contrib/http_servlet/build.gradle
  contrib/http_servlet/src/main/java/io/opencensus/contrib/http/servlet/OcHttpServletUtil.java
Labels: cla: yes

#1688 Update deps in examples and add support for :dependencyUpdates gradle…
  examples/build.gradle
Labels: cla: yes

#1687 Update deps and exclude opencensus artifacts from dependencies.
  build.gradle
  contrib/appengine_standard_util/build.gradle
  contrib/http_jaxrs/build.gradle
  contrib/log_correlation/stackdriver/build.gradle
  exporters/metrics/ocagent/build.gradle
  exporters/trace/datadog/src/main/java/io/opencensus/exporter/trace/datadog/DatadogExporterHandler.java
  exporters/trace/ocagent/build.gradle
Labels: cla: yes

#1689 Update bazel and maven examples tests
  examples/BUILD.bazel
  examples/opencensus_workspace.bzl
  examples/pom.xml
Labels: cla: yes

#1691 Remove format and licence tasks for tests and move to gradle.
  .travis.yml
  buildscripts/kokoro/linux_example_format.cfg
  buildscripts/kokoro/linux_example_license.cfg
  buildscripts/kokoro/linux_presubmit.sh
  buildscripts/travis_script
  examples/build.gradle
Labels: cla: yes

#1693 Cleanup config left after the format and licence tasks were removed.
  buildscripts/travis_script
Labels: cla: yes

#1692 Add option to add attributes to all exported spans to Stackdriver.
  exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverTraceConfiguration.java
  exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverTraceExporter.java
  exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandler.java
  exporters/trace/stackdriver/src/test/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandlerExportTest.java
  exporters/trace/stackdriver/src/test/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandlerProtoTest.java
Labels: cla: yes

#1698 CI: Temporarily disable example bazel build.
  .travis.yml
Labels: cla: yes, continuous integration

#1699 create scope for servlet request.
  contrib/http_servlet/src/main/java/io/opencensus/contrib/http/servlet/OcHttpServletFilter.java
  contrib/http_servlet/src/main/java/io/opencensus/contrib/http/servlet/OcHttpServletListener.java
Labels: cla: yes

#1700 Start 0.20.0 development cycle
  api/src/main/java/io/opencensus/common/OpenCensusLibraryInformation.java
  build.gradle
  examples/build.gradle
  examples/pom.xml
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentNodeUtils.java
Labels: cla: yes, release

#1701 Release
  api/src/main/java/io/opencensus/common/OpenCensusLibraryInformation.java
  build.gradle
  examples/build.gradle
  examples/pom.xml
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentNodeUtils.java
Labels: cla: yes, release

#1704 Update CHANGELOG.
  CHANGELOG.md
Labels: cla: yes, documentation, release

#1706 Update release versions for all readme and build files.
  README.md
  contrib/appengine_standard_util/README.md
  contrib/exemplar_util/README.md
  contrib/grpc_util/README.md
  contrib/log_correlation/log4j2/README.md
  contrib/log_correlation/stackdriver/README.md
  contrib/monitored_resource_util/README.md
  contrib/spring/README.md
  contrib/spring_sleuth_v1x/README.md
  contrib/zpages/README.md
  examples/build.gradle
  examples/pom.xml
  exporters/stats/prometheus/README.md
  exporters/stats/signalfx/README.md
  exporters/stats/stackdriver/README.md
  exporters/trace/instana/README.md
  exporters/trace/jaeger/README.md
  exporters/trace/logging/README.md
  exporters/trace/ocagent/README.md
  exporters/trace/stackdriver/README.md
  exporters/trace/zipkin/README.md
Labels: cla: yes, release

#1708 Add Http server and client instrumentation example in readme.
  examples/README.md
Labels: cla: yes

#1709 rollback scope creation for async request.
  contrib/http_servlet/src/main/java/io/opencensus/contrib/http/servlet/OcHttpServletListener.java
Labels: cla: yes

#1710 Refer to http-servlet example in example directory.
  contrib/http_servlet/README.md
Labels: cla: yes

#1711 Refer to http-client example in example directory.
  contrib/http_jetty_client/README.md
Labels: cla: yes

#1703 Proposal: Remove Bazel support for examples.
  .travis.yml
  RELEASING.md
  buildscripts/kokoro/linux_example_bazel.cfg
  buildscripts/kokoro/linux_presubmit.sh
  buildscripts/travis_script
  examples/BUILD.bazel
  examples/README.md
  examples/WORKSPACE
  examples/opencensus_workspace.bzl
Labels: build, cla: yes, continuous integration, discussion, examples

#1712 Small cleanup stackdriver stats exporter.
  exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtils.java
Labels: cla: yes

#1690 Remove build for java7.
  .travis.yml
  appveyor.yml
  buildscripts/travis_script
Labels: cla: yes

#1716 Exporter/Datadog: Fix typos in README.
  exporters/trace/datadog/README.md
Labels: cla: yes, documentation, exporters

#1719 Cleanup gradle after java7 build was removed.
  build.gradle
  contrib/agent/build.gradle
  exporters/trace/jaeger/build.gradle
  settings.gradle
Labels: cla: yes

#1720 Update readme code style.
  README.md
  contrib/agent/README.md
  contrib/appengine_standard_util/README.md
  contrib/dropwizard/README.md
  contrib/dropwizard5/README.md
  contrib/exemplar_util/README.md
  contrib/grpc_util/README.md
  contrib/http_jaxrs/README.md
  contrib/http_jetty_client/README.md
  contrib/http_servlet/README.md
  contrib/http_util/README.md
  contrib/monitored_resource_util/README.md
  contrib/spring/README.md
  contrib/spring_sleuth_v1x/README.md
  contrib/zpages/README.md
  examples/README.md
  exporters/metrics/ocagent/README.md
  exporters/metrics/util/README.md
  exporters/stats/signalfx/README.md
  exporters/trace/logging/README.md
  exporters/trace/ocagent/README.md
Labels: cla: yes

#1718 Deprecate MonitoredResource and change to use Resource.
  contrib/monitored_resource_util/build.gradle
  contrib/monitored_resource_util/src/main/java/io/opencensus/contrib/monitoredresource/util/AwsEc2InstanceResource.java
  contrib/monitored_resource_util/src/main/java/io/opencensus/contrib/monitoredresource/util/GcpGceInstanceResource.java
  contrib/monitored_resource_util/src/main/java/io/opencensus/contrib/monitoredresource/util/K8sContainerResource.java
  contrib/monitored_resource_util/src/main/java/io/opencensus/contrib/monitoredresource/util/MonitoredResource.java
  contrib/monitored_resource_util/src/main/java/io/opencensus/contrib/monitoredresource/util/MonitoredResourceUtils.java
  contrib/monitored_resource_util/src/main/java/io/opencensus/contrib/monitoredresource/util/ResourceKeyConstants.java
  contrib/monitored_resource_util/src/main/java/io/opencensus/contrib/monitoredresource/util/ResourceType.java
  contrib/monitored_resource_util/src/test/java/io/opencensus/contrib/monitoredresource/util/AwsEc2InstanceResourceTest.java
  contrib/monitored_resource_util/src/test/java/io/opencensus/contrib/monitoredresource/util/GcpGceInstanceResourceTest.java
  contrib/monitored_resource_util/src/test/java/io/opencensus/contrib/monitoredresource/util/K8sContainerResourceTest.java
  contrib/monitored_resource_util/src/test/java/io/opencensus/contrib/monitoredresource/util/MonitoredResourceTest.java
  contrib/monitored_resource_util/src/test/java/io/opencensus/contrib/monitoredresource/util/MonitoredResourceUtilsTest.java
  exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtils.java
  exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtilsTest.java
  exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandler.java
Labels: cla: yes

#1714 Provide creating scope for async request http-servlet.
  contrib/http_servlet/src/main/java/io/opencensus/contrib/http/servlet/OcHttpServletFilter.java
  contrib/http_servlet/src/main/java/io/opencensus/contrib/http/servlet/OcHttpServletListener.java
  contrib/http_servlet/src/main/java/io/opencensus/contrib/http/servlet/OcHttpServletUtil.java
Labels: DO NOT MERGE, cla: yes

#1724 #1707 Added missing references to 'opencensus-contrib-http-jaxrs'.
  all/build.gradle
  build.gradle
Labels: cla: yes

#1722 rollback scope creation for async request. (#1709)
  contrib/http_servlet/src/main/java/io/opencensus/contrib/http/servlet/OcHttpServletListener.java
Labels: cla: yes

#1727 Release
  api/src/main/java/io/opencensus/common/OpenCensusLibraryInformation.java
  build.gradle
  examples/build.gradle
  examples/pom.xml
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentNodeUtils.java
Labels: cla: yes, release

#1728 Update release versions for all readme and build files.
  README.md
  contrib/appengine_standard_util/README.md
  contrib/exemplar_util/README.md
  contrib/grpc_util/README.md
  contrib/http_util/README.md
  contrib/log_correlation/log4j2/README.md
  contrib/log_correlation/stackdriver/README.md
  contrib/monitored_resource_util/README.md
  contrib/spring/README.md
  contrib/spring_sleuth_v1x/README.md
  contrib/zpages/README.md
  examples/build.gradle
  examples/pom.xml
  exporters/stats/prometheus/README.md
  exporters/stats/signalfx/README.md
  exporters/stats/stackdriver/README.md
  exporters/trace/instana/README.md
  exporters/trace/jaeger/README.md
  exporters/trace/logging/README.md
  exporters/trace/ocagent/README.md
  exporters/trace/stackdriver/README.md
  exporters/trace/zipkin/README.md
Labels: cla: yes, documentation, release
