Repository census-instrumentation/opencensus-java, pull requests merged in 2019-08, with the labels that each got.

#1956 Use Zipkin quickstart script in download instructions
  exporters/trace/zipkin/README.md
Labels: cla: yes

#1960 Checker Framework: 2.9.2 -> 2.10.0
  build.gradle
Labels: cla: yes, static analysis

#1967 Replace oraclejdk8 with openjdk8 and remove jdk_switcher from Travis
  .travis.yml
  buildscripts/travis_script
Labels: cla: yes, continuous integration

#1969 Start 0.25.0 development cycle
  api/src/main/java/io/opencensus/common/OpenCensusLibraryInformation.java
  build.gradle
  examples/build.gradle
  examples/pom.xml
  exporters/metrics/ocagent/src/main/java/io/opencensus/exporter/metrics/ocagent/OcAgentNodeUtils.java
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentNodeUtils.java
Labels: cla: yes, release

#1972 Release
  api/src/main/java/io/opencensus/common/OpenCensusLibraryInformation.java
  build.gradle
  examples/build.gradle
  examples/pom.xml
  exporters/metrics/ocagent/src/main/java/io/opencensus/exporter/metrics/ocagent/OcAgentNodeUtils.java
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentNodeUtils.java
Labels: cla: yes, release
