Repository census-instrumentation/opencensus-java, pull requests merged in 2019-05, with the labels that each got.

#1870 Tests: Migrate from is(Not)SameAs to is(Not)SameInstanceAs.
  api/src/test/java/io/opencensus/metrics/DoubleCumulativeTest.java
  api/src/test/java/io/opencensus/metrics/DoubleGaugeTest.java
  api/src/test/java/io/opencensus/metrics/LongCumulativeTest.java
  api/src/test/java/io/opencensus/metrics/LongGaugeTest.java
  api/src/test/java/io/opencensus/metrics/MetricRegistryTest.java
  api/src/test/java/io/opencensus/stats/NoopStatsTest.java
  api/src/test/java/io/opencensus/tags/InternalUtilsTest.java
  api/src/test/java/io/opencensus/tags/NoopTagsTest.java
  api/src/test/java/io/opencensus/trace/CurrentSpanUtilsTest.java
  api/src/test/java/io/opencensus/trace/SpanBuilderTest.java
  api/src/test/java/io/opencensus/trace/TraceComponentTest.java
  api/src/test/java/io/opencensus/trace/TracerTest.java
  api/src/test/java/io/opencensus/trace/TracingTest.java
  api/src/test/java/io/opencensus/trace/propagation/PropagationComponentTest.java
  api/src/test/java/io/opencensus/trace/propagation/TextFormatTest.java
  build.gradle
  impl_core/src/test/java/io/opencensus/implcore/metrics/DoubleCumulativeImplTest.java
  impl_core/src/test/java/io/opencensus/implcore/metrics/DoubleGaugeImplTest.java
  impl_core/src/test/java/io/opencensus/implcore/metrics/LongCumulativeImplTest.java
  impl_core/src/test/java/io/opencensus/implcore/metrics/LongGaugeImplTest.java
  impl_core/src/test/java/io/opencensus/implcore/metrics/export/MetricProducerManagerImplTest.java
  impl_core/src/test/java/io/opencensus/implcore/tags/CurrentTagMapUtilsTest.java
  impl_core/src/test/java/io/opencensus/implcore/tags/ScopedTagMapTest.java
  impl_core/src/test/java/io/opencensus/implcore/tags/TaggerImplTest.java
Labels: cla: yes, tests

#1872 Release: Update release versions for all readme and build files.
  README.md
  contrib/appengine_standard_util/README.md
  contrib/dropwizard/README.md
  contrib/dropwizard5/README.md
  contrib/exemplar_util/README.md
  contrib/grpc_util/README.md
  contrib/http_jaxrs/README.md
  contrib/http_jetty_client/README.md
  contrib/http_servlet/README.md
  contrib/http_util/README.md
  contrib/log_correlation/log4j2/README.md
  contrib/log_correlation/stackdriver/README.md
  contrib/spring/README.md
  contrib/spring_sleuth_v1x/README.md
  contrib/zpages/README.md
  examples/build.gradle
  examples/pom.xml
  exporters/stats/prometheus/README.md
  exporters/stats/signalfx/README.md
  exporters/stats/stackdriver/README.md
  exporters/trace/datadog/README.md
  exporters/trace/elasticsearch/README.md
  exporters/trace/instana/README.md
  exporters/trace/jaeger/README.md
  exporters/trace/logging/README.md
  exporters/trace/ocagent/README.md
  exporters/trace/stackdriver/README.md
  exporters/trace/zipkin/README.md
Labels: cla: yes

#1873 Release: Update release in CHANGELOG.md
  CHANGELOG.md
Labels: cla: yes

#1874 Add missing Javadoc and fix typos.
  api/src/main/java/io/opencensus/metrics/MetricOptions.java
  benchmarks/src/jmh/java/io/opencensus/benchmarks/trace/SpanOperationsBenchmark.java
Labels: cla: yes, documentation

#1875 Disable by default RunningSpanStore, and enable if Zpages are initialized.
  CHANGELOG.md
  api/src/main/java/io/opencensus/trace/export/RunningSpanStore.java
  contrib/zpages/src/main/java/io/opencensus/contrib/zpages/ZPageHandlers.java
  impl_core/src/main/java/io/opencensus/implcore/trace/StartEndHandlerImpl.java
  impl_core/src/main/java/io/opencensus/implcore/trace/export/ExportComponentImpl.java
  impl_core/src/main/java/io/opencensus/implcore/trace/export/InProcessRunningSpanStore.java
  impl_core/src/main/java/io/opencensus/implcore/trace/export/InProcessRunningSpanStoreImpl.java
  impl_core/src/main/java/io/opencensus/implcore/trace/export/InProcessSampledSpanStoreImpl.java
  impl_core/src/main/java/io/opencensus/implcore/trace/export/RunningSpanStoreImpl.java
  impl_core/src/main/java/io/opencensus/implcore/trace/export/SampledSpanStoreImpl.java
  impl_core/src/main/java/io/opencensus/implcore/trace/internal/ConcurrentIntrusiveList.java
  impl_core/src/test/java/io/opencensus/implcore/trace/export/ExportComponentImplTest.java
  impl_core/src/test/java/io/opencensus/implcore/trace/export/InProcessRunningSpanStoreImplTest.java
  impl_core/src/test/java/io/opencensus/implcore/trace/export/NoopInProcessRunningSpanStoreTest.java
  impl_core/src/test/java/io/opencensus/implcore/trace/export/SpanExporterImplTest.java
  impl_core/src/test/java/io/opencensus/implcore/trace/internal/ConcurrentIntrusiveListTest.java
Labels: cla: yes

#1877 Log error if Spans are gc-ed without being closed.
  impl_core/src/main/java/io/opencensus/implcore/trace/RecordEventsSpanImpl.java
Labels: cla: yes, enhancement, tracing

#1879 Checker Framework: 2.8.0 -> 2.8.1
  build.gradle
Labels: cla: yes, static analysis

#1878 zPages: Enable RunningSpanStore only when /tracez is in use.
  contrib/zpages/src/main/java/io/opencensus/contrib/zpages/ZPageHandlers.java
Labels: cla: yes, contrib, tracing, zpages

#1882 Export SpanData in batches of maximum bufferSize.
  impl_core/src/main/java/io/opencensus/implcore/trace/export/SpanExporterImpl.java
Labels: cla: yes

#1881 Exporter/Trace/Stackdriver: Provide Deadline option and don't do retry by default.
  CHANGELOG.md
  exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverTraceConfiguration.java
  exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverTraceExporter.java
  exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandler.java
  exporters/trace/stackdriver/src/test/java/io/opencensus/exporter/trace/stackdriver/StackdriverTraceConfigurationTest.java
  exporters/trace/stackdriver/src/test/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandlerProtoTest.java
Labels: cla: yes, exporters, tracing

#1883 Exporter/Stats/Stackdriver: Provide Deadline option and don't do retry by default.
  CHANGELOG.md
  exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsConfiguration.java
  exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsExporter.java
  exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsConfigurationTest.java
  exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsExporterTest.java
Labels: cla: yes, exporters, stats

#1884 Exporter/Jaeger: Use configurations and add deadline.
  CHANGELOG.md
  exporters/trace/jaeger/build.gradle
  exporters/trace/jaeger/src/main/java/io/opencensus/exporter/trace/jaeger/JaegerExporterConfiguration.java
  exporters/trace/jaeger/src/main/java/io/opencensus/exporter/trace/jaeger/JaegerExporterHandler.java
  exporters/trace/jaeger/src/main/java/io/opencensus/exporter/trace/jaeger/JaegerTraceExporter.java
  exporters/trace/jaeger/src/test/java/io/opencensus/exporter/trace/jaeger/JaegerExporterConfigurationTest.java
  exporters/trace/jaeger/src/test/java/io/opencensus/exporter/trace/jaeger/JaegerExporterHandlerTest.java
Labels: cla: yes, enhancement, exporters, tracing

#1885 Exporter/Zipkin: Use configurations and add deadline.
  CHANGELOG.md
  exporters/trace/zipkin/build.gradle
  exporters/trace/zipkin/src/main/java/io/opencensus/exporter/trace/zipkin/ZipkinExporterConfiguration.java
  exporters/trace/zipkin/src/main/java/io/opencensus/exporter/trace/zipkin/ZipkinExporterHandler.java
  exporters/trace/zipkin/src/main/java/io/opencensus/exporter/trace/zipkin/ZipkinTraceExporter.java
  exporters/trace/zipkin/src/test/java/io/opencensus/exporter/trace/zipkin/ZipkinExporterConfigurationTest.java
Labels: cla: yes, enhancement, exporters, tracing

#1886 Exporter/Datadog, Elasticsearch: Add deadline option.
  CHANGELOG.md
  exporters/trace/datadog/src/main/java/io/opencensus/exporter/trace/datadog/DatadogExporterHandler.java
  exporters/trace/datadog/src/main/java/io/opencensus/exporter/trace/datadog/DatadogTraceConfiguration.java
  exporters/trace/datadog/src/main/java/io/opencensus/exporter/trace/datadog/DatadogTraceExporter.java
  exporters/trace/datadog/src/test/java/io/opencensus/exporter/trace/datadog/DatadogExporterHandlerTest.java
  exporters/trace/elasticsearch/src/main/java/io/opencensus/exporter/trace/elasticsearch/ElasticsearchTraceConfiguration.java
  exporters/trace/elasticsearch/src/main/java/io/opencensus/exporter/trace/elasticsearch/ElasticsearchTraceHandler.java
Labels: cla: yes, enhancement, exporters, tracing

#1889 Exporter/Stackdriver: Fix k8s_container resource.
  exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtils.java
  exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtilsTest.java
Labels: bug, cla: yes, exporters, stats

#1887 Exporter/Trace: Extract timeout logic to a common util artifact.
  CHANGELOG.md
  all/build.gradle
  build.gradle
  exporters/trace/util/README.md
  exporters/trace/util/build.gradle
  exporters/trace/util/src/main/java/io/opencensus/exporter/trace/util/TimeLimitedHandler.java
  settings.gradle
Labels: cla: yes, exporters, refactoring, tracing

#1890 Exporter/Trace: Refactor to use TimeLimitedHandler.
  buildscripts/import-control.xml
  exporters/trace/datadog/build.gradle
  exporters/trace/datadog/src/main/java/io/opencensus/exporter/trace/datadog/DatadogExporterHandler.java
  exporters/trace/elasticsearch/build.gradle
  exporters/trace/elasticsearch/src/main/java/io/opencensus/exporter/trace/elasticsearch/ElasticsearchTraceHandler.java
  exporters/trace/instana/build.gradle
  exporters/trace/jaeger/build.gradle
  exporters/trace/jaeger/src/main/java/io/opencensus/exporter/trace/jaeger/JaegerExporterHandler.java
  exporters/trace/util/src/main/java/io/opencensus/exporter/trace/util/TimeLimitedHandler.java
  exporters/trace/zipkin/build.gradle
  exporters/trace/zipkin/src/main/java/io/opencensus/exporter/trace/zipkin/ZipkinExporterHandler.java
Labels: cla: yes, exporters, refactoring, tracing

#1891 Exporter/Instana: Use configurations and add deadline option.
  CHANGELOG.md
  exporters/trace/instana/build.gradle
  exporters/trace/instana/src/main/java/io/opencensus/exporter/trace/instana/InstanaExporterConfiguration.java
  exporters/trace/instana/src/main/java/io/opencensus/exporter/trace/instana/InstanaExporterHandler.java
  exporters/trace/instana/src/main/java/io/opencensus/exporter/trace/instana/InstanaTraceExporter.java
Labels: cla: yes, exporters, tracing

#1892 Small cleanup for TestHandler.
  testing/src/main/java/io/opencensus/testing/export/TestHandler.java
Labels: cla: yes

#1895 Exporter/OcAgent: Make required fields non-null.
  exporters/metrics/ocagent/src/main/java/io/opencensus/exporter/metrics/ocagent/OcAgentMetricsExporter.java
  exporters/metrics/ocagent/src/main/java/io/opencensus/exporter/metrics/ocagent/OcAgentMetricsExporterConfiguration.java
  exporters/metrics/ocagent/src/test/java/io/opencensus/exporter/metrics/ocagent/OcAgentMetricsExporterConfigurationTest.java
  exporters/metrics/ocagent/src/test/java/io/opencensus/exporter/metrics/ocagent/OcAgentMetricsExporterIntegrationTest.java
  exporters/trace/ocagent/build.gradle
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporter.java
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporterConfiguration.java
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporterHandler.java
  exporters/trace/ocagent/src/test/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporterConfigurationTest.java
  exporters/trace/ocagent/src/test/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporterIntegrationTest.java
Labels: cla: yes, enhancement, exporters

#1893 Start dropping spans when the span exporter thread holds more than 10K spans references.
  exporters/metrics/ocagent/src/test/java/io/opencensus/exporter/metrics/ocagent/OcAgentMetricsExporterIntegrationTest.java
  impl_core/src/main/java/io/opencensus/implcore/trace/export/SpanExporterImpl.java
  impl_core/src/test/java/io/opencensus/implcore/trace/export/SpanExporterImplTest.java
Labels: cla: yes, exporters, tracing

#1899 Exporter/OcAgent: Add deadline option.
  CHANGELOG.md
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporter.java
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporterConfiguration.java
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporterHandler.java
  exporters/trace/ocagent/src/test/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporterConfigurationTest.java
Labels: cla: yes, enhancement, exporters

#1900 Start 0.23.0 development cycle
  api/src/main/java/io/opencensus/common/OpenCensusLibraryInformation.java
  build.gradle
  examples/build.gradle
  examples/pom.xml
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentNodeUtils.java
Labels: cla: yes, release

#1901 Release
  api/src/main/java/io/opencensus/common/OpenCensusLibraryInformation.java
  build.gradle
  examples/build.gradle
  examples/pom.xml
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentNodeUtils.java
Labels: cla: yes, release

#1902 Update release versions for all readme and build files and changelog.
  CHANGELOG.md
  README.md
  contrib/appengine_standard_util/README.md
  contrib/dropwizard/README.md
  contrib/dropwizard5/README.md
  contrib/exemplar_util/README.md
  contrib/grpc_util/README.md
  contrib/http_jaxrs/README.md
  contrib/http_jetty_client/README.md
  contrib/http_servlet/README.md
  contrib/http_util/README.md
  contrib/log_correlation/log4j2/README.md
  contrib/log_correlation/stackdriver/README.md
  contrib/spring/README.md
  contrib/spring_sleuth_v1x/README.md
  contrib/zpages/README.md
  examples/build.gradle
  examples/pom.xml
  exporters/metrics/ocagent/README.md
  exporters/stats/prometheus/README.md
  exporters/stats/signalfx/README.md
  exporters/stats/stackdriver/README.md
  exporters/trace/datadog/README.md
  exporters/trace/elasticsearch/README.md
  exporters/trace/instana/README.md
  exporters/trace/jaeger/README.md
  exporters/trace/logging/README.md
  exporters/trace/ocagent/README.md
  exporters/trace/stackdriver/README.md
  exporters/trace/zipkin/README.md
Labels: cla: yes, docs, release

#1904 Contrib/Resource: Fix a typo in test.
  contrib/resource_util/src/test/java/io/opencensus/contrib/resource/util/ContainerResourceTest.java
Labels: cla: yes, tests

#1898 Exporter/OcAgent: Add a note about netty-tcnative-boringssl dependency.
  examples/build.gradle
  exporters/metrics/ocagent/README.md
  exporters/trace/ocagent/README.md
Labels: cla: yes, docs, exporters

#1909 CI: Add JDK 10 and 11 build on Travis.
  .travis.yml
  buildscripts/travis_script
Labels: build, cla: yes, continuous integration

#1650 add support for opencensus http servlet plugin in spring cloud framework
  build.gradle
  buildscripts/import-control.xml
  contrib/spring/build.gradle
  contrib/spring/src/main/java/io/opencensus/contrib/spring/autoconfig/OpenCensusAutoConfiguration.java
  contrib/spring/src/main/java/io/opencensus/contrib/spring/autoconfig/OpenCensusProperties.java
  contrib/spring/src/main/java/io/opencensus/contrib/spring/instrument/web/HttpServletFilter.java
  contrib/spring/src/main/resources/META-INF/additional-spring-configuration-metadata.json
  contrib/spring/src/main/resources/META-INF/spring.factories
  contrib/spring/src/test/java/io/opencensus/contrib/spring/instrument/web/AbstractMvcIntegrationTest.java
  contrib/spring/src/test/java/io/opencensus/contrib/spring/instrument/web/HttpServletFilterIntegrationTests.java
  contrib/spring/src/test/resources/META-INF/spring.factories
  contrib/spring/src/test/resources/beans/HttpServletFilterIntegrationTest-context.xml
Labels: cla: yes

#1911 Increase the buffer size for the trace export batch.
  impl_core/src/main/java/io/opencensus/implcore/trace/export/ExportComponentImpl.java
Labels: cla: yes, exporters, tracing

#1912 Increase the buffer size for the trace export batch. (#1911)
  impl_core/src/main/java/io/opencensus/implcore/trace/export/ExportComponentImpl.java
Labels: cla: yes, release

#1913 Trace: Further increase span export buffer size to 2.5k.
  impl_core/src/main/java/io/opencensus/implcore/trace/export/ExportComponentImpl.java
Labels: cla: yes, enhancement, exporters, tracing

#1914 Trace: Further increase span export buffer size to 2.5k. (#1913)
  impl_core/src/main/java/io/opencensus/implcore/trace/export/ExportComponentImpl.java
Labels: cla: yes, release

#1915 Release
  api/src/main/java/io/opencensus/common/OpenCensusLibraryInformation.java
  build.gradle
  examples/build.gradle
  examples/pom.xml
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentNodeUtils.java
Labels: cla: yes, release

#1916 Update release versions for all readme and build files and changelog.
  CHANGELOG.md
  README.md
  contrib/appengine_standard_util/README.md
  contrib/dropwizard/README.md
  contrib/dropwizard5/README.md
  contrib/exemplar_util/README.md
  contrib/grpc_util/README.md
  contrib/http_jaxrs/README.md
  contrib/http_jetty_client/README.md
  contrib/http_servlet/README.md
  contrib/http_util/README.md
  contrib/log_correlation/log4j2/README.md
  contrib/log_correlation/stackdriver/README.md
  contrib/spring/README.md
  contrib/spring_sleuth_v1x/README.md
  contrib/zpages/README.md
  examples/build.gradle
  examples/pom.xml
  exporters/stats/prometheus/README.md
  exporters/stats/signalfx/README.md
  exporters/stats/stackdriver/README.md
  exporters/trace/datadog/README.md
  exporters/trace/elasticsearch/README.md
  exporters/trace/instana/README.md
  exporters/trace/jaeger/README.md
  exporters/trace/logging/README.md
  exporters/trace/ocagent/README.md
  exporters/trace/stackdriver/README.md
  exporters/trace/zipkin/README.md
Labels: cla: yes, docs, release

#1918 Exporter/Stackdriver: Expose unregister API.
  CHANGELOG.md
  exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsExporter.java
  exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsExporterTest.java
Labels: cla: yes, enhancement, exporters, metrics

#1919 add instrumentation for spring AsyncRestTemplate.
  build.gradle
  buildscripts/import-control.xml
  contrib/spring/build.gradle
  contrib/spring/src/main/java/io/opencensus/contrib/spring/autoconfig/TraceWebAsyncClientAutoConfiguration.java
  contrib/spring/src/main/java/io/opencensus/contrib/spring/instrument/web/client/TracingAsyncClientHttpRequestInterceptor.java
  contrib/spring/src/main/resources/META-INF/spring.factories
  contrib/spring/src/test/java/io/opencensus/contrib/spring/instrument/web/TraceWebAsyncClientAutoConfigurationTest.java
  contrib/spring/src/test/resources/META-INF/spring.factories
Labels: cla: yes, contrib

#1922 Test: Upgrade Mickito version and replace deprecated methods.
  api/src/test/java/io/opencensus/trace/CurrentSpanUtilsTest.java
  api/src/test/java/io/opencensus/trace/SpanTest.java
  api/src/test/java/io/opencensus/trace/TracerTest.java
  build.gradle
  contrib/agent/src/test/java/io/opencensus/contrib/agent/ResourcesTest.java
  contrib/agent/src/test/java/io/opencensus/contrib/agent/bootstrap/ContextTrampolineTest.java
  contrib/agent/src/test/java/io/opencensus/contrib/agent/bootstrap/TraceTrampolineTest.java
  contrib/agent/src/test/java/io/opencensus/contrib/agent/instrumentation/ExecutorInstrumentationTest.java
  contrib/agent/src/test/java/io/opencensus/contrib/agent/instrumentation/ThreadInstrumentationTest.java
  contrib/agent/src/test/java/io/opencensus/contrib/agent/instrumentation/UrlInstrumentationTest.java
  contrib/http_jaxrs/src/test/java/io/opencensus/contrib/http/jaxrs/JaxrsClientExtractorTest.java
  contrib/http_jaxrs/src/test/java/io/opencensus/contrib/http/jaxrs/JaxrsClientFilterTest.java
  contrib/http_jaxrs/src/test/java/io/opencensus/contrib/http/jaxrs/JaxrsContainerExtractorTest.java
  contrib/http_jaxrs/src/test/java/io/opencensus/contrib/http/jaxrs/JaxrsContainerFilterTest.java
  contrib/http_servlet/src/test/java/io/opencensus/contrib/http/servlet/OcHttpServletFilterTest.java
  contrib/http_servlet/src/test/java/io/opencensus/contrib/http/servlet/OcHttpServletListenerTest.java
  contrib/http_util/src/test/java/io/opencensus/contrib/http/AbstractHttpHandlerTest.java
  contrib/http_util/src/test/java/io/opencensus/contrib/http/HttpClientHandlerTest.java
  contrib/http_util/src/test/java/io/opencensus/contrib/http/HttpServerHandlerTest.java
  exporters/metrics/util/src/test/java/io/opencensus/exporter/metrics/util/MetricReaderTest.java
  exporters/stats/signalfx/src/test/java/io/opencensus/exporter/stats/signalfx/SignalFxMetricExporterTest.java
  exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/CreateMetricDescriptorExporterTest.java
  exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/CreateTimeSeriesExporterTest.java
  exporters/trace/instana/src/test/java/io/opencensus/exporter/trace/instana/InstanaTraceExporterTest.java
  exporters/trace/jaeger/src/test/java/io/opencensus/exporter/trace/jaeger/JaegerExporterHandlerTest.java
  exporters/trace/jaeger/src/test/java/io/opencensus/exporter/trace/jaeger/JaegerTraceExporterTest.java
  exporters/trace/logging/src/test/java/io/opencensus/exporter/trace/logging/LoggingTraceExporterTest.java
  exporters/trace/ocagent/src/test/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporterTest.java
  exporters/trace/ocagent/src/test/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceServiceRpcHandlersTest.java
  exporters/trace/stackdriver/src/test/java/io/opencensus/exporter/trace/stackdriver/StackdriverTraceExporterTest.java
  exporters/trace/zipkin/src/test/java/io/opencensus/exporter/trace/zipkin/ZipkinTraceExporterTest.java
  impl_core/src/test/java/io/opencensus/implcore/trace/export/SpanExporterImplTest.java
Labels: build, cla: yes, tests
