Repository census-instrumentation/opencensus-java, pull requests merged in 2019-02, with the labels that each got.

#1730 Example: Don't export to Stackdriver too frequent.
  examples/src/main/java/io/opencensus/examples/grpc/helloworld/HelloWorldClient.java
  examples/src/main/java/io/opencensus/examples/grpc/helloworld/HelloWorldServer.java
Labels: bug, cla: yes, examples

#1732 Update guava version.
  build.gradle
Labels: cla: yes

#1736 Update instructions for cherry-picking commits.
  RELEASING.md
Labels: cla: yes

#1735 enable javadoc for jetty client. (#1734)
  build.gradle
Labels: cla: yes

#1737 Tags: Fix Javadoc warnings.
  impl_core/src/main/java/io/opencensus/implcore/tags/TagMapImpl.java
Labels: cla: yes, documentation

#1738 Deprecated measures use instance of new measures when 1to1 mapping.
  contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcMeasureConstants.java
  contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcViews.java
  contrib/grpc_metrics/src/test/java/io/opencensus/contrib/grpc/metrics/RpcViewsTest.java
Labels: cla: yes

#1741 Clarify that realtime views are only for streaming rpcs
  contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcViews.java
Labels: cla: yes

#1740 Deprecated measures use instance of new measures when 1to1 mapping. …
  contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcMeasureConstants.java
  contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcViews.java
  contrib/grpc_metrics/src/test/java/io/opencensus/contrib/grpc/metrics/RpcViewsTest.java
Labels: cla: yes, gRPC, release

#1742 Clarify that realtime views are only for streaming rpcs (#1741)
  contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcViews.java
Labels: cla: yes, release

#1743 Release
  api/src/main/java/io/opencensus/common/OpenCensusLibraryInformation.java
  build.gradle
  examples/build.gradle
  examples/pom.xml
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentNodeUtils.java
Labels: cla: yes, release

#1744 Change Stackdriver trace to use Resource.
  buildscripts/import-control.xml
  exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandler.java
  exporters/trace/stackdriver/src/test/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandlerProtoTest.java
Labels: cla: yes, exporters, tracing

#1747 Remove bazel instructions since we don't update them
  README.md
Labels: cla: yes, documentation

#1750 Update release version.
  README.md
  contrib/appengine_standard_util/README.md
  contrib/exemplar_util/README.md
  contrib/grpc_util/README.md
  contrib/http_util/README.md
  contrib/log_correlation/log4j2/README.md
  contrib/log_correlation/stackdriver/README.md
  contrib/spring/README.md
  contrib/spring_sleuth_v1x/README.md
  contrib/zpages/README.md
  examples/pom.xml
  exporters/stats/prometheus/README.md
  exporters/stats/signalfx/README.md
  exporters/stats/stackdriver/README.md
  exporters/trace/instana/README.md
  exporters/trace/jaeger/README.md
  exporters/trace/logging/README.md
  exporters/trace/ocagent/README.md
  exporters/trace/stackdriver/README.md
  exporters/trace/zipkin/README.md
Labels: cla: yes, documentation, release

#1753 Update the REAME list in RELEASING.md
  RELEASING.md
  contrib/dropwizard/README.md
  contrib/dropwizard5/README.md
  contrib/http_jaxrs/README.md
  contrib/http_jetty_client/README.md
  contrib/http_servlet/README.md
  examples/build.gradle
  exporters/trace/datadog/README.md
Labels: cla: yes, documentation, release

#1745 add support for config option in http-servlet.
  CHANGELOG.md
  contrib/http_servlet/src/main/java/io/opencensus/contrib/http/servlet/OcHttpServletFilter.java
  contrib/http_servlet/src/test/java/io/opencensus/contrib/http/servlet/OcHttpServletFilterTest.java
Labels: cla: yes

#1754 add option for extractor and propagator for jetty client.
  CHANGELOG.md
  contrib/http_jetty_client/src/main/java/io/opencensus/contrib/http/jetty/client/OcJettyHttpClient.java
  contrib/http_jetty_client/src/test/java/io/opencensus/contrib/http/jetty/client/OcJettyHttpClientTest.java
Labels: GA-Effort, cla: yes, feature request

#1755 Documentation: Fix Gradle dependency specs
  contrib/dropwizard/README.md
  contrib/dropwizard5/README.md
Labels: cla: yes, documentation

#1757 Fix jetty https
  buildscripts/import-control.xml
  contrib/http_jetty_client/src/main/java/io/opencensus/contrib/http/jetty/client/OcJettyHttpClient.java
  contrib/http_jetty_client/src/test/java/io/opencensus/contrib/http/jetty/client/OcJettyHttpClientTest.java
Labels: GA-Effort, cla: yes

#1763 Exporter/OcAgent: Handle null resource.
  exporters/metrics/ocagent/src/main/java/io/opencensus/exporter/metrics/ocagent/OcAgentMetricsExporterWorker.java
Labels: bug, cla: yes, exporters, resource

#1765 Exporter/OcAgent: Support TLS credentials.
  buildscripts/import-control.xml
  exporters/metrics/ocagent/src/main/java/io/opencensus/exporter/metrics/ocagent/OcAgentMetricsExporter.java
  exporters/metrics/ocagent/src/main/java/io/opencensus/exporter/metrics/ocagent/OcAgentMetricsExporterConfiguration.java
  exporters/metrics/ocagent/src/main/java/io/opencensus/exporter/metrics/ocagent/OcAgentMetricsExporterWorker.java
  exporters/metrics/ocagent/src/test/java/io/opencensus/exporter/metrics/ocagent/OcAgentMetricsExporterConfigurationTest.java
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporter.java
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporterConfiguration.java
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporterHandler.java
  exporters/trace/ocagent/src/test/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporterConfigurationTest.java
Labels: API, cla: yes, exporters

#1766 Bump jaeger trace exporter version
  build.gradle
  buildscripts/import-control.xml
  exporters/trace/jaeger/src/main/java/io/opencensus/exporter/trace/jaeger/JaegerExporterHandler.java
  exporters/trace/jaeger/src/main/java/io/opencensus/exporter/trace/jaeger/JaegerTraceExporter.java
  exporters/trace/jaeger/src/test/java/io/opencensus/exporter/trace/jaeger/JaegerExporterHandlerTest.java
Labels: build, cla: yes, exporters

#1769 SpanKind is missing in HttpServerHandler and HttpClientHandler
  contrib/http_util/src/main/java/io/opencensus/contrib/http/HttpClientHandler.java
  contrib/http_util/src/main/java/io/opencensus/contrib/http/HttpServerHandler.java
  contrib/http_util/src/test/java/io/opencensus/contrib/http/HttpClientHandlerTest.java
  contrib/http_util/src/test/java/io/opencensus/contrib/http/HttpServerHandlerTest.java
Labels: cla: yes

#1770 Build: Upgrade Cloud Beta and GA versions.
  build.gradle
Labels: build, cla: yes

#1772 Checker Framework: 2.5.8 -> 2.6.0
  build.gradle
Labels: cla: yes, static analysis

#1762 Restrict people who can approve reviews. This is to ensure code quality.
  .github/CODEOWNERS
Labels: cla: yes

#1773 Exporter/Trace/OcAgent: Refactor Export RPC.
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporterHandler.java
Labels: cla: yes, exporters, tracing

#1777 Add dinooliva and rghetia to code owners.
  .github/CODEOWNERS
Labels: cla: yes

#1778 Exporter/OcAgent: Update all since tags.
  exporters/metrics/ocagent/README.md
  exporters/metrics/ocagent/src/main/java/io/opencensus/exporter/metrics/ocagent/OcAgentMetricsExporter.java
  exporters/metrics/ocagent/src/main/java/io/opencensus/exporter/metrics/ocagent/OcAgentMetricsExporterConfiguration.java
  exporters/trace/ocagent/README.md
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporter.java
  exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporterConfiguration.java
Labels: cla: yes, documentation, exporters
