Repository census-instrumentation/opencensus-java, pull requests merged in 2019-07, with the labels that each got.

#1948 Checker Framework: 2.8.2 -> 2.9.0
  build.gradle
Labels: cla: yes, static analysis

#1950 Exporter/Stackdriver: Fix stale document on interval.
  exporters/stats/stackdriver/README.md
  exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsConfiguration.java
  exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsConfigurationTest.java
  exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsExporterTest.java
Labels: cla: yes, docs, exporters

#1951 Build: Upgrade gRPC and Google dependency versions.
  build.gradle
  contrib/agent/src/integration-test/java/io/opencensus/contrib/agent/instrumentation/ExecutorInstrumentationIT.java
  contrib/agent/src/integration-test/java/io/opencensus/contrib/agent/instrumentation/ThreadInstrumentationIT.java
  contrib/agent/src/test/java/io/opencensus/contrib/agent/bootstrap/TraceTrampolineTest.java
  contrib/agent/src/test/java/io/opencensus/contrib/agent/instrumentation/ExecutorInstrumentationTest.java
  contrib/agent/src/test/java/io/opencensus/contrib/agent/instrumentation/ThreadInstrumentationTest.java
  contrib/agent/src/test/java/io/opencensus/contrib/agent/instrumentation/UrlInstrumentationTest.java
  examples/build.gradle
  exporters/metrics/ocagent/src/test/java/io/opencensus/exporter/metrics/ocagent/OcAgentMetricsExporterIntegrationTest.java
  exporters/trace/ocagent/src/test/java/io/opencensus/exporter/trace/ocagent/TraceProtoUtilsTest.java
  exporters/trace/stackdriver/src/test/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandlerProtoTest.java
Labels: build, cla: yes

#1955 use regular thread for to expose errors in appengine
  exporters/metrics/util/src/main/java/io/opencensus/exporter/metrics/util/DaemonThreadFactory.java
  exporters/metrics/util/src/main/java/io/opencensus/exporter/metrics/util/IntervalMetricReader.java
  impl_core/src/main/java/io/opencensus/implcore/internal/DaemonThreadFactory.java
Labels: cla: yes

#1957 Use HTTPS links in Zipkin exporter README
  exporters/trace/zipkin/README.md
Labels: cla: yes
